### PR TITLE
✨ Frontend: S4L Light product

### PR DESCRIPTION
**Pull request by odeimaiz**
S4L Light (s4llight):
- [x] Frontend app
- [x] Logos
- [x] Dashboard
  - [x] One + button only: sim4life
  - [x] Templates -> Tutorials
  - [x] Hide Data
- [x] Do not show maximize/restore iframe button

Sim4LifeLight

### CODE REVIEW

**Review by mguidon — APPROVED** [review]

**Review by pcrespov — COMMENTED** [review]
looks good! :-)

I still think all graphic assets should be moved outside from the repository. This way designers/artists can change those at any time without having to go through all the PR+CI+deploys ...  which is currently is in the order of "days" if you want e.g. to deploy in production.

**Comment by odeimaiz** [comment]
> looks good! :-)
> 
> I still think all graphic assets should be moved outside from the repository. This way designers/artists can change those at any time without having to go through all the PR+CI+deploys ... which is currently is in the order of "days" if you want e.g. to deploy in production.

Correct. But still, if the designers create a logo which is a bit wider, than the placeholder, we might need to update few numbers in the code, or if we simply want to update one text we also need to go through all the deployments mechanism...

I agree that moving all these images outside would provide more flexibility, but the branding is not just logos.

**Comment by pcrespov** [comment]
> Correct. But still, if the designers create a logo which is a bit wider, than the placeholder, we might need to update few numbers in the code, or if we simply want to update one text we also need to go through all the deployments mechanism...

Just a thought:  I am no expert but isn't there any technique in which you can parametrize those "style values" as well?  CSS??  then we could do the same with those and the images.

**Comment by odeimaiz** [comment]
> > Correct. But still, if the designers create a logo which is a bit wider, than the placeholder, we might need to update few numbers in the code, or if we simply want to update one text we also need to go through all the deployments mechanism...
> 
> Just a thought: I am no expert but isn't there any technique in which you can parametrize those "style values" as well? CSS?? then we could do the same with those and the images.

This external provider could also host a css or a json file with metadata, but the frontend layouts might need to be resized or rearranged.

**Review by sanderegg — APPROVED** [review]

**Review by GitHK — APPROVED** [review]

**Pull request merged**
