### PR TITLE
🎨 [Frontend] Annotation creation enhancements

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Enhancements requested by @newton1985.

- Save me one click when creating a text annotation from right click on the workbench, the position is already given.
- Keep the last changed color for the next rectangle or text annotation
- When creating a text annotation, expose all attribute options in the pop up window, not only the label
- Make the delete annotation button more visible

AnnotationsEnh

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
Q: which endpoint is used for the annotations?

**Comment by odeimaiz** [comment]
> Q: which endpoint is used for the annotations?

patch on the ``project`` level, they are part of the ``ui`` object.

**Review by pcrespov — COMMENTED** [review]
:ok_hand:

**Review by elisabettai — APPROVED** [review]
Beautiful, it helps a lot indeed.

**Comment by jsaq007** [comment]
@odeimaiz I noticed when clicking on an item the color always opens in the top right corner. Isn't it possible to open it where you clicked? From a user experience it would be much nicer. Just my 2c worth.

**Review by jsaq007 — COMMENTED** [review]
In general nice one. I have two issues which I find a little unintuitive from a user perspective. As mentioned in my comment when clicking in an item the editor always opens in the top right corner. The second is the delete/remove button is then down in the bottom right corner, (Took a little time to find that one 🤔).

I would think it better to have the delete button in the form/editor popup and if possible the editor to open where you clicked or as close to the item you click on as possible.

**Review by jsaq007 — APPROVED** [review]
In general nice one. I have one issues which I find a little unintuitive from a user perspective. As mentioned in my comment when clicking in an item the editor always opens in the top right corner.

I would think it better,  if possible the editor to open where you clicked or as close to the item you click on as possible.

**Comment by odeimaiz** [comment]
> In general nice one. I have one issues which I find a little unintuitive from a user perspective. As mentioned in my comment when clicking in an item the editor always opens in the top right corner.
> 
> I would think it better, if possible the editor to open where you clicked or as close to the item you click on as possible.

@jsaq007 will do 👍

**Pull request merged**
