### PR TITLE
🎨⚗️Comp backend/bugfix/work stealing (⚠️ devops)

### PR DESCRIPTION
**Pull request by sanderegg**
## What do these changes do?

As noted while testing, there are some cases where the dask-workers are not balancing the workload optimally.
As explained in the [dask-distributed documentation](https://distributed.dask.org/en/stable/scheduling-policies.html#adjusting-or-disabling-queuing), the queue of each worker may be adjusted by changing the number of threads a worker provides and/or the *worker-saturation*. Since the first one is easily changeable, this PR allows to do just that.
In a billable product where 1 machine can run 1 job it also does not really make sense to provide more than 1 thread per worker.

Therefore a new ENV is introduced at the clusters-keeper service level.

Bonus:
- improvements to e2e playwright code in general and for the sleepers in particular

## Dev Checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

## DevOps Checklist
- New ENVironment variable ```CLUSTERS_KEEPER_DASK_NTHREADS``` (see https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/306)

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
nice, thanks!

**Review by YuryHrytsuk — COMMENTED** [review]
Is the new ENV safe? Can we merge it immediately for all deployments?

**Review by GitHK — APPROVED** [review]
👍

**Comment by sanderegg** [comment]
> Is the new ENV safe? Can we merge it immediately for all deployments?

@YuryHrytsuk : I am not sure why it would not be safe. it is an addition, so yes it is fully safe or am I missing something there?

**Comment by YuryHrytsuk** [comment]
> > Is the new ENV safe? Can we merge it immediately for all deployments?
> 
> @YuryHrytsuk : I am not sure why it would not be safe. it is an addition, so yes it is fully safe or am I missing something there?

No worries. I am asking because I don't know

**Review by YuryHrytsuk — APPROVED** [review]

**Pull request merged**
