### PR TITLE
♻️ Add common library

### PR DESCRIPTION
**Pull request by giancarloromeo**
## What do these changes do?
The idea is to create a common-library that will contain all the `domain-agnostic` and _reusable_ components (base classes, validators).

Before, everything was included into `models-library`.

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
Thanks. Q: What is the advantage of having this library?

**Review by GitHK — COMMENTED** [review]
please ask me for a review again when done

**Review by pcrespov — COMMENTED** [review]
As I mentioned this morning, you will have to add it to all requirements of all services. 

As a rule of thumb: wherever in `requirements` where you use e.g. `models-library` you need to add this library


image

**Review by GitHK — APPROVED** [review]
All good, we'll need to add it the the service where we use it.

@giancarloromeo add yourself to the code owners file as well 😃

**Pull request merged**
