### PR TITLE
✨Frontend: Update all templates

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

As requested by @habz-bs, this PR makes possible to Update all Templates with one click.

UpdateAll

### CODE REVIEW

**Review by mguidon — APPROVED** [review]
Nice!

**Review by pcrespov — COMMENTED** [review]
:+1:

**Review by GitHK — APPROVED** [review]
👍 
Question is this function available to all users or just limited to certain groups?

**Comment by odeimaiz** [comment]
> 👍 Question is this function available to all users or just limited to certain groups?

It will apply to the those templates that you have write access

**Pull request merged**
