### PR TITLE
🎨 Feature: Tour de S4L

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Update the terminology to follow rocket's approach
- [x] Do not show Panddy, or any other animal, next to the guided tours list :(
- [x] Move the tours to json files to make them more flexible
  - [x] [Add these tours](https://z43.manuscript.com/f/cases/186485/sim4life-io-Guided-Tour-Framework-automatically-starting-after-the-login)

https://www.youtube.com/watch?v=Yt3p-F2x7rY
GuidedTours

## Related issue/s

related to https://github.com/ITISFoundation/osparc-issues/issues/931

### CODE REVIEW

**Review by mguidon — APPROVED** [review]
Brawo!

**Review by pcrespov — COMMENTED** [review]
🎉 Cauterets-Cambasque, Puy de Dôme and Grand Colombier

**Review by elisabettai — APPROVED** [review]
Very cool, no need of user manuals anymore! 🎉 
Maybe we could also add an item for the wallets, when everything is ready (and  MAYBE mention there that  you start to pay when you start a service...)

Can this guided tour be added to osparc.io as well?

**Comment by odeimaiz** [comment]
> 🎉 Cauterets-Cambasque, Puy de Dôme and Grand Colombier

Comment of the month 💪

**Comment by odeimaiz** [comment]
> Maybe we could also add an item for the wallets, when everything is ready (and MAYBE mention there that you start to pay when you start a service...)

Definitely. For now, I just stick to the Guided Tours provided by the App Team, but I also think that a Tour de Wallet is required.

> Can this guided tour be added to osparc.io as well?

Yes, very easy to add.

**Review by cosfor1 — APPROVED** [review]
Very nice!

**Pull request merged**
