### PR TITLE
Service Catalog cards

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Improve service card in Service Catalog
- [x] Show thumbnail instead of description if available, if not, show description.
- [x] Description as tool-tip.

ServiceCatalog

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
very pretty

**Review by GitHK — COMMENTED** [review]
Do I have to enable/add something to view this? I still can't see the images.

**Comment by odeimaiz** [comment]
> Do I have to enable/add something to view this? I still can't see the images.

Well, you have to set the thumbnail yourself.

**Review by GitHK — APPROVED** [review]
👍

**Review by KZzizzle — APPROVED** [review]
let's see if it makes it through CI =)

**Pull request merged**
