### PR TITLE
Read only mode for Viewer role

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
Regarding the study section in the case related to this PR, after some discussions with @sanderegg, we agreed that the following has to be implemented:
- [x] Study owner is able to assign viewer rights to a collaborator (downgrade)
- [x] The viewer-user is able to open the study but the changes that are serialized in the study model are not saved. When opening the study a Flash message is shown saying that changes will not be saved.
- [x] A ReadOnly icon is shown in the study card and also in the NavigationBar.
- [x] The viewer-user can't rename or delete a node, neither add a new one. (It will anyway not be saved).
- [x] Run and stop buttons are hidden.

## Related issue number
related to https://github.com/ITISFoundation/osparc-issues/issues/345

ViewerRole1

## Checklist

- [ ] Did you change any service's API? Then make sure to bundle document and upgrade version (``make openapi-specs``, ``git commit ...`` and then ``make version-*``)
- [ ] Unit tests for the changes exist
- [ ] Runs in the swarm
- [ ] Documentation reflects the changes
- [ ] New module? Add your github username to [.github/CODEOWNERS](.github/CODEOWNERS)

### CODE REVIEW

**Review by GitHK — COMMENTED** [review]
All that was listed checks out to work as expected.
The only issue I have are jupyter-notebooks and their content. Even if the user is a viewer he can still use the service and the files are saved and updated as before.

Do we plan on doing something for the dynamic services?

**Comment by odeimaiz** [comment]
> All that was listed checks out to work as expected.
> The only issue I have are jupyter-notebooks and their content. Even if the user is a viewer he can still use the service and the files are saved and updated as before.
> 
> Do we plan on doing something for the dynamic services?

Yes, you are right, we will discuss and tackled the issue separately.

**Review by GitHK — APPROVED** [review]
I am happy with what I see here.

**Review by ignapas — CHANGES_REQUESTED** [review]
Very cool. I only saw that when you open a study as viewer, the run and stop buttons will remain disabled forever unless the page is reloaded.

**Comment by odeimaiz** [comment]
> Very cool. I only saw that when you open a study as viewer, the run and stop buttons will remain disabled forever unless the page is reloaded.

Correct, the viewer shouldn't be able to re-execute the pipeline

**Review by ignapas — DISMISSED** [review]
Please check that we don't get any regression regarding the pipeline execution status and the status of the run & stop buttons. For this you have to run several pipelines at the same time, going in and out the studies while they run, making sure the status of the buttons make always sense. Also just run a pipeline and wait for it to finish (check also stop button). Thanks!!!

**Comment by odeimaiz** [comment]
> Please check that we don't get any regression regarding the pipeline execution status and the status of the run & stop buttons. For this you have to run several pipelines at the same time, going in and out the studies while they run, making sure the status of the buttons make always sense. Also just run a pipeline and wait for it to finish (check also stop button). Thanks!!!

All good, also I can't do that test because I can't run pipelines

**Review by sanderegg — APPROVED** [review]
:clap: :clap: gogo

**Comment by sanderegg** [comment]
> All that was listed checks out to work as expected.
> The only issue I have are jupyter-notebooks and their content. Even if the user is a viewer he can still use the service and the files are saved and updated as before.
> 
> Do we plan on doing something for the dynamic services?

we are waiting for the dynamic sidecar to fix this

**Comment by KZzizzle** [comment]
Looks pretty nice - well done Odei!

**Review by KZzizzle — APPROVED** [review]

**Comment by ignapas** [comment]
> > Please check that we don't get any regression regarding the pipeline execution status and the status of the run & stop buttons. For this you have to run several pipelines at the same time, going in and out the studies while they run, making sure the status of the buttons make always sense. Also just run a pipeline and wait for it to finish (check also stop button). Thanks!!!
> 
> All good, also I can't do that test because I can't run pipelines. If you could do it for me  ...

yeah... it's causing bugs

**Pull request merged**
