### PR TITLE
🐛 Adding metrics to dynamic-sidecar created services

### PR DESCRIPTION
**Pull request by GitHK**
## What do these changes do?

Adds metrics when services are `started` and `stopped`.
@elisabettai **NOTE:** to maintain compatibility to what was done before:
- a service is considered `started` as soon as a request to start is issued, it does not care if it starts successfully
- a service is considered `stopped` as soon as all resources for the service are removed

Produced metrics
```ini
# HELP simcore_simcore_service_webserver_services_started_total Counts the services started
# TYPE simcore_simcore_service_webserver_services_started_total counter
simcore_simcore_service_webserver_services_started_total{service_key="simcore/services/dynamic/bios-health-vns-calibrator",service_tag="1.0.18"} 1.0
# HELP simcore_simcore_service_webserver_services_started_created Counts the services started
# TYPE simcore_simcore_service_webserver_services_started_created gauge
simcore_simcore_service_webserver_services_started_created{service_key="simcore/services/dynamic/bios-health-vns-calibrator",service_tag="1.0.18"} 1.6709291583669653e+09
# HELP simcore_simcore_service_webserver_services_stopped_total Counts the services stopped
# TYPE simcore_simcore_service_webserver_services_stopped_total counter
simcore_simcore_service_webserver_services_stopped_total{result="None",service_key="simcore/services/dynamic/bios-health-vns-calibrator",service_tag="1.0.18"} 1.0
# HELP simcore_simcore_service_webserver_services_stopped_created Counts the services stopped
# TYPE simcore_simcore_service_webserver_services_stopped_created gauge
simcore_simcore_service_webserver_services_stopped_created{result="None",service_key="simcore/services/dynamic/bios-health-vns-calibrator",service_tag="1.0.18"} 1.670929236142497e+09
```

## Related issue/s

- fixes https://github.com/ITISFoundation/osparc-simcore/issues/3336
- https://github.com/ITISFoundation/osparc-issues/issues/638

## Checklist

- [x] Runs in the swarm

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
looking very good.
@elisabettai once this goes into master, could you maybe double check the values make sense? I guess https://github.com/ITISFoundation/osparc-simcore/issues/3472 will still happen.
Let's check once this one goes in. I have a feeling that the fix that @mrnicegyu11 did to the webserver prometheus scraping might multiply the entries by the amount of tasks (which is from the viewpoint of prometheus correct). This could indicate that I need to make sure the rabbitMQ channel only notifies 1 webserver and not all of them.

**Review by elisabettai — APPROVED** [review]
Thanks a lot for this!
@GitHK. the definition of "Started" sounds good to me. Anyway we want to count how many times the user wants to start the service (if it then fails, it's another story 😄).

I will check the values when this goes in master, as @sanderegg suggested.

Small clarification: I assume services that are "idle" will not be counted (which makes sense). Correct me if I'm wrong.

**Comment by GitHK** [comment]
> Small clarification: I assume services that are "idle" will not be counted (which makes sense). Correct me if I'm wrong.

@elisabettai that is correct, no idle services will be counted since they never get started, which makes sense.

**Review by pcrespov — APPROVED** [review]

**Comment by elisabettai** [comment]
I'm checking the values on master with this prometheus query:
```label_replace(topk(20, rate({__name__=~"simcore_simcore_service_(director|webserver)_services_started_total:sum_by_service_key_service_tag"}[30d])*60*60*24*30), "service_name", "$3", "service_key", "simcore/services/(dynamic|comp)/([a-zA-Z0-9]*/)?(.*)")```

I'm checking if the values for jupyter-smash make sense. The last value I read on the graph is **~53k** and we have values from about a month ago (i.e. from Dec.14, when this PR was merged).
From the e2e testing we run every hour the Jupyterlabs template (2x jupyter-smash) and 10 times the same as part of the parallel test. 

So **in a month, we should have: 15840 runs**.

If I'm not doing anything wrong, the value we're getting seems high. @sanderegg, is this expected based on #3472? I see that the PR that fixed #3472 was merged on Dec. 15, so I'd expect to have the correct numbers now.

**Pull request merged**
