### PR TITLE
Adds timestamp when duplicating and importing

### PR DESCRIPTION
**Pull request by GitHK**
## What do these changes do?

When a study is imported or duplicated, a timestamp will be added to its name to help users more easily tell them apart.

## Related issue/s

closes https://github.com/ITISFoundation/osparc-issues/issues/444

### CODE REVIEW

**Review by odeimaiz — APPROVED** [review]

**Comment by GitHK** [comment]
> Actually not sure if this is the best solution - people may clone on different days for example so then full date would be added also. A member of team black also mentioned that colons are tricky in file names (not sure if this will impact the exported file name but if so, Windows will not be ok with it)

Would you prefer something like `20210331092033` which is the date without any separators?

**Comment by KZzizzle** [comment]
Haha honestly we didn't converge to an agreement during the team black meeting. This is one way to do it which forces them to rename studies... The other alternative was _copy, _copy_copy.... Which is also ugly. If the colons don't ever end up in any exported file name I'm less concerned so another possibility is 2021:03:31:09:28:30 ...

**Comment by GitHK** [comment]
> Haha honestly we didn't converge to an agreement during the team black meeting. This is one way to do it which forces them to rename studies... The other alternative was _copy, _copy_copy.... Which is also ugly. If the colons don't ever end up in any exported file name I'm less concerned so another possibility is 2021:03:31:09:28:30 ...

The `_copy_copy...` is not possible, as it dose not look at the history of names for all the projects. Adding the columns is the best way. In the future they will get stripped from file names, for now this name dose not end up in any file name.

**Review by KZzizzle — APPROVED** [review]
Gorgeous 😆

**Pull request merged**
