### PR TITLE
Large study card supports Study Model

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

The main purpose of this PR was to enhance the Large card to support the Study Model instead of a serialized Study.

Since now it works with the model, this PR ended up providing a necessary refactoring of many widgets that were running around the Medium and Large cards and we managed to get rid of signals and duplicated calls to the backend.

#### Bonus:
- [x] Show webserver's error messages for Import/Export

## Related issue/s
closes https://github.com/ITISFoundation/osparc-simcore/issues/1633
closes https://github.com/ITISFoundation/osparc-simcore/issues/1612

### CODE REVIEW

**Review by GitHK — COMMENTED** [review]
The part regarding the study card seems to work as expected.

When importing a study if an error is generated, it is still not properly handled.

**Review by KZzizzle — APPROVED** [review]
awesome

**Review by sanderegg — APPROVED** [review]
:+1:

**Comment by odeimaiz** [comment]
> The part regarding the study card seems to work as expected.
> 
> When importing a study if an error is generated, it is still not properly handled.

Done

**Review by GitHK — APPROVED** [review]
Yes, now it properly displays errors when there is an issue during the import

**Pull request merged**
