### PR TITLE
Fix: update metadata from Study Editor

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
- [x] Study metadata can be updated from within the StudyEditor
- [x] Ask for confirmation before deleting node

## Related issue number
closes ITISFoundation/osparc-issues#271
closes ITISFoundation/osparc-issues#276
closes ITISFoundation/osparc-issues#278
closes ITISFoundation/osparc-issues#290

deleteNode

## Checklist

- [ ] Did you change any service's API? Then make sure to bundle document and upgrade version (``make openapi-specs``, ``git commit ...`` and then ``make version-*``)
- [ ] Unit tests for the changes exist
- [ ] Runs in the swarm
- [ ] Documentation reflects the changes
- [ ] New module? Add your github username to [.github/CODEOWNERS](.github/CODEOWNERS)

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
A small screenshot of changes?

**Review by GitHK — CHANGES_REQUESTED** [review]
All work except: https://github.com/ITISFoundation/osparc-issues/issues/276

**Comment by odeimaiz** [comment]
> A small screenshot of changes?

Added

**Review by sanderegg — APPROVED** [review]
great!!

**Pull request merged**
