### PR TITLE
✨ Study from Template: Show messages and progress

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Show the feedback that the backend provides when a study is being created out of a template.

### Bonus:
- retry nodeState regardless error status

StudyFromTemplate

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
🎉  fantastic! Much better!

I would replace the UUID of the project in the message and change it for the display name

**Comment by odeimaiz** [comment]
> I would replace the UUID of the project in the message and change it for the display name

Yes, @sanderegg is already on that 👍

**Comment by elisabettai** [comment]
Nice! I had the same comment of Pedro on the UUID. 
Minor thing: changing "project" to "Study" for consistency.

**Comment by odeimaiz** [comment]
> Nice! I had the same comment of Pedro on the UUID. Minor thing: changing "project" to "Study" for consistency.

@sanderegg, merci 🤗

**Review by pcrespov — APPROVED** [review]

**Pull request merged**
