### PR TITLE
3rd party tokens redesign

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

3rd party tokens redesign

Bonus:
- Fixed Mattward and Opencor portal tests

tokens

### CODE REVIEW

**Review by mguidon — APPROVED** [review]
two things come to mind:
1. What is the z43 service that we suppor?t
2. blackfynn will soon become Pennsieve

**Review by GitHK — APPROVED** [review]
Could you add a pop-up before removing the API-key and this blackfynn credentials? It is annoying if just click by mistake, because I'd have to regenerate the API keys and change the scripts.

**Comment by odeimaiz** [comment]
> Could you add a pop-up before removing the API-key and this blackfynn credentials? It is annoying if just click by mistake, because I'd have to regenerate the API keys and change the scripts.

Done

**Comment by odeimaiz** [comment]
> two things come to mind:
> 
> 1. What is the z43 service that we suppor?t
> 2. blackfynn will soon become Pennsieve

1. Just some dummy data for the animation. The 3rd party token thing was very blackfynn oriented, now it's more flexible and soon we will be able to add in the same section the necessary credentials form filesrv.
2. Very good

**Pull request merged**
