### PR TITLE
Fix bugs

### LINKED ISSUE #2042: Organizations Menu Navigation is Very Laggy/Buggy
When I try to create or edit an organization, it is often difficult to get the list of the organization's users. When clicking on an organization name, sometimes nothing loads and sometimes it loads but after multiple clicks/switching organizations and back. Then, trying to switch to a different organization will often take a long time or will not work.  See gif below:

organization_bug
image

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
Fixes few bugs:
#2032 Study editor properly closes: auto save timer is stopped and node iFrames are closed
#2042 Organization list item can be clicked anywhere in the item and the list of members will be shown
#2055 Within the StudyEditor "More Info" of the study can be opened again
#2068 Fixed (a bit) tempEdge position with scale and scroll

#2051 Some refactoring in the FilePIcker&co for facilitating the serialization of the different type of outputs

## Related issue number
closes https://github.com/ITISFoundation/osparc-simcore/issues/2032
closes https://github.com/ITISFoundation/osparc-simcore/issues/2042
closes https://github.com/ITISFoundation/osparc-simcore/issues/2055
related to https://github.com/ITISFoundation/osparc-simcore/issues/2068
related to https://github.com/ITISFoundation/osparc-simcore/issues/2051

## Checklist

- [ ] Did you change any service's API? Then make sure to bundle document and upgrade version (``make openapi-specs``, ``git commit ...`` and then ``make version-*``)
- [ ] Unit tests for the changes exist
- [ ] Runs in the swarm
- [ ] Documentation reflects the changes
- [ ] New module? Add your github username to [.github/CODEOWNERS](.github/CODEOWNERS)

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
looks marvelous

**Review by GitHK — APPROVED** [review]
All looks good.

If you may, there when the study is fully zoomed out scrollbars appear and dragging them dose nothing (which is correct but awkward)

**Review by pcrespov — APPROVED** [review]

**Review by KZzizzle — APPROVED** [review]
thanks Odei!

**Comment by odeimaiz** [comment]
> All looks good.
> 
> If you may, there when the study is fully zoomed out scrollbars appear and dragging them dose nothing (which is correct but awkward)

It will be tackled separately. The scroll bar is a bit out of control at the moment :(

**Pull request merged**
