### PR TITLE
🎨 Clean up Navigation Bar

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Merge manual and feedback menus into help menu
- [x] Split User Center into My Account and Billing Center
- [x] Remove name from User Menu Button
- [x] Prettier menus
- [x] Mini Profile on User Menu

NavBar

### CODE REVIEW

**Review by matusdrobuliak66 — COMMENTED** [review]
:+1:

**Review by pcrespov — COMMENTED** [review]
schoeeen! :+1:

**Review by elisabettai — APPROVED** [review]
Very nice!

Suggestion: why not renaming "User Center" to "My Profile" or "My account"? In the end you go there to change your password (and check resource usage). 
In this way it will be more similar to how other web applications call similar "pages".

**Review by GitHK — COMMENTED** [review]
👍

**Review by sanderegg — COMMENTED** [review]
nice! 💯

**Review by ignapas — COMMENTED** [review]
I agree with Eli's comment. I would not place a question mark in the navigation bar. I think it looks really bad... but if you really want to do it, I would go for something more like 
image

**Comment by elisabettai** [comment]
> And I would not place a question mark in the navigation bar. I think it looks really bad... but if you really want to do it, I would go for something more like 

I've quickly looked at other web applications, and Help & co. is normally under the User button as well. If you want to follow IP's suggestion (=remove the "?" from the navigation bar), you could add a section for Help&co under the user menu.

**Comment by odeimaiz** [comment]
@elisabettai @ignapas done:
image

**Review by matusdrobuliak66 — APPROVED** [review]

**Pull request merged**
