### PR TITLE
⬆️ upgrade docker buildx to v0.7.1

### PR DESCRIPTION
**Pull request by sanderegg**
## What do these changes do?

upgrade Docker buildx to latest version v0.7.1

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]
Cool!
I have been wondering about these configs ... and how they shall connect/sync to the devel environment.  I guess you agree with me that the CI is "the source of truth", right? How this information reach my devel environment?

 For instance, assume I did not read this update. How do I know that I should update buildx in my dev machine to match this.?

Should we have some recipe in the Makefile that does that check? ``make check-tools`` would compare the CI environ vs devel environ and make a report that says e.g. WARNING the version of your tool X does not match the "official" CI version etc ...

**Review by KZzizzle — APPROVED** [review]
I'm awestruck

**Review by GitHK — APPROVED** [review]

**Comment by mrnicegyu11** [comment]
> Cool! I have been wondering about these configs ... and how they shall connect/sync to the devel environment. I guess you agree with me that the CI is "the source of truth", right? How this information reach my devel environment?
> 
> For instance, assume I did not read this update. How do I know that I should update buildx in my dev machine to match this.?
> 
> Should we have some recipe in the Makefile that does that check? `make check-tools` would compare the CI environ vs devel environ and make a report that says e.g. WARNING the version of your tool X does not match the "official" CI version etc ...

This sounds nice. I noted the change for now manually.

lgtm

**Review by mrnicegyu11 — APPROVED** [review]

**Comment by sanderegg** [comment]
I do not think this has any consequence on devops.
@pcrespov 
I originally pinned the version, because docker buildx version 0.6.0 was having an issue and failing the builds... 
now I realized my computer had already updated to v0.7.1 so that is why I took the initiative.

but you may be right about this version. I would like that dependabot take care of it...

**Pull request merged**
