### PR TITLE
More visible Maximize button

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
- [x] The actual content of the iframe doesn't take all the available space:
  - [x] restart and maximize buttons are more visible and do not overlap with buttons in the iframe content
  - [x] Adds a thicker separation between osaprc and the dnyamic service

actionButtons

#### Bonus
- [x] Allow sending parent = null

## Related issue/s
related to https://github.com/ITISFoundation/osparc-issues/issues/439
closes https://github.com/ITISFoundation/osparc-issues/issues/438

### CODE REVIEW

**Review by mguidon — COMMENTED** [review]
Much better. But does it no take a bit too much space away from the fullscreen?

**Review by sanderegg — APPROVED** [review]
waow totally thick... ;)

**Review by GitHK — APPROVED** [review]
It really looks in the way, but if it's what it is required...

**Comment by KZzizzle** [comment]
I get the impression that the service view is getting to be pretty busy in general, mainly because new things are added all the time. Ideally for me, that view would be refactored so that there's just more space in general:
* moving input/output to the sidebar since in service view people don't care about the study info or rest of nodes anyway
* The above would make some room so that the expand/collapse could be on the existing service bar
* The breadcrumbs could extend the whole width so there's more space in case someone has a huge pipeline
* Output file download can be put into the outputs subwindow which is maybe more intuitive - with the current columns, it doesn't make sense to do that but with a subwindow it could work

Current:
image

Suggested: 
image

**Pull request merged**
