### PR TITLE
🐛 adjust storage user project permission based on new logic with workspaces

### PR DESCRIPTION
**Pull request by matusdrobuliak66**
## What do these changes do?
- 🐛 adjust storage user project permission based on new logic with workspaces
  - This endpoint needs to be refactored, and we also need to add pagination. For now, I am making it backward-compatible so that it also lists projects the user has access to through shared workspaces.

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by odeimaiz — APPROVED** [review]

**Review by sanderegg — APPROVED** [review]
thanks!

**Review by sanderegg — APPROVED** [review]
no tests?

**Review by GitHK — APPROVED** [review]

**Comment by pcrespov** [comment]
>   * This endpoint needs to be refactored, and we also need to add pagination. For now, I am making it backward-compatible so that it also lists projects the user has access to through shared workspaces.
> 


PLease add an issue and tag/classify it appropriately so we do not miss this. thx

**Review by pcrespov — COMMENTED** [review]
PLease add an issue and tag/classify it appropriately so we do not miss this. thx
and I align as well with @sanderegg ,  is this covered by any test?

**Comment by matusdrobuliak66** [comment]
> no tests?

test added :+1:

**Pull request merged**
