### PR TITLE
🎨 Frontend: Show Tiers in secondary column

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Allow users changing the Tier with the study open (secondary column)

## Bonus:
- [x] bugfix: show Service Data button even if it doesn't have outputs

SelectTier

## Dev-ops checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
Nice :+1:

**Review by mguidon — APPROVED** [review]
👍

**Review by sanderegg — APPROVED** [review]
cool!

**Review by elisabettai — APPROVED** [review]
Very nice!

**Review by pcrespov — COMMENTED** [review]
:+1:

**Review by jsaq007 — APPROVED** [review]
Nice one  👍🏼

**Pull request merged**
