### PR TITLE
🎨 Add additional thumbnail to the selectable options

### PR DESCRIPTION
**Pull request by jsaq007**
## What do these changes do?

Adds new thumbnails options

## Dev-ops checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by odeimaiz — APPROVED** [review]

**Review by bisgaard-itis — APPROVED** [review]

**Review by elisabettai — APPROVED** [review]
Nice, thanks! 
Wow, we have so many, I guess they took a conscious decision in making so many thumbnails that look somewhat similar. 😉

**Review by pcrespov — APPROVED** [review]
thx.
I have some questions and suggestions. These links are pointing to the latest version in github and you are using names to  create some sort of "version".  
Why not using git for the version control instead of renaming? And, instead of hard coding the thumbnails, why don't you use github API to get all the "published thumbnails"? 
In short, I would suggest the following:
- create a proper release workflow in the s4l-assets repo
- the front-end queries s4l-assets repo (via github API) to get the corresponding "released version". 

This approach provides a clean decoupling and frees us from having to release a new front-end everytime there are changes in the assets.

**Comment by mguidon** [comment]
> thx. I have some questions and suggestions. These links are pointing to the latest version in github and you are using names to create some sort of "version". Why not using git for the version control instead of renaming? And, instead of hard coding the thumbnails, why don't you use github API to get all the "published thumbnails"? In short, I would suggest the following:
> 
> * create a proper release workflow in the s4l-assets repo
> * the front-end queries s4l-assets repo (via github API) to get the corresponding "released version".
> 
> This approach provides a clean decoupling and frees us from having to release a new front-end everytime there are changes in the assets.

Querying should be done in the  backend. We tried the github api but it is rate-limited without tokens to about 1 call per hour

**Comment by pcrespov** [comment]
> Querying should be done in the backend. We tried the github api but it is rate-limited without tokens to about 1 call per hour

OK. And then it could be passed to the front-end via the classic config entrypoint. Moreover, we can create a dedicated /assets entrypoint for this type of things.

**Pull request merged**
