### PR TITLE
Service card

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Refactoring of the Service Card to make it more StudyCard-like (and more maintainable)

Before (1):
image

Before (2):
image

After:
ServiceLarge

### CODE REVIEW

**Review by mguidon — APPROVED** [review]
Looks much better. Thanks!

**Review by GitHK — COMMENTED** [review]
I do not see the "edit" buttons. Either as user or as tester.
Also the below happens when I click on the Quality view.
Screenshot 2021-03-18 at 08 07 44

**Comment by odeimaiz** [comment]
> I do not see the "edit" buttons. Either as user or as tester.
> Also the below happens when I click on the Quality view.
> Screenshot 2021-03-18 at 08 07 44

https://github.com/ITISFoundation/osparc-issues/issues/430

**Review by pcrespov — COMMENTED** [review]
Is there a way to edit the fields in place instead of popping a modal window? i.e. when the pencil is clicked, then there is a text-field that becomes editable ... or something in this line?

**Comment by odeimaiz** [comment]
> Is there a way to edit the fields in place instead of popping a modal window? i.e. when the pencil is clicked, then there is a text-field that becomes editable ... or something in this line?

Yes, that sounds like a nice enhancement to be applied in more editable fields. It will be tackled separately 👍

**Review by KZzizzle — APPROVED** [review]
Awesome Odei! One other comment that we could discuss (not for this PR) is that the edit pencils are very far from the field that is supposed to be edited. I wonder if at some point they could be located closer to the fields or otherwise a very discreet divider like: 

image

**Pull request merged**
