### PR TITLE
🎨 Improve Home page's layout

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Refactor home page
  - [x] Header, Content and Footer sections
  - [x] All content sections go into scroll containers
- [x] Publish Template button placed where the Open goes

StudyHomePage2

## Related issue/s

related to https://github.com/ITISFoundation/osparc-issues/issues/1278

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]
nice!

**Review by sanderegg — APPROVED** [review]

**Review by GitHK — APPROVED** [review]
👍 nice

**Review by bisgaard-itis — APPROVED** [review]
Cool! thanks

**Review by elisabettai — APPROVED** [review]
Looks nice, thanks!
Some more ideas:
1. Don't show the pipeline view tab if there's only 1 node in the Study
2. Maybe add a short description (or title) to the pipeline view tab. In the [mock-up](https://github.com/ITISFoundation/osparc-issues/issues/1278) EO added the title, but maybe that's redundant.

**Pull request merged**
