### PR TITLE
🎨 [Frontend] Small screens: Let them go

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

When a user manages to log in using a very very small screen, the User Menu button, and therefore, the Logout button are inaccessible.

In that scenario, this PR will make a dialog pop up and suggest the user to log out.

### Bonus:
- [x] Show study location in Study Details

VeryverySmall

Location in Study Details:
image

## Related issue/s

- related to https://github.com/ITISFoundation/osparc-issues/issues/1369

## Dev-ops checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
what happens if i close (i.e. press x) in the logout screen? Can I still logout?

**Comment by odeimaiz** [comment]
> what happens if i close (i.e. press x) in the logout screen? Can I still logout?

You will have missed the chance to properly logout.

**Review by jsaq007 — APPROVED** [review]
👍🏼

**Review by sanderegg — COMMENTED** [review]
what about removing the X not possible? then the only option is to logout or close the tab

**Review by ignapas — APPROVED** [review]

**Pull request merged**
