### PR TITLE
✨RabbitMQ: add persistency on rabbitmq service

### PR DESCRIPTION
**Pull request by sanderegg**
## What do these changes do?
- [x] adds a named volume to keep rabbitmq data between rabbitmq restarts

## Related issue/s

- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4279

### CODE REVIEW

**Review by mguidon — APPROVED** [review]
:+1:

**Review by mrnicegyu11 — APPROVED** [review]
great!

**Review by GitHK — APPROVED** [review]
👍 thanks for this one!

**Review by matusdrobuliak66 — APPROVED** [review]
Thanks!

**Pull request merged**
