### PR TITLE
Update Frontend to new checkpoints and checkout

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Update Resources "/projects/" -> "/repos/projects/"
- [x] Support not only tag, but also message
- [x] Update Snapshots table
- [x] Close snapshot before explicitly ```checkout``` another one

newCheckpoints

### CODE REVIEW

**Review by KZzizzle — COMMENTED** [review]
The functionality looks great and it's very cool to have versioning on oSPARC. The issues I have with the UI are ones that I mentioned before, namely:

1. "snapshot" is an unintuitive name. So unintuitive that in the demo gif, the snapshots are named "V0, V1..."  =P This is already mentioned here: https://github.com/ITISFoundation/osparc-simcore/issues/2392
2. The top bar is getting very crowded (see also https://github.com/ITISFoundation/osparc-simcore/pull/2517#issuecomment-914238160). It may be close to a point where there needs to be some consolidation of study operations:
    - guided mode
    - run options: selected node, clusters
    - export/import
    - versioning
   
I'm not sure if these requests should be here or also go into the metamodeling backlog. If they will not be tackled in this PR I can just approve.

**Comment by odeimaiz** [comment]
> I'm not sure if these requests should be here or also go into the metamodeling backlog. If they will not be tackled in this PR I can just approve.

Please, add them to the metamodeling case and we can discuss them on PM2. This is just about updating the frontend to the backend changes.

**Review by KZzizzle — APPROVED** [review]

**Review by GitHK — COMMENTED** [review]
Something is slightly off:
- if you try to take multiple snapshots without adding a node, it will not work. I'd like to make changes to the layout and be able to create a snapshot
-  also try adding a node and taking more than 3 snapshots, it sometimes stops at the first and sometimes at the second. don't know why

**Comment by odeimaiz** [comment]
> Something is slightly off:
> 
> * if you try to take multiple snapshots without adding a node, it will not work. I'd like to make changes to the layout and be able to create a snapshot
> * also try adding a node and taking more than 3 snapshots, it sometimes stops at the first and sometimes at the second. don't know why

Yes, the backend is preventing you from taking snapshots of the same thing

**Review by pcrespov — APPROVED** [review]

**Pull request merged**
