### PR TITLE
🎨 [Frontend] Prettify "Creating template" progress

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Refactor the Node Progress class to be used with Long running tasks
- [x] Show product logo on Loading screens

Before:
CreateProjectBefore

After:
CreateProject

## Related issue/s

closes https://github.com/ITISFoundation/osparc-issues/issues/1628

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by GitHK — APPROVED** [review]
👍

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by sanderegg — COMMENTED** [review]
thanks

**Review by jsaq007 — APPROVED** [review]
Looks nice. ;) Maybe the fields hidden to start is a little misleading and not consistent  with the original / starting project?

**Comment by odeimaiz** [comment]
> Looks nice. ;) Maybe the fields hidden to start is a little misleading and not consistent with the original / starting project?

That's because the sequence is not fixed.

**Pull request merged**
