### PR TITLE
🐛   First attempt to get rid of authentication pop-up when container dies (🚨 ⚠️ devops)

### PR DESCRIPTION
**Pull request by elisabettai**
## What do these changes do?
It avoids that users get the authentication pop-up when new dynamic services stop for some reason. 
For now it returns a 401 (although 503 is the correct one, and the one returned by the legacy dynamic services). Need tips on how to fix this.

## Related issue/s
- ITISFoundation/osparc-issues#726
- #2718 
- https://git.speag.com/oSparc/osparc-ops-environments/-/issues/298

## How I tested it
On master, I've added the new rules to the static-webserver. Then I create a study with a jupyterlab-math and removed the associated dy-proxy.
Without these new rule: authentication pop-up appears (and I see a 401 error code)
With these new rule: "Kernel died unexpected" window appears (but I still see a 401 error code)

Note: I didn't test much on a local deployment because the authentication pop-up doesn't appear there.

## Checklist
- [ ] We should we make sure a 503 is returned.

## DEVOPS ⚠️
- Make sure that the maintenance page still works with this MR in master
- Make sure again that the internal traefik dashboard (with route `/api`) is disabled when this is released to a deployment

### CODE REVIEW

**Review by mrnicegyu11 — APPROVED** [review]
Looks good to me as a first version, I have no input or ideas about the 401 at this point. For me, I'll have this go in and not worry too much about changing the status code. A proper error instead of the auth-pop-up is already a huge step forward!


Super great job, thanks so much for tackling this! It will make the user experience much smoother wen something fails, at least an error is displayed now :D

**Review by pcrespov — CHANGES_REQUESTED** [review]
is this ready for review or still WIP?

regex are a bit special, i would add some tests, not just a comment to do it :-)
It should be fairly easy ...
Just add an extra test in https://github.com/ITISFoundation/osparc-simcore/blob/master/packages/models-library/tests/test_basic_regex.py that
- loads the ``services/docker-compose.yml``
- iterate the ``["services"]["static-webserver"]["deploy"]["labels"]`` list
- find the items you want 
- test the match you suggest in your comment

**Review by sanderegg — APPROVED** [review]
@mrnicegyu11  needs to remove /api in deployment

**Review by mrnicegyu11 — APPROVED** [review]
Minor: I would prefer having it called `dynamic-service` rather than `modern-service`, otherwise very very nice contribution, thanks a lot for this

**Comment by elisabettai** [comment]
> Thanks a lot!
> 
> @mrnicegyu11 : legacy services are also dynamic services... dynamic-legacy and dynamic-modern or else versions?

I re-phrased with "dy-sidecar powered-services", I hope makes everyone happy. :relaxed:

**Comment by mrnicegyu11** [comment]
@Surfict fyi this PR changes / adds some traefik route priorities and might thus interfere with the maintenance page. Before releasing this further to staging or prod, we need to test in master if the maintenance page still works correctly. I will flag this PR accordingly

**Review by odeimaiz — APPROVED** [review]
Wonderful!

**Comment by elisabettai** [comment]
For the record, while testing [staging_switzer1](https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_switzer1), I didn't experience any authentication pop-up, while using "Prep2Go Light copied from AWS 23-09-2022" (a4628a32-3419-11ed-9a85-02420a0b01c2). It was often happening before. 

So test :heavy_check_mark:

**Pull request merged**
