### PR TITLE
🐛 No longer upload output ports when study is in read only mode

### PR DESCRIPTION
**Pull request by GitHK**
## What do these changes do?

Currently, due to a side effect outputs are not uploaded by the sidecar. Storage raises an error due to missing permissions to upload files when sidecar is running in read only mode.

This properly addresses the issue.

**NOTE** with @elisabettai we discussed about this. When opened in read only you cannot push outputs to downstream services. I'm not sure how this works for legacy services.

## Related issue/s

- requires https://github.com/ITISFoundation/osparc-simcore/pull/4202
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/4044
- https://github.com/ITISFoundation/osparc-issues/issues/638

### CODE REVIEW

**Comment by GitHK** [comment]
FYI: Just something to keep in mid, read my notes above. Thanks!
@mguidon @mrnicegyu11 @odeimaiz @elisabettai

**Review by mrnicegyu11 — APPROVED** [review]
Could I bother you to in fact check and write down here how it works for legacy services' outputs if they are in read only mode?

**Comment by mrnicegyu11** [comment]
thanks a lot for this! small and clean

**Comment by GitHK** [comment]
> Could I bother you to in fact check and write down here how it works for legacy services' outputs if they are in read only mode?

@mrnicegyu11 so in case of comp and legacy services outputs will not be updated. Especially for computational, since the run button is disabled.

**Review by sanderegg — APPROVED** [review]

**Review by pcrespov — APPROVED** [review]

**Review by matusdrobuliak66 — APPROVED** [review]

**Pull request merged**
