### PR TITLE
Current & Target TSR

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
- [x] Bring the concept of Current and Target TSR
- [x] Studies inherit service's "known limitations" (Transitivity of known limitations)

Unfortunately it contains the commits of https://github.com/ITISFoundation/osparc-simcore/pull/2147

Current-target:
current-target

With SelectBox:
dropdown-quality

Inherit:
limitations

## Related issue/s
related to https://github.com/ITISFoundation/osparc-issues/issues/356

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
Some suggestions:

- Minimum target TSR should be 1 star?
- UX:  I like how you set the "empty" stars but I would set its number with a number field or a drop down that indicates the actual target, e.g. "stasfactory " etc ... Visually is more clear what is the achieved and the target. 

MUST NOT merge before #2147

**Comment by odeimaiz** [comment]
> * Minimum target TSR should be 1 star?

You might not want to target that rule at all

> * UX:  I like how you set the "empty" stars but I would set its number with a number field or a drop down that indicates the actual target, e.g. "satisfactory " etc ... Visually is more clear what is the achieved and the target.

I don't think that approach is more clear. Let's see what others say.

**Review by pcrespov — APPROVED** [review]

**Comment by mguidon** [comment]
Too many stars for my taste. As @pcrespov suggested can we maybe have the target stars as a number? Or maybe do sth with colors?

**Comment by odeimaiz** [comment]
@pcrespov @mguidon @KZzizzle Here the dropdown that replaces the target start:
dropdown-quality

**Review by KZzizzle — APPROVED** [review]
amazing!

**Review by sanderegg — APPROVED** [review]

**Pull request merged**
