### PR TITLE
File Browser redesign

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR brings the concept of Folder View which is used together with the Files Tree in
- [x] File Picker
- [x] Node Output Files
- [x] Data Browser

It is meant to ease navigating files, more like a File Explorer way.

File Picker:
FilePicker

Node Output Files:
NodeOutputFiles

Data Browser:
DataBrowser

### CODE REVIEW

**Review by mguidon — APPROVED** [review]
Very nice! Now we are just missing filserv.

**Review by sanderegg — APPROVED** [review]
verrry pretty

**Review by ignapas — CHANGES_REQUESTED** [review]
Only some ideas about the design:
* Some separation between the icons (icons that touch each other look weird, specially if the have rounded corners)
* The scrollbars also look strange... now they have a box for the scroller, did you change this? I liked them more without the box. Also the scroller is not centered inside the box, that does not look good.
* If the file name takes more than one line, it is cut
* Make the select box a two toggle buttons Kapture 2021-03-15 at 10 19 56

**Comment by odeimaiz** [comment]
> Only some ideas about the design:
> 
> * Some separation between the icons (icons that touch each other look weird, specially if the have rounded corners)
> * The scrollbars also look strange... now they have a box for the scroller, did you change this? I liked them more without the box. Also the scroller is not centered inside the box, that does not look good.
> * If the file name takes more than one line, it is cut
> * Make the select box a two toggle buttons Kapture 2021-03-15 at 10 19 56

- Done
- I didn't change anything
- Done
- Done

**Pull request merged**
