### PR TITLE
🎨 Frontend: Redesign File Picker in App Mode 

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

As discussed:
- [x] Use accordion like layout to
  - [x] make the "Select New file" options easier to find
  - [x] keep the other options hidden by default
- [x] Make Select File button more prominent
- [x] Provide a "Drop file here" option

Before:
image

After:
After

## Related issue/s

closes https://github.com/ITISFoundation/osparc-issues/issues/1447
closes https://github.com/ITISFoundation/osparc-issues/issues/1444

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
👍

**Review by matusdrobuliak66 — APPROVED** [review]
Beautiful 👍

**Review by sanderegg — APPROVED** [review]
great!

**Review by GitHK — APPROVED** [review]
Thanks for the change! Looks way more intuitive to me

**Review by elisabettai — APPROVED** [review]
Much much better! 
Thee small suggestions:
1. Move up the link option: I think it is used a bit more often than selecting a file from other studies
2. Rename "Select Used File": it doesn't mean much. I'd call it "Select File From Other Project/Study"
3. I'd still keep some kind of explanation as you had before, saying that you have 3 options to upload a file. It doesn't do any harm in my opinion and you have plenty of unused space. In addition, as it is now, it is not obvious for a user who doesn't know anything about this that they only have to do one of the three things. They might think they have to go through all the 3 steps.

**Comment by odeimaiz** [comment]
> Much much better! Thee small suggestions:
> 
> 1. Move up the link option: I think it is used a bit more often than selecting a file from other studies
> 2. Rename "Select Used File": it doesn't mean much. I'd call it "Select File From Other Project/Study"
> 3. I'd still keep some kind of explanation as you had before, saying that you have 3 options to upload a file. It doesn't do any harm in my opinion and you have plenty of unused space. In addition, as it is now, it is not obvious for a user who doesn't know anything about this that they only have to do one of the three things. They might think they have to go through all the 3 steps.

Done, thanks

**Review by ignapas — APPROVED** [review]
👍🏼

**Comment by odeimaiz** [comment]
For the Release Notes

FilePickerRedesign

**Pull request merged**
