### PR TITLE
🎨 Frontend: Update services UX II

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR makes possible to Update a Service or change its Boot mode with the study open.

These options show up on a third tab in the secondary column (not as shown in the animations):
image

Update services:
UpdateServices

Change Boot_mode:
BootMode

## Related issue/s

closes https://github.com/ITISFoundation/osparc-issues/issues/780

### CODE REVIEW

**Review by elisabettai — APPROVED** [review]
Amazing functionality! 🤩 
Some suggestions:
- boot options: I'd prefer to have it only under the "more options" button of the node, instead of adding a third tab to the secondary column
- updating services: I like where it is in the animation (in the output ports tab instead of a third tab).

**Comment by odeimaiz** [comment]
> * boot options: I'd prefer to have it only under the "more options" button of the node, instead of adding a third tab to the secondary column
> * updating services: I like where it is in the animation (in the output ports tab instead of a third tab).

Merci!

Regarding the boot mode, the problem is that you also need to stop it. Since it requires two steps, which are not immediate, I wouldn't have it as a single click menu option.

Regarding the updating services, yes, it might make sense to have it where I had it in the first place: right below the outputs, because you might need to download them first.

The functionality is there, and changing the layout is no effort, let's see what feedback we get tomorrow 👍.

**Comment by odeimaiz** [comment]
> This is pretty cool. 2 cent suggestion with the update button:
> 
> * I would have just the one button and maybe a pop-up dialog that says "your service will be restarted in order to update it", Yes/No?

I agree that it would be nicer to reduce the two steps to one, but I would find the chain of promises in the frontend a bit too long. In that case:
- wait for Stop -> Idle the service
- wait for PUTting the study with the new version
- request Start of the service

**Review by matusdrobuliak66 — APPROVED** [review]

**Comment by elisabettai** [comment]
@odeimaiz, small thing happing when stopping a dynamic service (in Firefox), the leaving page confirmation...

image

**Comment by elisabettai** [comment]
Potential addition for updating services @odeimaiz :
- make that possible also for services that are not deprecated/retired, but have an updated version

**Pull request merged**
