### PR TITLE
✨ Frontend: File Picker: Abort file upload button

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Refactor File Picker
- [x] Implement abort upload

### Bonus:
- [x] Avoid delete confirmation if FP is empty
- [x] Stop file upload if the study gets closed. Requested by @mrnicegyu11 

AbortUpload

## Related issue/s

closes https://github.com/ITISFoundation/osparc-issues/issues/732

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
I like the feature! 
Would it be possible to also add some stop button next to the progress bar of the FilePicker node in the workbench?
A use case: I "daragandarop" three files on the workbench -> three nodes appear -> I want to stop two of them from uploading.

**Comment by odeimaiz** [comment]
> I like the feature! Would it be possible to also add some stop button next to the progress bar of the FilePicker node in the workbench? A use case: I "daragandarop" three files on the workbench -> three nodes appear -> I want to stop two of them from uploading.

Please create a new case for this, I guess you never tried daragandaropping three files on the workbench ;)

**Review by GitHK — APPROVED** [review]
Nice!

**Review by matusdrobuliak66 — APPROVED** [review]

**Comment by elisabettai** [comment]
@odeimaiz, sorry for not checking this before.
Not very critical suggestion: can we add the abort button on the node itself?
image

It took me a bit to realize it was in the secondary column (I did not read the PR to pretend to be an external user). Also, if you click on the workbench you don't see it anymore (which is expected, but doesn't help).

**Comment by pcrespov** [comment]
> @odeimaiz, sorry for not checking this before. Not very critical suggestion: can we add the abort button on the node itself? image
> 
> It took me a bit to realize it was in the secondary column (I did not read the PR to pretend to be an external user). Also, if you click on the workbench you don't see it anymore (which is expected, but doesn't help).

@elisabettai, I already had this discussion a few lines above with @odeimaiz. he proposed to create a new separate issue for this. I did not follow up since I am not a real user and you did not comment on the above. Could you please then create a separate issue for him?

**Comment by mischasabathy** [comment]
Dear All, 

I don't think I should be in this e-mail list. Please remove me from it. 
Thanks 

BR 
Mischa

**Pull request merged**
