### PR TITLE
🐛 [Frontend] Minor fixes: File Picker Reset, Node Editor Close, Selection Management, Button Alignment

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Reset "File Picker" label after resetting file
- [x] Close Node editor after cancel
- [x] Unselect Nodes before moving Annotations and vice versa
- [x] Study info page: align buttons

Reset File Picker
ResetFP

Close Node editor after cancel:
CancelAddNode

Unselect Nodes before moving Annotations and vice versa:
MoveItems

Align buttons:
AlignedButtons

## Related issue/s

closes https://github.com/ITISFoundation/osparc-issues/issues/1585
closes https://github.com/ITISFoundation/osparc-issues/issues/1582
closes https://github.com/ITISFoundation/osparc-issues/issues/1388

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
thx. please rewrite commit title into something more descriptive
e.g. "UI Improvements: File Picker Reset, Node Editor Close, Selection Management, Button Alignment"

**Review by GitHK — APPROVED** [review]

**Review by elisabettai — APPROVED** [review]
Thanks!

Oh, I like the resetting of the name of the file picker. Always thought about that, but somewhat forgot to create an issue. 😉

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by sanderegg — COMMENTED** [review]
great, thanks!

**Review by jsaq007 — APPROVED** [review]
👍🏼

**Pull request merged**
