### PR TITLE
🎨  Adds address+country as required in the request form

### PR DESCRIPTION
**Pull request by pcrespov**
## What do these changes do?

Address info required in request form
image

## Related issue/s

- closes https://z43.fogbugz.com/f/cases/189875/New-feedback-login-page-address

## Dev Checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

## DevOps

none

### CODE REVIEW

**Review by GitHK — APPROVED** [review]
👍

**Review by eofli — APPROVED** [review]
I would still check w/ JcP if we need any other info such as Phone number. Otherwise. OK

**Review by bisgaard-itis — APPROVED** [review]
Looks good to me. Thanks!

**Review by ignapas — APPROVED** [review]
👍🏼

**Pull request merged**
