### PR TITLE
✨ e2e: playwright frontend

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Set up and first round of tests that will mainly test the different products' frontend in master.

The remaining tests will pass one this PR gets merged
image

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by jsaq007 — APPROVED** [review]
👍🏼

**Review by sanderegg — COMMENTED** [review]
waiting for PR readyness ;)

**Review by matusdrobuliak66 — APPROVED** [review]
Cool. So, what's the idea here? I can see that you have 38 tests passed. Do you log in and perform various tests on the UI?

Also, please keep in mind when writing the tests that it would be super useful if we could possibly reuse them to run against our local deployment. In that case, we can set up some of them to run in the merge request.

**Review by sanderegg — APPROVED** [review]
💯

**Review by sanderegg — APPROVED** [review]
are you going to run them in the CI?

**Comment by odeimaiz** [comment]
> are you going to run them in the CI?

Not for now. I first want to work on the tests and, one day, they can be part of the CI

**Pull request merged**
