### PR TITLE
♻️ Is3669/access rights renaming

### LINKED ISSUE #3669: Unify ```accessRights``` and ```access_rights```
Studies/Templates provide the access rights info in the ```accessRights``` metadata, while services provide it under ```access_rights```. Could we, please, move the later to ```accessRights```?

### PR DESCRIPTION
**Pull request by pcrespov**
## What do these changes do?

Ensures field named as ``accessRights`` in **web**-API response bodies.

@odeimaiz does it requires changes in front-end as well? 

### Next steps:

**enforce** that all fields in  **web**-API request/respond bodies should be lower camelcase
   - test automatically all schemas of the web-api
   - add helpers for pydantic models to ensure this

## Related issue/s

- closes #3669 

## How to test

- tests against model examples

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
Ok... yet another pandora...
I kind of get the point, but still I am a bit wondering cause we have a huge mess in this regards... We kind of had a camelCase webAPI initially, then we started having also snake case in there, and I think we do have snake case in the internal APIs...
What is now the rule or idea? when do you want one or the other? What does the api-server do?
Shall we go for complete snake-case, or all webAPI/api-server go camelCase? or a mixture?

**Comment by odeimaiz** [comment]
> @odeimaiz does it requires changes in front-end as well?

It does require changes. Please, let me make them in this PR.

**Comment by odeimaiz** [comment]
@sanderegg The issue here is that studies/templates and services are treated similarly when it comes to access rights. But because of this "inconsistency", there is quite some almost duplicated code in the frontend.

I personally went for camelCase to match the camel casing in the studies/templates metadata.

**Comment by pcrespov** [comment]
> Ok... yet another pandora... I kind of get the point, but still I am a bit wondering cause we have a huge mess in this regards... We kind of had a camelCase webAPI initially, then we started having also snake case in there, and I think we do have snake case in the internal APIs... What is now the rule or idea? when do you want one or the other? What does the api-server do? Shall we go for complete snake-case, or all webAPI/api-server go camelCase? or a mixture?

@sanderegg In the next steps above you can read my proposal. IMO it is simple to deal with this provided we have the right checks in place. I already created a draft that implements the "next steps" section. We can discuss that tomorrow

**Review by odeimaiz — CHANGES_REQUESTED** [review]
Frontend changes required

**Pull request merged**
