### PR TITLE
🐛 FIX: project patch when wallet not shared

### PR DESCRIPTION
**Pull request by matusdrobuliak66**
## What do these changes do?
- 🐛 Removes call to director-v2 which is not needed for patching of project data

## Related issue/s
- fixes https://github.com/ITISFoundation/osparc-simcore/issues/6443

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by odeimaiz — COMMENTED** [review]
👍

**Review by pcrespov — APPROVED** [review]
why was it there then?

**Comment by matusdrobuliak66** [comment]
> why was it there then?

When I was introducing PATCH 5 months ago I thought it was needed.

**Review by sanderegg — APPROVED** [review]
yeah

**Pull request merged**
