### PR TITLE
Make Node outputs more visible

### LINKED ISSUE #1408: Single view of Jupyter Notebooks in osparc
**USER STORY:**

I am an osparc user and use the platform as a way to run my notebooks. 
- I login, 
 - i get to the dashboard, 
 - I see a template study with a logo like 

- I can read nice explanation about its content (e.g. kernels, authors, resources, etc), 
- I click and I get directly into my **ready to use** notebook: 
image
- I do some notebooks and run them
- If i decide to create a more complex workflow, I can click on the top and make my notebook a single node of a more complex pipeline

### Current version

Currently we get into the node view but do not expand the iframe, i.e.
image

I can understand that this would be also an option in some cases. E.g. those node views that have no iframe or those that have inputs; but it is not in the case that I show you above.

I guess we can find some logic such that the views adjust to each case (e.g. only if iframe+no inputs, then expand iframe) . Adding these switches in the preferences might also be an option.

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
- Within the NodeView, this PR makes the Outputs more visible by adding a side panel with the Outputs themselves, similar to the Inputs.
- When collapsing either the Inputs or Outputs, instead of hiding them completely, a very narrow widget is rendered showing the number of connected nodes.

### Bonus:
- Study and Service cards in dashboard show the description in markdown
- upgrade qx-iconfont-fontawesome to 0.2.0
- Auto maximize IFrame if there are no settings to show

Improved collapsed view
Collapsing

Outputs

OneNode

## Related cases
closes #1408 

## Checklist

- [ ] Did you change any service's API? Then make sure to bundle document and upgrade version (``make openapi-specs``, ``git commit ...`` and then ``make version-*``)
- [ ] Unit tests for the changes exist
- [ ] Runs in the swarm
- [ ] Documentation reflects the changes
- [ ] New module? Add your github username to [.github/CODEOWNERS](.github/CODEOWNERS)

### CODE REVIEW

**Comment by sanderegg** [comment]
concerning the collapsing:
the two columns are essentially wasted space. Could we totally remove them an keep the info in the title instead? something like you have:

**Inputs(n)**  name of the service+buttons **Outputs(m)**

Maybe having some kind of smallish arrow on Inputs/Outputs would give a hint.

or a drawer like this one?
Screenshot from 2020-03-26 07-38-04

**Comment by ignapas** [comment]
@odeimaiz this is not yet finished right?

**Comment by odeimaiz** [comment]
> @odeimaiz this is not yet finished right?

I want to clean it up a bit. It will be ready for review tomorrow morning, in the meantime, if you have any requests....

**Comment by odeimaiz** [comment]
> Very good idea!
> 
> concerning the collapsing:
> the two columns are essentially wasted space. Could we totally remove them an keep the info in the title instead? something like you have:
> 
> **Inputs(n)** name of the service+buttons **Outputs(m)**
> 
> Maybe having some kind of smallish arrow on Inputs/Outputs would give a hint.
> 
> or a drawer like this one?
> Screenshot from 2020-03-26 07-38-04

GIF updated ;)

**Comment by ignapas** [comment]
> > Very good idea!
> > concerning the collapsing:
> > the two columns are essentially wasted space. Could we totally remove them an keep the info in the title instead? something like you have:
> > **Inputs(n)** name of the service+buttons **Outputs(m)**
> > Maybe having some kind of smallish arrow on Inputs/Outputs would give a hint.
> > or a drawer like this one?
> > Screenshot from 2020-03-26 07-38-04
> 
> GIF updated ;)

how did you do that? with qooxdoo? what kind of sorcery....

**Comment by sanderegg** [comment]
> > Very good idea!
> > concerning the collapsing:
> > the two columns are essentially wasted space. Could we totally remove them an keep the info in the title instead? something like you have:
> > **Inputs(n)** name of the service+buttons **Outputs(m)**
> > Maybe having some kind of smallish arrow on Inputs/Outputs would give a hint.
> > or a drawer like this one?
> > Screenshot from 2020-03-26 07-38-04
> 
> GIF updated ;)

very nice! and with animation... I can only approve...

**Comment by odeimaiz** [comment]
> AWESOME
> Only I get this error in the console:
> Screenshot from 2020-03-26 16-56-46
> And the new study button icon looks a bit misplaced?
> Screenshot from 2020-03-26 16-57-46

Both fixed 👍

**Comment by ignapas** [comment]
PRed with the one pixel border to distinguish between the two collapsible panels on the right

**Pull request merged**
