### PR TITLE
✨ [Frontend] Connect folders to backend

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR gets rid of the dummy frontend data and connects the folders functionality to the backend.

Still only available in master, until the sharing and other functionalities are implemented. Also, the "Move to folder" folders tree needs some love.

Users can:
- Create folders and subfolders
- List folders, subfolders and studies in there
- Update the name and description
- Delete folders (not sure what the backend does what it's content)
- Move studies to folders

Folders

## Related issue/s

related to https://github.com/ITISFoundation/osparc-issues/issues/716

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
Nice! :) Did you also take the search bar into consideration? Does it behave reasonably?

**Review by pcrespov — COMMENTED** [review]
:eyes:

**Review by elisabettai — APPROVED** [review]
Looks good! 🤩 I didn't have time yet to play with folders on master, but I am happy to do so if useful at this stage.

I like a lot the messages saying clearly that doing x is not supported yet, in my opinion we can potentially release it already like that (if all the rest works properly).

**Review by ignapas — APPROVED** [review]

**Comment by odeimaiz** [comment]
> Nice! :) Did you also take the search bar into consideration? Does it behave reasonably?

That's the only thing it's not yet connected to the backend: filter also folders by text and sort also the folders.

**Comment by odeimaiz** [comment]
> Looks good! 🤩 I didn't have time yet to play with folders on master, but I am happy to do so if useful at this stage.
> 
> I like a lot the messages saying clearly that doing x is not supported yet, in my opinion we can potentially release it already like that (if all the rest works properly).

Not there yet. The frontend doesn't always know if a study is part of a folder or not, and the backend will simply move it without checking it. We need both, the backend and frontend, to be aware of the constraints, and behave accordingly.

Also, when deleting a folder, we need to warn the users of what it's being deleted, potentially listing all the studies that will be deleted...

Without solving these two issues, I wouldn't move it beyond master.

**Review by sanderegg — COMMENTED** [review]
what a day!! nice!

**Pull request merged**
