### PR TITLE
🎨 xmas image

### PR DESCRIPTION
**Pull request by jsaq007**
## What do these changes do?

Add xmas image to login screen for 12 days of xmas
small fix for inconsistency in colors between light and dark mode

## Dev Checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
haha! :)

**Review by mguidon — APPROVED** [review]
Hossa!

**Review by elisabettai — APPROVED** [review]
Brilliant!

**Review by ignapas — COMMENTED** [review]
well well... look who is the code owner... 
image

**Review by sanderegg — APPROVED** [review]
great!

**Review by wvangeit — APPROVED** [review]

**Review by bisgaard-itis — APPROVED** [review]
🎄 🎅🏻

**Review by SCA-ZMT — APPROVED** [review]

**Pull request merged**
