### PR TITLE
🎨 Changes user's phone policies  (🗃️)

### PR DESCRIPTION
**Pull request by pcrespov**
## What do these changes do?

- drops phone's uniqueness constraint (i.e. same phone can be used in different registrations)
- pre-registration phone not copied to user's phone since it is not confirmed. Otherwise an error in the phone number might risk blocking user's authentication 

## Related issue/s

- Feedback by @NielsKuster to drop phone uniqueness
- Feedback by @odeimaiz on phone pre-registraiont

## How to test

Driving tests
- package/postgress-database/tests
- services/web/server/tests/unit

## Dev-ops checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
:+1:

**Review by elisabettai — APPROVED** [review]
Thanks!
I thought it was a good idea to have phone uniqueness, it was a way to implicitly check that users were not trying to register to different products (e.g. `s4l` vs `s4lacad`).

**Comment by pcrespov** [comment]
> Thanks! I thought it was a good idea to have phone uniqueness, it was a way to implicitly check that users were not trying to register to different products (e.g. `s4l` vs `s4lacad`).

@elisabettai please bring the discussion back to the table if you still think this is critical. AFAIK we have informed about the downsides of this decission.

**Comment by odeimaiz** [comment]
Thanks!

**Pull request merged**
