### PR TITLE
✨ Frontend: Preview page: WorkbenchPreview + Thumbnails

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

In order to improve the UX for inspecting a Study without opening it, this PR adds a ``Preview`` page to the Study details tabsView.

For now, in this view, only accessible for the ``osparc`` and ``s4l`` products, a preview of the workbench (suggested by @sanderegg in https://github.com/ITISFoundation/osparc-simcore/pull/4360#pullrequestreview-1480759545) and the service's thumbnails are shown together with the nodes tree.

### Bonus
Data page was also added to the tabsView.

PreviewPage

## Related issue/s

- related to https://github.com/ITISFoundation/osparc-issues/issues/979

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
🎉

**Review by mguidon — APPROVED** [review]
This comes along nicely. Maybe we could unleash the icon lady?

**Comment by SCA-ZMT** [comment]
Looks really cool... so cool in fact, that I would suggest a more standard behavior: the preview shows first when the user clicks on a study, rather than the detailed and verbose (and less intuitive) info with study ID etc.

**Review by sanderegg — COMMENTED** [review]
looking cool! I agree with @SCA-ZMT that maybe defaulting on the preview might be what you wanna see most of the time

**Review by elisabettai — APPROVED** [review]
Very very cool and I agree that this can become "default preview" of a Study.

Is here that we might include some markdown editing function for users, so they can edit what is shown?

**Review by matusdrobuliak66 — APPROVED** [review]
:1st_place_medal:

**Comment by odeimaiz** [comment]
> Very very cool and I agree that this can become "default preview" of a Study.
> 
> Is here that we might include some markdown editing function for users, so they can edit what is shown?

@elisabettai 
Let's show in the RM and decide what to show by default... I personally think that even though it looks nice (and it will look nicer), we you show the boring Info page.

What do you mean by the markdown editing function? That's part the Info page, the Description section. We will now add also the comments section below that: https://github.com/ITISFoundation/osparc-simcore/pull/4386

**Comment by elisabettai** [comment]
> @elisabettai
What do you mean by the markdown editing function? That's part the Info page, the Description section. We will now add also the comments section below that: https://github.com/ITISFoundation/osparc-simcore/pull/4386

Yes, I was thinking about the Info page and that would fulfill most of the features requested in https://github.com/ITISFoundation/osparc-issues/issues/979. 

What are you planning to show next in this `Preview`? I am just afraid that users might not notice the `Preview` and put stuff in the Info page only.

**Pull request merged**
