### PR TITLE
✨ [Frontend] Leave Organization

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Should I stay or should I go?

Let users leave an Organization if they got personal access (not through an another organization).

~~Open~~ Answered questions:
- What should happen right after? Reload all resources (studies, templates, services, wallets...)? It will trigger a reload of the page.
- What if the user leaves an organization while having a study open and has access to that study through the quit organization? Not allowed to leave an Organization while a Study is open.

Bonus:
- [x] Fix no-thumbnail display ("the playwright user cannot open the sleeper service")

LeaveOrganization

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by sanderegg — APPROVED** [review]
thanks!

**Comment by elisabettai** [comment]
Nice. 🕺🏻 

> Open questions:
>     What should happen right after? Reload all resources (studies, templates, services, wallets...)?
Yes, why not? I guess users should see everything up-to-date once the leave an org.
> What if the user leaves an organization while having a study open and has access to that study through the quit organization?
Tricky one. Ideally, if you can perform this check when they request to leave the org, you can throw an error saying that they have to close the study first.

**Review by GitHK — APPROVED** [review]
👍

**Review by jsaq007 — APPROVED** [review]
👍🏼

**Pull request merged**
