### PR TITLE
Fixed cached classifiers

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
Fixes replicated classifiers.

The problem we have is that the current frontend cache is not able to handle classifiers coming from different organizations. This PR fixes this specific issue but it would be nice to extend the caching system.

## Related issue number
closes ITISFoundation/osparc-issues#279

## Checklist

- [ ] Did you change any service's API? Then make sure to bundle document and upgrade version (``make openapi-specs``, ``git commit ...`` and then ``make version-*``)
- [ ] Unit tests for the changes exist
- [ ] Runs in the swarm
- [ ] Documentation reflects the changes
- [ ] New module? Add your github username to [.github/CODEOWNERS](.github/CODEOWNERS)

### CODE REVIEW

**Comment by pcrespov** [comment]
Cannot really see that the title here is actually a field ... Was confusing to find that therte was a field missing

image

**Comment by pcrespov** [comment]
With such a huge tree, we would need some kind of search field at the top
image
Something like github

image

**Comment by odeimaiz** [comment]
> Cannot really see that the title here is actually a field ... Was confusing to find that therte was a field missing
> 
> image

It was also reported by @GitHK. Just created an issue for that:
https://github.com/ITISFoundation/osparc-issues/issues/287

**Review by pcrespov — APPROVED** [review]
The issue was fixed but I think there is more potential to improve the UX
Gave a couple of tips to think about ... but incomplete

**Review by GitHK — APPROVED** [review]
The PR addresses the issue and I can correctly see label permissions now.

**Pull request merged**
