### PR TITLE
✨ [Frontend] Username and Privacy settings

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR exposes
- [x] user's Username
- [x] privacy settings: hide fullname and hide email
- [x] getting ready to support ``username`` for other users

username

## Related issue/s

- follows https://github.com/ITISFoundation/osparc-simcore/pull/6904
- related to https://github.com/ITISFoundation/osparc-issues/issues/1779

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by sanderegg — COMMENTED** [review]
nice!

**Review by pcrespov — APPROVED** [review]
Good for a this round but I think we should need to polish some details. 

Here are some thoughts:
- Capitalize `Username` same as you do with first and last name. 
- When if fails, i have to improve the message and perhaps we can offer alternative usernames that are similar to the one the user enters.
- I would also add more info on what is what (e.g. a small info icon or on hover on each field). Specially for privacy. 
- We also need to elaborate a bit more what are the implications of the privacy settings on the overall sharing etc ...

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by GitHK — COMMENTED** [review]
👍

**Comment by odeimaiz** [comment]
> Good for a this round but I think we should need to polish some details.
> 
> Here are some thoughts:
> 
> * Capitalize `Username` same as you do with first and last name.
> * When if fails, i have to improve the message and perhaps we can offer alternative usernames that are similar to the one the user enters.
> * I would also add more info on what is what (e.g. a small info icon or on hover on each field). Specially for privacy.
> * We also need to elaborate a bit more what are the implications of the privacy settings on the overall sharing etc ...

I capitalized `Username`

**Review by jsaq007 — APPROVED** [review]

**Pull request merged**
