### PR TITLE
🐛 Publishing as Tutorials - PO TESTER and ADMIN

### PR DESCRIPTION
**Pull request by jsaq007**
## What do these changes do?

Fixes the issue where users could publish templates to all users of the product

PRODUCT_OWNER TESTERS AND ADMIN

Screenshot 2023-12-06 at 11 27 52

USER

Screenshot 2023-12-06 at 11 28 31

## Related issue/s

Resolves https://z43.fogbugz.com/f/cases/reply/190171/?ixBugEventEmail=1355244

## Dev Checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
👍

**Review by elisabettai — APPROVED** [review]
Thanks a lot, it looks good.

**Review by ignapas — APPROVED** [review]
I have not tested it myself but looking good

**Review by eofli — APPROVED** [review]
👍

**Pull request merged**
