### PR TITLE
Separate webserver tests to improve CI speed

### PR DESCRIPTION
**Pull request by sanderegg**
## What do these changes do?

- [x] separated webserver unit tests into 11 jobs that shall run below 12 minutes each (added a timeout to that end)
- [x] separated webserver integration tests into 2 jobs that shall run below 20 minutes each
- [x] simplified github workflow file to prevent common errors

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]
:tada: Super!

**Review by GitHK — APPROVED** [review]
👍

**Review by pcrespov — COMMENTED** [review]
@sanderegg Since every test subfolder has a timeout,  does it mean that when new tests overrun this number we need to create another folder and add them there?

**Comment by sanderegg** [comment]
exactly. so the jobs don't go out of hand...

**Pull request merged**
