### PR TITLE
✨ Frontend: Disable Services Auto Start

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR implements the frontend part of https://github.com/ITISFoundation/osparc-simcore/pull/4103.

In order to open/close studies faster, or for inspecting studies, this PR exposes the option for opening studies with the ``disable_service_auto_start`` flag. By default it's set to false.

AutoStart

## Related issue/s

related to https://github.com/ITISFoundation/osparc-issues/issues/916

### CODE REVIEW

**Review by elisabettai — APPROVED** [review]

**Review by sanderegg — COMMENTED** [review]
Amazingly fast. Any option to Ctrl+click to shortcut that?
And also why do we see the errors on opening? let me know if I need to do something more on the backend.

**Comment by odeimaiz** [comment]
> Amazingly fast. Any option to Ctrl+click to shortcut that?

Ctrl+click already enables the multi selection of studies. I think, for now, it's enough with the checkbox. We could maybe place it somewhere more visible, but no hidden keyboard shortcuts.

> And also why do we see the errors on opening? let me know if I need to do something more on the backend.

All good with the backend 👌, just two retired services.

**Review by pcrespov — APPROVED** [review]
👍

**Comment by newton1985** [comment]
Why set to false by default? Also the checkbox is quite buried, so if it's going to be difficult to find, I think the default should be true. But I remember there is an argument against this... remind me?

**Comment by odeimaiz** [comment]
> Why set to false by default? Also the checkbox is quite buried, so if it's going to be difficult to find, I think the default should be true. 

Yes, I agree the option is a bit hidden.

> But I remember there is an argument against this... remind me?

Mono-service studies/projects, app-mode, portal templates... it's better not change the current behavior and let the "power" users test it first 👌

**Pull request merged**
