### PR TITLE
🐛♻️ Billing center: latest fixes

### LINKED ISSUE #5284: UI: Improvements on billing center tables
image

- **Cannot read comment** column! 
   - on hover show entire message?
- Status: button to **filter status** Success/Failed/Pending
- Success in other **color**?
- **Width** of the columns  (e.g. Comments should be larger and invoice should only have space for the icon?
- Fill the **large lower area** in the window with the table?
- Consider adding a **refresh button** in the table to explicitly ask to refresh listing

image

### PR DESCRIPTION
**Pull request by ignapas**
## What do these changes do?
* Comment hover tooltip (transactions table)
* Refresh button to transactions table
* Auto-recharge form does not show up if user has no payment methods
* **Inactivity fix**
* Cancel payment when closing window
* Showing notification if GET paymentMethods fail (b/c ServiceUnavailable, for example)
* Adjusted some column widths
* Wallet items not clickable - share button in menu (Niels' feedback)
* Longer buy credits window to accommodate gateway's form
* Share button
* Edit wallet form labels
* Removed wallet thumbnail
* Duration bug (thanks @matusdrobuliak66 )

## Related issue/s
closes #5284 #5383

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]
Vamosss!

**Review by GitHK — APPROVED** [review]

**Comment by elisabettai** [comment]
I think NK would like, in the credits account
1. A button for sharing the wallet, with this icon: 
image
2. The wording for sharing credits should be changed: instead of "Add Members", something like "Share Credit Account":
image

**Review by jsaq007 — APPROVED** [review]

**Review by elisabettai — APPROVED** [review]

**Review by matusdrobuliak66 — APPROVED** [review]
Thanks a lot for these changes!

**Comment by ignapas** [comment]
> Thanks a lot for these changes!

Thanks for pointing it out. The [previous implementation](https://github.com/ITISFoundation/osparc-simcore/pull/5329/commits/c76f02de4d1c1516030b80f9ba22431d77518aed) was a bit faulty...

**Pull request merged**
