### PR TITLE
✨ [Frontend] Listen to the ``stateInputPorts`` and ``stateOutputPorts`` websocket events

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

The icons next to the node ports are now also handled by the backend. This only works with dynamic v2 services

Socket message ``stateInputPorts`` states:
- DOWNLOAD_STARTED
- DOWNLOAD_FINISHED_SUCCESSFULLY
- DOWNLOAD_WAS_ABORTED
- DOWNLOAD_FINISHED_WITH_ERROR

Socket message ``stateOutputPorts`` states:
- UPLOAD_STARTED
- UPLOAD_FINISHED_SUCCESSFULLY
- UPLOAD_WAS_ABORTED
- UPLOAD_FINISHED_WITH_ERROR

PortStatus

## Related issue/s

- closes https://github.com/ITISFoundation/osparc-issues/issues/1706
- closes https://github.com/ITISFoundation/osparc-issues/issues/1737

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
:ok_hand:

**Review by GitHK — APPROVED** [review]
👍

**Review by ignapas — APPROVED** [review]
once there starts to be an increasing number of updates spontaneously coming from the server, it really helps to keep all that data up to date in a single, detached place. like that it is easily accessible from any part of the app and not only from the component who listens to the socket event. like that you can listen to all socket events from one place, that takes care of updating this centralized store of data, or "state", and then you have your components listening (subscribing to changes) to parts of this store and updating themselves accordingly.
one library that helps doing this that seems widely used and working well is https://mobx.js.org/README.html
I was testing it long time ago with Qooxdoo and seemed to work well, if you are interested, we can take a look together

**Comment by odeimaiz** [comment]
> once there starts to be an increasing number of updates spontaneously coming from the server, it really helps to keep all that data up to date in a single, detached place. like that it is easily accessible from any part of the app and not only from the component who listens to the socket event. like that you can listen to all socket events from one place, that takes care of updating this centralized store of data, or "state", and then you have your components listening (subscribing to changes) to parts of this store and updating themselves accordingly. one library that helps doing this that seems widely used and working well is https://mobx.js.org/README.html I was testing it long time ago with Qooxdoo and seemed to work well, if you are interested, we can take a look together

Merci! I would rather extend our Store or create a Port data model in the Node model than add an external library.

**Pull request merged**
