### PR TITLE
```nodeProgress``` in frontend

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR brings the frontend for https://github.com/ITISFoundation/osparc-simcore/pull/3773.

The node start-up sequence is as follows:
1 - CLUSTER_UP_SCALING
2 - SIDECAR_PULLING
3a -  SERVICE_INPUTS_PULLING
3b -  SERVICE_OUTPUTS_PULLING
3c - SERVICE_STATE_PULLING
4 - SERVICE_IMAGES_PULLING

All these steps have a progress bar that is shown when the frontend gets some step progress. Regarding the up-scaling, since there is no progress, when we are in this step a message saying ```This step can take up to 3 minutes``` is shown.

In the node loading page, below the node state, this is shown: (due to several issues, the messages for the animation were faked)
nodeProgress

## Related issue/s

Show progress. Related to ITISFoundation/osparc-issues#765
closes https://github.com/ITISFoundation/osparc-simcore/issues/3788

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
:+1:

**Review by elisabettai — APPROVED** [review]
Cool! 

You might consider not showing the old messages (the ones that shows up directly below the service thumbnail) or showing a generic one e.g. "Loading you project/study".

**Comment by odeimaiz** [comment]
> You might consider not showing the old messages (the ones that shows up directly below the service thumbnail) or showing a generic one e.g. "Loading you project/study".

I think they are not old, just a different type of state. @sanderegg ?

**Comment by sanderegg** [comment]
> > You might consider not showing the old messages (the ones that shows up directly below the service thumbnail) or showing a generic one e.g. "Loading you project/study".
> 
> I think they are not old, just a kind of a subtask progress. @sanderegg ?

So I am trying to differentiate ```service state``` information from ```task progress```.
a service is ```pending```, ```pulling```, ```starting```, ```stopping``` this is the service state
a service's outputs are ```pushing```/```pulling``` or the service's states are ```pushing```/```pulling``` with a progress.

Of course this is a work in progress and we can discuss whether we should at some point replace one with another.

**Review by sanderegg — APPROVED** [review]

**Pull request merged**
