### PR TITLE
🐛 Frontend: Fix open issue

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

It looks like in the logging stage, because of some buggy signal triggering only reproducible in some browsers, 2 osparc dashboards were created... and none was fully bound to the application's state. This PR brings a fix to that issue and also some redesign and refactoring.

#### Bonus?
- [x] downgrade socket.io back to 4.5.4

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
:+1:

**Review by sanderegg — APPROVED** [review]
🙏

**Review by GitHK — COMMENTED** [review]
👍

**Review by elisabettai — APPROVED** [review]
🤞🏻🤞🏻

**Review by jsaq007 — APPROVED** [review]
Looks good... But I am unable to start a study so unable to test properly

**Pull request merged**
