### PR TITLE
Provide study link in Sharing

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR provides a permanent link to a study.

It doesn't implement sharing capabilities within the link. The user using the link must already have access to it.

StudyLink

## Related issue/s
related to: https://github.com/ITISFoundation/osparc-issues/issues/408

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]
This is the same mechanism as the template studies?

**Comment by odeimaiz** [comment]
> This is the same mechanism as the template studies?

Exactly, the navigation to a study was already in place. One day we could update all these reroutes to something like ```url/#/study/uuid:open```

**Review by KZzizzle — COMMENTED** [review]
this is a SUPER NICE feature! One request: if the study is not shared with someone who uses the link, could they get an error message saying "Study $STUDY_NAME is not shared with you" or something to that effect?

**Review by sanderegg — APPROVED** [review]
great addition!

**Pull request merged**
