### PR TITLE
✨ Tooltip on node links

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

As requested by TeamBlack, tooltips were added to the links when they either go dashed or orange:
LinkTT

### CODE REVIEW

**Review by sanderegg — COMMENTED** [review]
nice addition.

**Review by GitHK — APPROVED** [review]
Very nice:

Suggestion: when the line is `red dashed` maybe have both texts in the tooltips `out of date` and `connection candidate...`.

**Review by colinRawlings — APPROVED** [review]
:+1:

**Comment by elisabettai** [comment]
Looking very good, I'd have some suggestions for the message to make it even more explicit:
- Dashed blue: "Compatible input detected: check node_Y inputs"
- Red: "Inputs have changed, re-run node_Y to bring it up to date". (Is this true?)
- I'd also add a tooltip for the gray arrows, especially the dashed one (which I guess means that that connection will not be taken into account because all the inputs are already full)

**Review by elisabettai — COMMENTED** [review]
Looking very good, I'd have some suggestions for the message to make it even more explicit:

    Dashed blue: "Compatible input detected: check node_Y inputs"
    Red: "Inputs have changed, re-run node_Y to bring it up to date". (Is this true?)
    I'd also add a tooltip for the gray arrows, especially the dashed one (which I guess means that that connection will not be taken into account because all the inputs are already full)

**Pull request merged**
