### PR TITLE
🎨 Enh: Merge secondary column's content

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Having three tab pages in the secondary columns can make their content to be a bit hidden (specially the Service Options: update version, change boot mode, update resource limits). Since most of the space there was unused, this PR brings all the content to the same page.

**Bonus**:
- [x] Do not let users delete nodes while pipeline is running.

Content merged (notice the flexible labels):
SecondaryColumns

Disable main Delete Node buttons:
DeleteNodes

## Related issue/s

fixes https://github.com/ITISFoundation/osparc-simcore/issues/5722
fixes https://github.com/ITISFoundation/osparc-issues/issues/1398

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by sanderegg — APPROVED** [review]
that is very nice!!
maybe you could also align the unit with the text?
image

**Review by elisabettai — APPROVED** [review]
Wow, that's a big change, we're getting rid of the inputs and outputs tab. 🥲 
I like the single tab, it helps a lot finding all the useful information in one single place.

Two small questions/suggestions:
1. The icon of the secondary column shows gears, which is also the icon for comp. nodes and it might be confusing. I'd just delete the tab icons, since we don't have tabs anymore.
2. Does the icon at the left of "Inputs", "Outputs", etc... mean that you can collapse it (and hide long lists of inputs/outputs if you want)? In not, I'd remove it.
image

**Review by pcrespov — APPROVED** [review]
fantastic!

**Comment by elisabettai** [comment]
> When you select the study entry in the tree or the selection is empty, we do show an icon on top. Also, when a file picker is selected it has its own icon. So no icon isn't an option, which icon do you propose?

I see what you mean, but also in those cases, I don't find the icons very useful. I think they're useful if there is more than 1 tabs, so users need a way to "activate" the other tabs and recognize the different functionality. So the advantage I see in removing, is that we would clean a bit the UI from elements that we don't need.

But I also understand if you don't want to get rid of them, maybe that would require a lot of code changes for a small improvement. For the icon, I'd use the "input" (or "output") port one or a double arrow (e.g. [this](https://www.flaticon.com/free-icon/arrow_10413840?term=connection&page=1&position=29&origin=search&related_id=10413840)).

**Review by jsaq007 — APPROVED** [review]
Looks good.

**Pull request merged**
