### PR TITLE
🎨 [Frontend] Highlight workbench elements

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Highlight selected node(s)
- [x] Highlight edge when hovering input port

HighlightWorkbench

## Related issue/s

- closes https://github.com/ITISFoundation/osparc-issues/issues/639
- closes https://github.com/ITISFoundation/osparc-simcore/issues/3066
- closes https://github.com/ITISFoundation/osparc-issues/issues/628

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by sanderegg — COMMENTED** [review]
back to colors?

**Review by jsaq007 — APPROVED** [review]
👍🏼

**Review by pcrespov — COMMENTED** [review]
i like it very much :+1: -)

**Review by GitHK — APPROVED** [review]
nice

**Review by ignapas — APPROVED** [review]
noice

**Pull request merged**
