### PR TITLE
🐛 Fix: Open study from notification

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Bugfix: fix open study when the study details has been open from a notification

OpenFromNotification

## Related issue/s
fixes https://github.com/ITISFoundation/osparc-issues/issues/1281

## Dev Checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by sanderegg — COMMENTED** [review]
:+1:

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by pcrespov — COMMENTED** [review]
:+1:

**Review by GitHK — COMMENTED** [review]
👍

**Review by elisabettai — APPROVED** [review]
Thanks for the quick fix.
I've edited the description to add the related issue so it's closed automatically.

**Review by ignapas — APPROVED** [review]

**Pull request merged**
