### PR TITLE
bugfix: director-v2 is implicitely converting float values to int, preventing kember from running

### PR DESCRIPTION
**Pull request by sanderegg**
## What do these changes do?

Kember tutorial was failing because a wrong value of 0 is passed as deltaT to the kember service

### CODE REVIEW

**Review by KZzizzle — APPROVED** [review]
Amazing, thank you!!

**Review by GitHK — APPROVED** [review]
so annoying when this happens

**Review by pcrespov — COMMENTED** [review]
where are the changes here?

**Review by pcrespov — APPROVED** [review]
AHA! I see it now ... **STRICT**

**Pull request merged**
