### PR TITLE
Web Worker takes care of setting intervals for heartbeat

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
Replace the current (window).timer by a timer run by a WebWorker

## Related issue number
closes https://github.com/ITISFoundation/osparc-simcore/issues/1955
closes https://github.com/ITISFoundation/osparc-issues/issues/375

### CODE REVIEW

**Review by sanderegg — COMMENTED** [review]
I still do not really understand the issue with the project being closed/garbage collector kicking in. is the heartbeat of the windows manager drifting by 15 minutes?

**Review by pcrespov — APPROVED** [review]

**Review by pcrespov — COMMENTED** [review]
Now we are certain osparc will not have "heart arrhythmias"! Great job @odeimaiz !

**Comment by odeimaiz** [comment]
> Now we are certain osparc will not have "heart arrhythmias"! Great job @odeimaiz !

Delegating the heart beat to an external class.... I should rename it to "pacemaker"

**Review by GitHK — COMMENTED** [review]
Very good Odei, the web worker is creating heart beats at regular intervals as expected. 
This works far better. Please also merge my PR into yours so we can close the reported issue.

**Review by GitHK — APPROVED** [review]
👍  this should now fix the reported issue

**Pull request merged**
