### PR TITLE
✨ Ask for a project name when it's created

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Allow users set a name when creating a project.
- [x] Credits Available bar next to the wallet selector was removed, now the number of credits left is part of the text in the Drop Down (element reused in the Billing Center).
- [x] The Tier selection layout goes into a Scroll container. For now, they will stay hidden.

PrjName

## Related issue/s

closes https://z43.fogbugz.com/f/cases/190882/Ask-for-a-project-name-the-first-time-the-project-is-opened

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by elisabettai — APPROVED** [review]
Super-nice, thanks!

Minor 1: I don't see the need of the scrollable container for the instance types, they fit very well in the window as it was before.
Minor 2: the buttons as they were before fit the space on the right better, now the right part of the window is very empty.

image

**Review by sanderegg — APPROVED** [review]
"updated networks in directorv2"???

**Comment by odeimaiz** [comment]
> Minor 1: I don't see the need of the scrollable container for the instance types, they fit very well in the window as it was before. 

It only becomes scrollable if it reaches the maximum height.

> Minor 2: the buttons as they were before fit the space on the right better, now the right part of the window is very empty.

We think that in this case the user will go from top to bottom through the options, that's why we thought of moving them to the bottom-right.

**Review by pcrespov — APPROVED** [review]
Shoulnd the cursor be on then project name when the modal window pops up?

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by GitHK — COMMENTED** [review]
👍

**Review by jsaq007 — APPROVED** [review]
Looks great thanks for the extra effort

**Pull request merged**
