### PR TITLE
🐛Uploading files works again

### PR DESCRIPTION
**Pull request by sanderegg**
## What do these changes do?
Fixes the issue where files could not be uploaded through the frontend anymore.

The issue arose from https://github.com/ITISFoundation/osparc-simcore/pull/4490

### CODE REVIEW

**Review by odeimaiz — APPROVED** [review]
Merci!

**Review by GitHK — APPROVED** [review]
👍

**Review by matusdrobuliak66 — APPROVED** [review]

**Comment by matusdrobuliak66** [comment]
This is one that we will hotfix?

**Comment by sanderegg** [comment]
> This is one that we will hotfix?

yes

**Pull request merged**
