### PR TITLE
✨Expiration Date: FE 2nd iteration

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
- [x] Backend only provides the expiration DAY. Frontend updated accordingly
- [x] If accounts expires in less than 7 days:
  - More human readable Flash Message
  - Show hourglass with tooltip in Navigation bar. Tapping it brings you to the preferences

Expire

## Related issue/s
https://github.com/ITISFoundation/osparc-simcore/pull/3352

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]
great! :tada:

**Review by GitHK — APPROVED** [review]
👍

**Comment by elisabettai** [comment]
Super! What happens if the account has expired? Does it show negative days? (:

**Comment by elisabettai** [comment]
Super! I guess this also solves the negative number days I had yesterday "Your account will expire in -1 day".
Minor suggestion: when the account has expired, I would add the support email in the flash message.

**Comment by odeimaiz** [comment]
> Super! I guess this also solves the negative number days I had yesterday "Your account will expire in -1 day". Minor suggestion: when the account has expired, I would add the support email in the flash message.

Correct, users will never see the negative number because the backend won't let them in.
The support email is already part of the Flash Message and also the tooltips 👌. But, if the log in fails because the account expired, the frontend just shows the error message coming from the backend. Therefore, the support email has to be added in the backend. I can take care of that.

**Pull request merged**
