### PR TITLE
✨ Feature: Payment Gateway in a new window

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

More Wallets related mock up:
- Overview Page: when clicking on the Wallets on the Navigation Bar, the Overview or Summary page is shown.
- Payment Gateway: in order to get closer to the final workflow, open a new window that would point to a URL given by the backend (for now, it point to paypal's sandbox). This window is modal and a blocker is shown on top of our application.
- Preferred Wallet: Let the user select the preferred wallet (shown with a strong star).

Overview Page:
Summary

Preferred Wallet:
Start

Payment Gateway in pop up window:
Window

## Related issue/s

related to https://github.com/ITISFoundation/osparc-issues/issues/1027

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
cool! :1st_place_medal:

**Review by pcrespov — APPROVED** [review]
Looks good. I have two inputs/tips regarding UX

1. what about having colors for wallets and using it in the progress bar. This way it is simpler to identify visually from which wallet your are consuming 
2. In the tables, I think adding titles to the columns would help to understand specially the numbers in the tables.

Thx! Backend soon in the best theaters ;-)

**Review by sanderegg — APPROVED** [review]
nice improvements!

**Comment by odeimaiz** [comment]
> 1. what about having colors for wallets and using it in the progress bar. This way it is simpler to identify visually from which wallet your are consuming from

The colors are used for alerting users about low balance, red <10 credits, yellow <50, and blue if >50

> 2. In the tables, I think adding titles to the columns would help to understand specially the numbers in the tables.

👌

**Pull request merged**
