### PR TITLE
Is288/osparc gui

### PR DESCRIPTION
**Pull request by ignapas**
## What do these changes do?

* Solve some bugs in resizing&positioning views in sidebar.
* Change design of splitpane.
* Some code refactoring, attaching handlers in dedicated function and managing toggle buttons in logger view in a simplified way.

## Related issue number

connects to #288 

## Test it

- Play around with the side bar. Does it look cool? Transitions work? Resize the splitpane. Any suggestions?

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] **Runs in the swarm**
- [ ] If you design a new module, add your user to .github/CODEOWNERS

[waffle.io]:https://waffle.io/marketing-assets/documents/waffleio_cheatsheet_v1.pdf?utm_source=blog&utm_medium=cheatsheet-ctabutton&utm_campaign=cheatsheet

### CODE REVIEW

**Comment by pcrespov** [comment]
@ignapas i like your suggestion on testing it. @oetiker would it be possible to get the new features into something similar to http://www.qooxdoo.org/current/playground so that we could try it online?

**Comment by ignapas** [comment]
> @ignapas i like your new "test it" section. I would also keep and do the checklist btw... Is the new front-end testing useful?
> @oetiker would it be possible to get the new features into something similar to http://www.qooxdoo.org/current/playground so that we could try it online?

Checklist added. Is it to be used by the reviewers? About the front-end testing, I haven't used it yet... I will try to start using them in my next contrib. @oetiker is there a recommended reading for Qooxdoo frontend testing? Thanks

**Comment by oetiker** [comment]
@pcrespov and @ignapas there are two kinds of tests for the frontend:

* unit tests. they are already part of the setup and follow the rules of qooxdoo unit testing
   as described here https://www.qooxdoo.org/devel/pages/development/frame_apps_testrunner.html

* the second kind of tests would be actual end 2 end ui tests ... @cboulanger is working on an event recorder for qooxdoo that will make this kind of testing very simple. see the demo here: https://cboulanger.github.io/eventrecorder/widgetbrowser_recorder/ my plan was/is to add support for the event recorder to our setup as soon as development settles ... which seems to be pretty much the case now, so we might discuss this in the planning today

@pcrespov a version of the playground based on the current qx version is on http://www.qooxdoo.org/qxl.playground/

**Comment by cboulanger** [comment]
@oetiker Great to hear that you're trying out the event recorder. Let me know if you have questions.

**Pull request merged**
