### PR TITLE
Support ContentSchema (array) input/output port type

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR brings a new widget (TextField like) that supports the Content Schema input port type that comes in https://github.com/ITISFoundation/osparc-simcore/pull/2756.

For now, only the ```array``` type is supported

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]
🌶️

**Review by mguidon — APPROVED** [review]
wow

**Review by GitHK — APPROVED** [review]
nice

**Review by KZzizzle — APPROVED** [review]
super!

**Pull request merged**
