### PR TITLE
Update All services with one click

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

UpdateAll

## Related issue/s
closes https://github.com/ITISFoundation/osparc-issues/issues/572

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
love it! thanks for the present!!

**Review by pcrespov — APPROVED** [review]
Great!

THOUGHT:  Still updates the latest patch, right? 

From https://semver.org/
>> Given a version number MAJOR.MINOR.PATCH, increment the:
>> 1. MAJOR version when you make incompatible API changes,
>> 2. MINOR version when you add functionality in a backwards compatible manner, and
>> 3. PATCH version when you make backwards compatible bug fixes.

Should we add an option to select what sort of upgrade as well?  At least for MINOR?

**Comment by odeimaiz** [comment]
> Great!
> 
> THOUGHT: Still updates the latest patch, right?
> 
> From https://semver.org/
> 
> > > Given a version number MAJOR.MINOR.PATCH, increment the:
> > > 
> > > 1. MAJOR version when you make incompatible API changes,
> > > 2. MINOR version when you add functionality in a backwards compatible manner, and
> > > 3. PATCH version when you make backwards compatible bug fixes.
> 
> Should we add an option to select what sort of upgrade as well? At least for MINOR?

Correct, for now, it only applies to Patches.

A Minor upgrade in the service might involve updates in the ports (new port, updates on units....) and this would break connections. I'm not sure you want to go that far.

**Comment by pcrespov** [comment]
> A Minor upgrade in the service might involve updates in the ports (new port, updates on units....) and this would break connections. I'm not sure you want to go that far.

@odeimaiz a minor upgrade should be backwards compatible ( read definitions above)

**Pull request merged**
