### PR TITLE
🎨 [Frontend] Request Account form for oSPARC 🚨

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

If product vendor's information says that ``invitation_form`` and the login configuration says ``invitation_required``, a Request Account form will be displayed (no more ``is_product_billable`` checks for this).

RequestAccount

## Related issue/s

closes https://github.com/ITISFoundation/osparc-issues/issues/1584

## How to test

- set  `"invitation_form": true` in database (see below)
- open product's url
- click invitation
- you should get the form
- repeat with `"invitation_form": false` to obtain either a link (if `invitation_url` is provided) or an email (if not)

## Dev-ops checklist 🚨

- 🗃️  Add `invitation_form: true` in `products.vendor` column of the database. e.g. 
```json
{
    "url": "https://acme.com",
    "license_url": "https://acme.com/license",
    "invitation_form": true,
    "name": "ACME",
    "copyright": "© ACME correcaminos",
    "has_landing_page": false
}
```
                    

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
Thanks!

**Review by pcrespov — APPROVED** [review]
thx!

**Review by elisabettai — APPROVED** [review]
Beautiful, thanks!

**Comment by elisabettai** [comment]
@JavierGOrdonnez, when this reaches production, you might get a json form in the emails that request an osparc account. Just add that to the "Preregistration" tab in the PO Center, or ask @pcrespov for more info. 😉

**Review by giancarloromeo — APPROVED** [review]
👍

**Review by jsaq007 — APPROVED** [review]
I didn't run it in the browser but looks ok. I don't expect big surprises

**Pull request merged**
