### PR TITLE
🎨 [Frontend] Enh Drag&Drop: Drop on Trash

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Enh/glitches in the Drag & Drop
  - [x] Allow dropping Studies and Folders into the Trash
  - [x] Show error messages coming from backend
  - [x] Show warning when moving workspace content

#### Bonus:
- [x] A couple of aesthetic enhancements to the Market in Light theme
- [x] Remove unused Appearance files
- [x] Fix TIP

DropOnTrash

## Related issue/s

- related to https://github.com/ITISFoundation/osparc-issues/issues/716

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
:+1:

**Review by pcrespov — COMMENTED** [review]
Nice.

Since "Move to Trash" is an operation that can be un-done ... perhaps it is a "yellow" button instead of red?

**Review by pcrespov — APPROVED** [review]
Lets check the error messages.

**Review by jsaq007 — APPROVED** [review]

**Review by sanderegg — COMMENTED** [review]
:+1:

**Review by giancarloromeo — APPROVED** [review]

**Comment by odeimaiz** [comment]
> Since "Move to Trash" is an operation that can be un-done ... perhaps it is a "yellow" button instead of red?

@pcrespov Yellow it is:

MoveToTtrash

**Review by GitHK — COMMENTED** [review]
👍

**Review by ignapas — APPROVED** [review]

**Pull request merged**
