### PR TITLE
🎨 ⚗️ Login page animation

### PR DESCRIPTION
**Pull request by jsaq007**
## What do these changes do?

Enhance the login page with a simple animation.

## Dev-ops checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by GitHK — COMMENTED** [review]
👍

**Review by mguidon — APPROVED** [review]
:hot_pepper:

**Review by pcrespov — COMMENTED** [review]
I would like to have an easter egg that once activated, the cloud follows the mouse :-D

**Review by sanderegg — APPROVED** [review]
pretty

**Review by bisgaard-itis — APPROVED** [review]
💅🏻

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by YuryHrytsuk — APPROVED** [review]

**Comment by jsaq007** [comment]
Discussed with Niels and decided not to pursue this further at the moment

**Pull request closed without merging**
