### PR TITLE
✨ FE: Deprecated services

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Show deprecated icon with tooltip on NodeUI:
  - Tooltip on computational nodes: "Please, instantiate an updated version"
  - Tooltip on dynamic nodes: "Please, download the artifacts and upload them to an updated version"
- [x] Dynamic service loading page: stop spinning icon if it Fails/Deprecated
- [x] When a deprecated dynamic service is selected, display outputs page (where the ```Artifacts``` button sits) in secondary panel and show deprecated chip together with de deprecation instructions

Deprecated

## Related issue/s

related to https://github.com/ITISFoundation/osparc-issues/issues/658

### CODE REVIEW

**Review by mrnicegyu11 — APPROVED** [review]
omfg finally i love it! <3

**Review by pcrespov — COMMENTED** [review]
:+1:

**Comment by elisabettai** [comment]
So nice! I really like that the user gets directly to the output where Artifacts can be downloaded.

Since some user complained, could we change "Artifacts" to something more clear, e.g. "Service data"? And, in the instructions, maybe we should clarify what they're going to find. I guess "workspace" and outputs, right?

**Review by GitHK — APPROVED** [review]
Looking really nice! 👍

**Comment by odeimaiz** [comment]
> Since some user complained, could we change "Artifacts" to something more clear, e.g. "Service data"? And, in the instructions, maybe we should clarify what they're going to find. I guess "workspace" and outputs, right?

Not in every deprecated service the workspace zip will be present so I didn't want to go into those details. Maybe we could add something like contact support/service-owner for more details....

Regarding the ```Artifacts``` wording, I don't have a strong opinion...

**Pull request merged**
