### PR TITLE
WIP: 🐛 fixes flaky tests/integration/02/test_dynamic_services_routes.py::test_start_status_stop

### PR DESCRIPTION
**Pull request by GitHK**
## What do these changes do?

Sometimes the code relative to an enum migration (not auto generated by alembic) would fail. 
For details on the migration failing see https://github.com/ITISFoundation/osparc-simcore/actions/runs/3446962667/jobs/5752633533#step:12:253

Instead of adding the filed for the enum and fail if the enum field already exists, this will add the field to enum only if the field does not exist.

## Related issue/s

- fixes https://github.com/ITISFoundation/osparc-simcore/issues/3545

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
Some thoughts: This will definitively avoid the error but I have the feeling it will not be fixing the real cause.

This migration script adds a **new** enumerator called ``ADMIN`` to ``TYPE``. Therefore the question is why ``ADMIN`` is already in there?  IMO a plausible answer would be that some other entity has already run the migration!

**Comment by GitHK** [comment]
> Some thoughts: This will definitively avoid the error but I have the feeling it will not be fixing the real cause.
> 
> This migration script adds a **new** enumerator called `ADMIN` to `TYPE`. Therefore the question is why `ADMIN` is already in there? IMO a plausible answer would be that some other entity has already run the migration!

@pcrespov Had the same exact thought process.

Regarding migrations, I think that the following statements are true:
- the migration which fails is not the first one in the chain (there are others before and others afterwards)
- once the migrations are applied, even if request to apply them again, they get skipped

Other considerations:
- the db migration is applied once per module, so a previous test in the same file could not have caused the issue
- when running the `[int] director-v2 02` tests, the swarm gets created and destroyed multiple times, once per each file in the directory (does not run with `--keep-docker-up` option)

What I think happens:
- I'd say something is not cleaned up thoroughly when the swarm is put down.
- What raised a red flag was `get_alembic_config_from_cache` that could create issues.

Any other ideas?

**Comment by GitHK** [comment]
I think this might also be related: `cached statement plan is invalid due to a database schema or configuration change (SQLAlchemy asyncpg dialect will now invalidate all prepared caches in response to this exception)`. See https://github.com/ITISFoundation/osparc-simcore/actions/runs/3637703641/jobs/6139379723#step:12:564

Someone suggests to toss away "the metadata" form the session https://github.com/sqlalchemy/sqlalchemy/issues/6645

The models should generate their metadata inside this module `simcore_postgres_database.models.base`


## My best guess

When pytest runs it all discovered tests and runs them one after another inside the same interpreter.

- tests discovered in `module_a.py` run which start and destroy Postgres `(ALL OK)`
- tests discovered in `module_b.py` run which start Postgres (these can fail because of caching issues).

There are two flaky tests causing issues "apparently related to caching". Both generate issue because Postgres has been previously started and stopped in the same purest session (using the same python interpreter)

**Review by sanderegg — COMMENTED** [review]
One thing I am wondering is the following, this is an integration test right? so I guess you are depending on the migration service AND some migration fixtures at the same time.

Both are doing the same thing, and the fixture that starts the migration service does not wait for it to finish. Therefore it can happen that both migrations are run in parallel.

Therefore I would try to make sure the migration of the **migration micro-service** is complete before proceeding. I think that lies somewhere in the docker_swarm fixture.

**Pull request closed without merging**
