### PR TITLE
🎨 Only show “credits” col in usage table if wallets

### PR DESCRIPTION
**Pull request by jsaq007**
## What do these changes do?

Only show “credits” column in usage table if wallets/payments are activated in the product

## Related issue/s
- resolves https://github.com/ITISFoundation/osparc-issues/issues/1182

## Dev Checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by GitHK — APPROVED** [review]
👍

**Review by elisabettai — APPROVED** [review]
Thanks a lot!
I took the liberty to modify the description and link the correct issue that it's going to be resolved (the issue is in the other osparc-issues repository). 

Probably you already know, but when an issue is successfully linked, you see it appearing in the "Development" section on the right.

image

**Review by ignapas — APPROVED** [review]
lgtm

**Review by pcrespov — COMMENTED** [review]
Thx. I took the liberty to add `milestone` and `labels` to the issue. It helps us collecting stats on the sprint.

TIP: perhaps it's time to tine a bit the front-end linter or include some pre-commit hooks to avoid these failures on the CI :-)

**Pull request merged**
