### PR TITLE
✨ Changes in auto-recharge limit policy (🗃️, ⚠️)

### PR DESCRIPTION
**Pull request by pcrespov**
## What do these changes do?

Changed auto-recharge limit model from _maximum number of top-ups_ (`top_up_countdown`) to _maximum amount per natural month_ (`monthly_limit_in_usd`). 

The minimum threshold to top-up is also now defined via env var `PAYMENTS_AUTORECHARGE_MIN_BALANCE_IN_USD`, i.e. _at the app level instead of per-user_. This value is also passed to the front-end in `GetWalletAutoRecharge.minBalanceInUsd` as read-only so it can be shown in the help to the user. (@odeimaiz )

These are the new models used in `get_wallet_autorecharge: GET /wallets/{wallets}/ator-recharge` and `update_wallet_autorecharge: PUT /wallets/{wallets}/ator-recharge`
image

More details of [openapi.json](https://editor-next.swagger.io/?https://raw.githubusercontent.com/ITISFoundation/osparc-simcore/86d9c65ca32567e48c0601f671934d042ae98108/services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml) 

### Main Changes
- ✨ `services/webserver api version: 0.35.0 → 0.36.0`
-🗃️ `packages/postgres-database version: 0.10.0 → 0.11.0`

## Related issue/s

- Follows up front-end changes in #4945 
- Implementing autorecharge in #4751

## How to test

Driving tests `services/web/server/tests/unit/with_dbs/03/wallets/payments/test_payments_methods.py`

## DevOps  ⚠️

- **Renamed** `PAYMENTS_AUTORECHARGE_DEFAULT_MIN_BALANCE` -> `PAYMENTS_AUTORECHARGE_MIN_BALANCE_IN_USD`
- **New** `PAYMENTS_AUTORECHARGE_DEFAULT_MONTHLY_LIMIT`
- 🗃️  migration of `payments_autorecharge`

### CODE REVIEW

**Review by YuryHrytsuk — APPROVED** [review]
thanks!

**Review by odeimaiz — APPROVED** [review]

**Review by mrnicegyu11 — APPROVED** [review]
ack on devops changes

**Review by sanderegg — APPROVED** [review]

**Review by matusdrobuliak66 — APPROVED** [review]
thanks :+1:

**Comment by matusdrobuliak66** [comment]
@pcrespov Just a comment the `PAYMENTS_AUTORECHARGE_MIN_BALANCE_IN_USD` is in dollars (but RUT knows only about credits, therefore he needs some Credit threshold (which I guess might be different for different products..) Just saying that we need to think about this corner case. The easiest way from my perspective would be if there is somewhere one credit threshold for example 200 credits that RUT will know about and inform payment service when this is reached.

**Comment by jsaq007** [comment]
:+1:

**Pull request merged**
