### PR TITLE
✨ Form playground

### PR DESCRIPTION
**Pull request by ignapas**
## What do these changes do?

Adds a JSONSchema form generation playground to ``/#/form-sandbox``

Screenshot from 2022-03-02 10-41-59

## How to test

Go to 127.0.0.1:9081/#/form-sandbox and try out the form. It's a very basic one for the moment. Please suggest improvements.
Test that the previous service submission form still works. It looks good on my side, only the call fails on my local deployment:
Screenshot from 2022-03-02 10-50-27

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]
This great to recover/re-enable!
- Could you please check the errors github actions is giving?


To compare, other playground for [json-forms](https://jsonforms.io/)
- https://ulion.github.io/jsonform/playground/
- https://rjsf-team.github.io/react-jsonschema-form/

**Review by pcrespov — COMMENTED** [review]
Please add here how it renders schema samples in PR #2756

**Comment by ignapas** [comment]
> Please add here how it renders schema samples in PR #2756

Screenshot from 2022-03-08 15-12-17

**Review by odeimaiz — APPROVED** [review]
👍

**Pull request merged**
