### PR TITLE
♻️ Maintenance/refactors servicelib

### PR DESCRIPTION
**Pull request by pcrespov**
## What do these changes do?

- adds extra ``aiohttp`` to separate dependencies exclusive to aiohttp-services
- can install and test using minimal installation  (e.g. for fastapi-based services) or w/ aiohttp extra (for aiohttp-based services)

### In detail
- adds extra requirements ``aiohttp`` (affects requirements/* and setup.py)
- moves aiohttp-specific modules inside ``src/servicelib/aiohttp``
- moves aiohttp-specific tests inside ``tests/aiohttp``
- changes in Makefile

## How to test

```cmd
make devenv
source .venv/bin/activate
cd packages/services-library

# installs normally (i.e. no aiohttp extras)
make install-dev
make test-dev

# install with aiohttp extras
make "install-dev[aiohttp]"
make "test[aiohttp]"
```

## Checklist

- [x] CI two tests: with aiohttp extras and without aiohttp extras
- [x] adapt services using servicelib: 
    - aiohttp-based: web-server and storage - install as ``service-library[aiohttp]``
    - fastapi-based: - install as ``service-library``
- [x] increase version of servicelib
- [x] simcore-sdk now only depends on `service-library`
- [ ] run make reqs on all involved dependencies to make sure it works correctly

### CODE REVIEW

**Comment by GitHK** [comment]
@pcrespov while trying to make this PR work, it was not possible to do so.
- `simcore-sdk` depends on `servicelib[aiohttp]` (aiopg_utils)
- `simcore-sdk` will also be present in `dynamic-sidecar` (https://github.com/ITISFoundation/osparc-simcore/pull/2509), but instead of `servicelib[aiohttp]` the service should install `servicelib` (without extra aiohttp dependencies).

I propose closing this PR.

In alternative I'd create a new library called `utilslib` containing general utility functions, to be shared among other packages and services:
- for my future use case there are are 2 functions which need to be shared by `servicelib`, `director-v2`, `simcore-sdk`, `dynamic-sidecar`.
- I would also add a test to avoid check that this new library installs other simcore packages (avoids future issues).

**Comment by GitHK** [comment]
After a discussione with @pcrespov, we decided to break dependency between `simcore-sdk` and `servicelib`.
- will copy functions from the `apiopg_utils`
- `archiving_utils` will go into a separate very small focused library called `archivinglib`.

**Comment by GitHK** [comment]
Think I've managed to address everything.

@pcrespov one more thing does not convince me. In the webserver I did not change anything inside requirements. But I've managed to fix all the tests and to use the "new import paths". I think you mentioned something about the code still being there even after installing servicelib without the aiohttp part. That would explain why it works.

**Comment by pcrespov** [comment]
> Think I've managed to address everything.
> 
> @pcrespov one more thing does not convince me. In the webserver I did not change anything inside requirements. But I've managed to fix all the tests and to use the "new import paths". I think you mentioned something about the code still being there even after installing servicelib without the aiohttp part. That would explain why it works.

@GitHK is there any reason why you add the _aiohttp.in requirements in the webserver? Most of the dependencies in ``servicelib[aiohttp]`` are already included in ``web-server`` installer and the test coverage is not 100%.
I did some refactoring and added it

**Review by GitHK — APPROVED** [review]
👍 I think it looks all good now.

**Review by mguidon — APPROVED** [review]
Cleaning Lady was here...

**Pull request merged**
