### PR TITLE
Workbench improvements: Pan

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Middle mouse button enables panning:
Pan

### CODE REVIEW

**Review by KZzizzle — APPROVED** [review]
DOPE!!!!

**Review by pcrespov — COMMENTED** [review]
:tada:

**Review by sanderegg — APPROVED** [review]
AWESOME!!

**Comment by KZzizzle** [comment]
closes https://github.com/ITISFoundation/osparc-issues/issues/389

**Pull request merged**
