### PR TITLE
Use dedicated thumbnails for ISAN templates

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
- [x] Uses study-thumbnail entry from database
- [x] Expose "thumbnail" field
- [x] Added dummy thumbnails for ISAN templates to this PR

## Related issue number
child of #759

image

Thumbnail_2D_RawGraphs
Thumbnail_3D_Paraview
Thumbnail_CC_0D
Thumbnail_Mattward

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] **Runs in the swarm**
- [ ] If you design a new module, add your user to .github/CODEOWNERS

### CODE REVIEW

**Comment by odeimaiz** [comment]
> But where is the thumbnail path of the ISAN projects updated

Together with the rest of the metadata: in the DB. I'm exposing it in a different branch called study2template

**Comment by odeimaiz** [comment]
> the public wiki or some other public server

Where is the public wiki? Which other public server would you go for?

**Comment by pcrespov** [comment]
> Where is the public wiki? Which other public server would you go for?

You can e.g. even use github's wiki for that. By attaching files (d&d) to the wikie

**Comment by odeimaiz** [comment]
@pcrespov @ignapas OK, for now, and since they will be changed, I added the thumbnails to the PR.

**Pull request merged**
