### PR TITLE
✨ Privacy Policy & EULA

### PR DESCRIPTION
**Pull request by ignapas**
## What do these changes do?
Adds the Privacy Policy & EULA to the request account form, with links to the documents.
image

## Related issue/s

- https://github.com/ITISFoundation/osparc-issues/issues/1030

## How to test

Can it be tested? (send the form)

## Dev Checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by mrnicegyu11 — CHANGES_REQUESTED** [review]
Sorry I am going to be annoying I think I need to double check with what the laywer said and adjust. ill let you know!

**Comment by pcrespov** [comment]
> Sorry I am going to be annoying I think I need to double check with what the laywer said and adjust. ill let you know!

@mrnicegyu11 please add the links https://github.com/ITISFoundation/osparc-issues/issues/1030

**Review by pcrespov — COMMENTED** [review]
See comments above.

**Comment by mrnicegyu11** [comment]
here is the verbatim text that we need to adhere to, for the record:
```
When creating the account, the user is informed that their data will be processed in accordance with the linked privacy policy and that they are authorized to use the web product in accordance with the linked EULA. The user should confirm both by ticking the box before he can create the account. The user must only have the opportunity to take note of the two documents by clicking on the link. However, they do not have to do this. However, they must check the box.
```

**Comment by mrnicegyu11** [comment]
@ignapas I am not sure if "please read" is legally sufficient (I really dont know if it is. How I understood it the EULA is formally a contract, so i guess reading it is not sufficient you have to accept the agreement as well). The wording could be along the lines of what was provided by the legal counsel, which is more long, annoying and boring, but maybe safer. Such as:
"Data will be processed in accordance with the linked privacy policy. Users are authorized to use the web product in accordance with the linked EULA."

Potentially also Nik, our GDPR officer, should decide this

**Comment by ignapas** [comment]
Text has been changed according to the on in [this comment](https://github.com/ITISFoundation/osparc-issues/issues/1030#issuecomment-1966043753). The link for the privacy policy has the `staging.` part stripped out for when the prod website is finally available.

**Review by mrnicegyu11 — APPROVED** [review]
thx 🎉

**Review by jsaq007 — APPROVED** [review]
Looks good to me.

**Pull request merged**
