### PR TITLE
qxapp -> osparc refactor

### PR DESCRIPTION
**Pull request by ignapas**
### Potentially breaking changes

qxapp -> osparc refactor

### How to test
```
make build-devel
make up-devel
```
and/or
```
make build
make up
```
and see that everything works fine

### CODE REVIEW

**Comment by ignapas** [comment]
Screenshot 2019-09-02 at 11 49 22
Finding an error when compiling the application. Cannot figure out how the refactor influences this...

**Comment by ignapas** [comment]
If I create a folder ``qooxdoo``, rename ``qooxdoo.d.ts`` to ``d.ts`` and put it inside, it works... but before the refactor everything works fine :S
Folder looks like this
Screenshot 2019-09-02 at 11 53 17

**Comment by ignapas** [comment]
Tried again after merging the latest changes in master, same result (problem with the theme package)

**Comment by ignapas** [comment]
@oetiker will tackle this on Thursday afternoon

**Comment by oetiker** [comment]
I created a PR to unbreak this https://github.com/ignapas/osparc-simcore/pull/2

**Pull request merged**
