### PR TITLE
✨ App Mode: Run upstream dependencies for dynamic services

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

In the App Mode, if a computational node was connected upstream to a dynamic services, when accessing the dynamic service step the computational one was never executed (because the dynamic one doesn't strictly depend on it).

This PR changes that behavior. from now on, everything upstream will be executed and in the meantime a "Preparing Inputs" dialog will be shown together with the logs of the nodes that are being executed behind the scenes. Also, while the execution is ongoing the iframe will be disabled.

### Bonus:
- [x] Show timestamp in logger

Use case: TI Planning pipeline
While only the ElectrodeSelector and the PostProcessing steps are exposed, there is an optimization step which is not shown to the user but it has to be run when going from the ES to the PP:

PreparingInputs

## Related issue/s
related to https://github.com/ITISFoundation/osparc-issues/issues/622

### CODE REVIEW

**Comment by odeimaiz** [comment]
> just a question, if the user chooses not to run the upstream services, would the iframe still be locked?

Yes, shall I remove the disable part?

**Comment by KZzizzle** [comment]
> 

if the frame is frozen in any case, I would just run the stuff by default (without yet another confirmation) since the user wouldn't be able to interact with that service anyway

**Review by pcrespov — COMMENTED** [review]
👍

**Review by ignapas — APPROVED** [review]
nice gui

**Pull request merged**
