### PR TITLE
🐛 Fixes sudden pylint error in CI

### PR DESCRIPTION
**Pull request by pcrespov**
## What do these changes do?

Recurrent CI error with the python linter:  Since  a few hours, all PR show the following error in the python-linting tests:
```cmd
# pylint version info
pylint 2.12.1
astroid 2.9.0
Python 3.8.12 (default, Oct 18 2021, 14:07:50) 
[GCC 9.3.0]
# Running linter
************* Module conftest
services/api-server/tests/unit/conftest.py:20:0: E0611: No name 'RWApiKeysRepository' in module '_helpers' (no-name-in-module)
services/api-server/tests/unit/conftest.py:20:0: E0611: No name 'RWUsersRepository' in module '_helpers' (no-name-in-module)

------------------------------------
Your code has been rated at 10.00/10

make: *** [Makefile:374: pylint] Error 2
Error: Process completed with exit code 2.
```

- This PR fixes E0611 no-name-in-module
- Created a script that merges all CI ``python-linting`` logs into a single file to easily compare logs from two different CIs
- A first look at the difference between two consecutive CIs still does not show any clear evidence of why this still happens
    -  pip freeze list in both CIs are identicla
    - same tooling
    - micro differences in ``git`` version

image
image

### CODE REVIEW

**Comment by mrnicegyu11** [comment]
This is the changelog from the github-actions-virtual-container [from github organisation] (https://github.com/actions/virtual-environments/commit/e8bd81b2d0c402c745a25d48be05168fc26614af)

**Review by mrnicegyu11 — APPROVED** [review]
Looks good, lets get this in so the deploy-pipeline is not blocked 👯

**Review by sanderegg — APPROVED** [review]
very nice tool!
One thing I do not understand is why you want to remove helpers in general. I find them quite useful to reduce file shear size.

**Comment by pcrespov** [comment]
> very nice tool! One thing I do not understand is why you want to remove helpers in general. I find them quite useful to reduce file shear size.

- In that particular case. the helper was not reused anywhere. 
- Using helpers is a good practice but it turns bad when all helpers are copy&pastes of others and have the same name. 
- Tests do not include ``__init__.py`` which makes importing helpers with the same name unreliable

**Pull request merged**
