### PR TITLE
⬆️ Maintenance week/14

### PR DESCRIPTION
**Pull request by GitHK**
## What do these changes do?

**TO NOTE:**

- removed constraint `attrs` from `service-library`
- ~~removed constraints  `jinja2`, `fsspec` from `dask-sidecar` @sanderegg please give this a look~~
- `datcore-adapter` depens on `pennsieve` who's got a few pinned dependencies casing issues when upgrading. Should we ask for an unpin? @sanderegg 

## 1/2 Changes to libraries (only updated libraries are included)
- #packages before: 125
- #packages after : 103

|#|name|before|after|upgrade| count|
|-|----|------|-----|-------|------|
|   1 | aio-pika                  | 6.8.0, 6.8.2    | 7.1.2      | **MAJOR**  | 2 |
|   2 | aioboto3                  | 9.3.1           | 9.4.0      | *minor*    | 1 |
|   3 | aiobotocore               | 1.4.1, 2.1.0    | 2.1.2,2.2.0 | *minor*    | 2 |
|   4 | aiodebug                  | 1.1.2           | 2.3.0      | **MAJOR**  | 1 |
|   5 | aiohttp-jinja2            | 1.4.2           | 1.5        | *minor*    | 1 |
|   6 | aiohttp-session           | 2.9.0           | 2.11.0     | *minor*    | 1 |
|   7 | aiohttp-swagger           | 1.0.15          | 1.0.16     |            | 2 |
|   8 | aioitertools              | 0.8.0           | 0.10.0     | *minor*    | 2 |
|   9 | aioredlock                | 0.7.1           | 0.7.3      |            | 1 |
|  10 | aioresponses              | 0.7.2           | 0.7.3      |            | 1 |
|  11 | aiormq                    | 3.3.1           | 6.2.3      | **MAJOR**  | 2 |
|  12 | alembic                   | 1.7.4, 1.7.6, 1.7.5 | 1.7.7      |            | 11 |
|  13 | anyio                     | 3.4.0           | 🗑️ removed |  | 1 |
|  14 | argcomplete               | 1.12.3          | 🗑️ removed |  | 1 |
|  15 | astroid                   | 2.9.0, 2.9.3    | 2.11.2     | *minor*    | 15 |
|  16 | async-asgi-testclient     | 1.4.9, 1.4.7    | 1.4.10     |            | 2 |
|  17 | asyncpg                   | 0.23.0          | 0.25.0     | *minor*    | 1 |
|  18 | attrs                     | 21.4.0          | 🗑️ removed |  | 1 |
|  19 | backports-entry-points-selectable | 1.1.1           | 🗑️ removed |  | 3 |
|  20 | black                     | 21.12           | 22.1.0     | **MAJOR**  | 4 |
|  21 | botocore                  | 1.20.106        | 1.24.21    | *minor*    | 1 |
|  22 | certifi                   | 2021.10.8, 2021.5.30 | 2021.10.8  |            | 3 |
|  23 | cffi                      | 1.14.5          | 1.15.0     | *minor*    | 2 |
|  24 | chardet                   | 4.0.0           | 🗑️ removed |  | 1 |
|  25 | charset-normalizer        | 2.0.11          | 2.0.12     |            | 16 |
|  26 | click                     | 8.0.1, 8.0.3    | 8.0.4      |            | 20 |
|  27 | coverage                  | 6.3.1, 6.1.2    | 6.3.2      |            | 16 |
|  28 | cryptography              | 36.0.0, 36.0.1, 3.4.7 | 36.0.2     |            | 10 |
|  29 | dask                      | 2022.1.1        | 2022.3.0   | *minor*    | 1 |
|  30 | datamodel-code-generator  | 0.11.14         | 🗑️ removed |  | 1 |
|  31 | distlib                   | 0.3.3           | 0.3.4      |            | 3 |
|  32 | distributed               | 2022.1.1        | 2022.3.0   | *minor*    | 1 |
|  33 | distro                    | 1.6.0           | 1.7.0      | *minor*    | 6 |
|  34 | dnspython                 | 2.1.0, 2.2.0    | 2.2.1      |            | 9 |
|  35 | email-validator           | 1.1.3           | 🗑️ removed |  | 1 |
|  36 | faker                     | 12.1.0, 13.3.0, 12.3.0, 9.8.3 | 13.3.3     |            | 14 |
|  37 | fastapi                   | 0.73.0, 0.74.1  | 0.75.0     | *minor*    | 2 |
|  38 | filelock                  | 3.4.2, 3.4.0    | 3.6.0      | *minor*    | 16 |
|  39 | fsspec                    | 2022.1.0        | 2022.2.0   | *minor*    | 1 |
|  40 | genson                    | 1.2.2           | 🗑️ removed |  | 1 |
|  41 | h11                       | 0.12.0          | 🗑️ removed |  | 1 |
|  42 | httpcore                  | 0.14.3          | 🗑️ removed |  | 1 |
|  43 | httpx                     | 0.21.3          | 🗑️ removed |  | 1 |
|  44 | hypothesis                | 6.39.3          | 6.39.6     |            | 1 |
|  45 | identify                  | 2.4.3, 2.4.9, 2.4.0, 2.4.10, 2.4.11 | 2.4.12     |            | 17 |
|  46 | idna                      | 2.10            | 3.3        | **MAJOR**  | 23 |
|  47 | importlib-metadata        | 4.11.2, 4.10.1, 4.10.0, 4.8.1 | 4.11.3     |            | 11 |
|  48 | importlib-resources       | 5.3.0, 5.4.0    | 5.6.0      | *minor*    | 15 |
|  49 | inflect                   | 5.3.0           | 🗑️ removed |  | 1 |
|  50 | isodate                   | 0.6.1, 0.6.0    | 0.6.1      |            | 3 |
|  51 | itsdangerous              | 2.1.0           | 2.1.2      |            | 1 |
|  52 | jinja2                    | 3.0.3, 2.11.3   | 3.1.1      | *minor*    | 6 |
|  53 | jmespath                  | 0.10.0          | 1.0.0      | **MAJOR**  | 1 |
|  54 | jsondiff                  | 1.3.0           | 1.3.1      |            | 1 |
|  55 | jsonschema                | 4.4.0, 3.2.0    | 4.4.0      |            | 3 |
|  56 | lazy-object-proxy         | 1.6.0           | 1.7.1      | *minor*    | 1 |
|  57 | mako                      | 1.1.5, 1.1.6    | 1.2.0      | *minor*    | 11 |
|  58 | markupsafe                | 1.1.1, 2.0.1, 2.1.0 | 2.1.1      |            | 14 |
|  59 | mccabe                    | 0.6.1           | 0.7.0      | *minor*    | 15 |
|  60 | multidict                 | 5.1.0           | 6.0.2      | **MAJOR**  | 4 |
|  61 | mypy                      | 0.931           | 0.942      | *minor*    | 1 |
|  62 | numpy                     | 1.21.4          | 1.22.3     | *minor*    | 2 |
|  63 | openapi-schema-validator  | 0.1.6, 0.1.5    | 0.2.3      | *minor*    | 4 |
|  64 | openapi-spec-validator    | 0.3.1           | 0.4.0      | *minor*    | 4 |
|  65 | openpyxl                  | 3.0.7           | 3.0.9      |            | 1 |
|  66 | orjson                    | 3.5.3           | 3.6.7      | *minor*    | 1 |
|  67 | pamqp                     | 2.3.0           | 3.1.0      | **MAJOR**  | 2 |
|  68 | pandas                    | 1.3.4           | 1.4.1      | *minor*    | 1 |
|  69 | paramiko                  | 2.9.2, 2.8.0    | 2.10.3     | *minor*    | 7 |
|  70 | platformdirs              | 2.4.0, 2.5.0    | 2.5.1      |            | 29 |
|  71 | prance                    | 0.21.8.0        | 🗑️ removed |  | 1 |
|  72 | pre-commit                | 2.15.0, 2.16.0  | 2.17.0     | *minor*    | 4 |
|  73 | prometheus-client         | 0.12.0, 0.11.0  | 0.13.1     | *minor*    | 2 |
|  74 | psycopg2-binary           | 2.9.1           | 2.9.3      |            | 3 |
|  75 | pycparser                 | 2.20            | 2.21       | *minor*    | 2 |
|  76 | pydantic                  | 1.9.0           | 🗑️ removed |  | 1 |
|  77 | pylint                    | 2.12.1, 2.12.2  | 2.13.2     | *minor*    | 15 |
|  78 | pynacl                    | 1.4.0           | 1.5.0      | *minor*    | 3 |
|  79 | pyparsing                 | 3.0.6           | 3.0.7      |            | 1 |
|  80 | pyrsistent                | 0.18.1, 0.18.0  | 0.18.1     |            | 5 |
|  81 | pysnooper                 | 0.5.0           | 🗑️ removed |  | 1 |
|  82 | pytest                    | 7.0.1, 7.0.0, 6.2.5 | 7.1.1      | *minor*    | 20 |
|  83 | pytest-asyncio            | 0.18.1, 0.18.0  | 0.18.3     |            | 17 |
|  84 | pytest-docker             | 0.10.3          | 0.11.0     | *minor*    | 7 |
|  85 | pytest-forked             | 1.3.0           | 1.4.0      | *minor*    | 1 |
|  86 | pytest-mock               | 3.6.1           | 3.7.0      | *minor*    | 3 |
|  87 | pytest-runner             | 5.3.1           | 6.0.0      | **MAJOR**  | 14 |
|  88 | pytest-xdist              | 2.4.0           | 2.5.0      | *minor*    | 1 |
|  89 | python-dotenv             | 0.19.2          | 0.20.0     | *minor*    | 10 |
|  90 | python-magic              | 0.4.24          | 0.4.25     |            | 1 |
|  91 | pytz                      | 2021.3          | 2022.1     | **MAJOR**  | 1 |
|  92 | pyyaml                    | 5.4.1           | 6.0        | **MAJOR**  | 2 |
|  93 | redis                     | 3.5.3           | 4.2.0      | **MAJOR**  | 1 |
|  94 | regex                     | 2021.11.10      | 🗑️ removed |  | 1 |
|  95 | requests                  | 2.27.1, 2.26.0  | 2.27.1     |            | 3 |
|  96 | respx                     | 0.19.1          | 0.19.2     |            | 1 |
|  97 | rfc3986                   | 1.5.0           | 🗑️ removed |  | 1 |
|  98 | ruamel-yaml               | 0.17.17         | 🗑️ removed |  | 1 |
|  99 | ruamel-yaml-clib          | 0.2.6           | 🗑️ removed |  | 1 |
| 100 | s3transfer                | 0.5.0           | 0.5.2      |            | 1 |
| 101 | semantic-version          | 2.8.5           | 2.9.0      | *minor*    | 2 |
| 102 | semver                    | 2.13.0          | 🗑️ removed |  | 1 |
| 103 | six                       | 1.16.0          | 🗑️ removed |  | 1 |
| 104 | sniffio                   | 1.2.0           | 🗑️ removed |  | 1 |
| 105 | sqlalchemy                | 1.4.31          | 1.4.32     |            | 13 |
| 106 | text-unidecode            | 1.3             | 🗑️ removed |  | 3 |
| 107 | toml                      | 0.10.2          | 🗑️ removed |  | 14 |
| 108 | tomli                     | 1.2.2, 1.2.3    | 2.0.1      | **MAJOR**  | 37 |
| 109 | tqdm                      | 4.61.1, 4.63.0, 4.62.3 | 4.63.1     |            | 4 |
| 110 | types-aiofiles            | 0.8.3           | 0.8.5      |            | 1 |
| 111 | types-pyyaml              | 6.0.4           | 6.0.5      |            | 1 |
| 112 | typing-extensions         | 4.0.1, 3.10.0.2 | 4.1.1      | *minor*    | 34 |
| 113 | ujson                     | 4.0.2           | 5.1.0      | **MAJOR**  | 2 |
| 114 | urllib3                   | 1.26.7, 1.26.8  | 1.26.9     |            | 18 |
| 115 | virtualenv                | 20.13.0, 20.13.2, 20.10.0, 20.13.1 | 20.14.0    | *minor*    | 17 |
| 116 | watchdog                  | 2.1.6           | 2.1.7      |            | 7 |
| 117 | watchgod                  | 0.7             | 0.8.1      | *minor*    | 1 |
| 118 | websocket-client          | 1.2.3           | 1.3.1      | *minor*    | 3 |
| 119 | websockets                | 10.1            | 10.2       | *minor*    | 1 |
| 120 | werkzeug                  | 2.0.1, 2.0.2    | 2.0.3      |            | 2 |
| 121 | wheel                     | 0.37.0          | 0.37.1     |            | 3 |
| 122 | wrapt                     | 1.13.3, 1.12.1  | 1.14.0     | *minor*    | 15 |
| 123 | yarl                      | 1.5.1           | 1.7.2      | *minor*    | 2 |
| 124 | zict                      | 2.0.0           | 2.1.0      | *minor*    | 1 |
| 125 | zipp                      | 3.7.0, 3.6.0    | 3.7.0      |            | 2 |
## 2/2 Repo wide overview of libraries
- #reqs files parsed: 57

|#|name|versions-base|versions-test|versions-tool|
|-|----|-------------|-------------|-------------|
|   1 | aio-pika                  | 7.1.2                     | 7.1.2                     |                           |
|   2 | aioboto3                  |                           | 9.5.0                     |                           |
|   3 | aiobotocore               | 2.2.0                     | 2.2.0                     |                           |
|   4 | aiocache                  | 0.11.1                    |                           |                           |
|   5 | aiodebug                  | 2.3.0                     | 2.3.0                     |                           |
|   6 | aiodocker                 | 0.21.0                    | 0.21.0                    |                           |
|   7 | aiofiles                  | 0.8.0                     | 0.8.0                     |                           |
|   8 | aiohttp                   | 3.8.1                     | 3.8.1                     |                           |
|   9 | aiohttp-jinja2            | 1.5                       |                           |                           |
|  10 | aiohttp-security          | 0.4.0                     |                           |                           |
|  11 | aiohttp-session           | 2.11.0                    |                           |                           |
|  12 | aiohttp-swagger           | 1.0.16                    |                           |                           |
|  13 | aioitertools              | 0.10.0                    | 0.10.0                    |                           |
|  14 | aiopg                     | 1.3.3                     | 1.3.3                     |                           |
|  15 | aioredis                  | 2.0.1                     |                           |                           |
|  16 | aioresponses              |                           | 0.7.3                     |                           |
|  17 | aiormq                    | 6.2.3                     | 6.2.3                     |                           |
|  18 | aiosignal                 | 1.2.0                     | 1.2.0                     |                           |
|  19 | aiosmtplib                | 1.1.6                     |                           |                           |
|  20 | aiozipkin                 | 1.1.1                     |                           |                           |
|  21 | alembic                   | 1.7.7                     | 1.7.7                     |                           |
|  22 | anyio                     | 3.5.0                     | 3.5.0                     |                           |
|  23 | argon2-cffi               | 21.3.0                    |                           |                           |
|  24 | argon2-cffi-bindings      | 21.2.0                    |                           |                           |
|  25 | asgi-lifespan             |                           | 1.0.1                     |                           |
|  26 | asgiref                   | 3.5.0                     |                           |                           |
|  27 | astroid                   |                           | 2.11.2                    | 2.11.2                    |
|  28 | async-asgi-testclient     |                           | 1.4.10                    |                           |
|  29 | async-generator           | 1.10                      |                           |                           |
|  30 | async-timeout             | 4.0.2                     | 4.0.2                     |                           |
|  31 | asyncpg                   | 0.25.0                    |                           |                           |
|  32 | attrs                     | 21.4.0                    | 21.4.0                    |                           |
|  33 | bcrypt                    | 3.2.0                     | 3.2.0                     |                           |
|  34 | beautifulsoup4            | 4.11.1                    |                           |                           |
|  35 | black                     |                           |                           | 22.3.0                    |
|  36 | bleach                    | 5.0.0                     |                           |                           |
|  37 | blosc                     | 1.10.6                    |                           |                           |
|  38 | bokeh                     | 2.4.2                     | 2.4.2                     |                           |
|  39 | boto3                     | 1.21.33                   | 1.21.21                   |                           |
|  40 | botocore                  | 1.24.21, 1.24.33          | 1.24.21                   |                           |
|  41 | bump2version              |                           |                           | 1.0.1                     |
|  42 | certifi                   | 2021.10.8                 | 2021.10.8                 |                           |
|  43 | cffi                      | 1.15.0                    | 1.15.0                    |                           |
|  44 | cfgv                      |                           |                           | 3.3.1                     |
|  45 | change-case               | 0.5.2                     |                           | 0.5.2                     |
|  46 | charset-normalizer        | 2.0.12                    | 2.0.12                    |                           |
|  47 | click                     | 8.1.2                     | 8.1.2                     | 8.1.2                     |
|  48 | cloudpickle               | 2.0.0                     |                           |                           |
|  49 | codecov                   |                           | 2.1.12                    |                           |
|  50 | colorlog                  |                           | 6.6.0                     |                           |
|  51 | configparser              | 5.2.0                     |                           |                           |
|  52 | coverage                  |                           | 6.3.2                     |                           |
|  53 | coveralls                 |                           | 3.3.1                     |                           |
|  54 | cryptography              | 36.0.2                    | 36.0.2                    |                           |
|  55 | cytoolz                   | 0.11.2                    |                           |                           |
|  56 | dask                      | 2022.4.0                  |                           |                           |
|  57 | dask-gateway              | 0.9.0                     |                           |                           |
|  58 | dask-gateway-server       |                           | 0.9.0                     |                           |
|  59 | defusedxml                | 0.7.1                     |                           |                           |
|  60 | deprecated                | 1.2.13                    | 1.2.13                    |                           |
|  61 | dill                      |                           | 0.3.4                     | 0.3.4                     |
|  62 | distlib                   |                           |                           | 0.3.4                     |
|  63 | distributed               | 2022.4.0                  |                           |                           |
|  64 | distro                    | 1.7.0                     | 1.7.0                     |                           |
|  65 | dnspython                 | 2.2.1                     | 2.2.1                     |                           |
|  66 | docker                    | 5.0.3                     | 5.0.3                     |                           |
|  67 | docker-compose            | 1.29.1                    | 1.29.1                    |                           |
|  68 | dockerpty                 | 0.4.1                     | 0.4.1                     |                           |
|  69 | docopt                    | 0.6.2                     | 0.6.2                     |                           |
|  70 | ecdsa                     | 0.14.1                    |                           |                           |
|  71 | email-validator           | 1.1.3                     | 1.1.3                     |                           |
|  72 | entrypoints               | 0.4                       |                           |                           |
|  73 | et-xmlfile                | 1.1.0                     |                           |                           |
|  74 | execnet                   |                           | 1.9.0                     |                           |
|  75 | expiringdict              | 1.2.1                     |                           |                           |
|  76 | faker                     |                           | 13.3.4                    |                           |
|  77 | fastapi                   | 0.75.1                    |                           |                           |
|  78 | fastapi-contrib           | 0.2.11                    |                           |                           |
|  79 | fastapi-pagination        | 0.9.1                     |                           |                           |
|  80 | fastjsonschema            | 2.15.3                    |                           |                           |
|  81 | filelock                  |                           |                           | 3.6.0                     |
|  82 | flaky                     |                           | 3.7.0                     |                           |
|  83 | frozenlist                | 1.3.0                     | 1.3.0                     |                           |
|  84 | fsspec                    | 2022.3.0                  |                           |                           |
|  85 | future                    | 0.18.2                    |                           |                           |
|  86 | futures                   | 3.0.5                     |                           |                           |
|  87 | greenlet                  | 1.1.2                     | 1.1.2                     |                           |
|  88 | gunicorn                  | 20.1.0                    |                           |                           |
|  89 | h11                       | 0.12.0                    | 0.12.0                    |                           |
|  90 | h2                        | 4.1.0                     |                           |                           |
|  91 | heapdict                  | 1.0.1                     |                           |                           |
|  92 | hpack                     | 4.0.0                     |                           |                           |
|  93 | httpcore                  | 0.14.7                    | 0.14.7                    |                           |
|  94 | httptools                 | 0.2.0, 0.4.0              |                           |                           |
|  95 | httpx                     | 0.22.0                    | 0.22.0                    |                           |
|  96 | hyperframe                | 6.0.1                     |                           |                           |
|  97 | hypothesis                |                           | 6.43.0                    |                           |
|  98 | icdiff                    |                           | 2.0.5                     |                           |
|  99 | identify                  |                           |                           | 2.4.12                    |
| 100 | idna                      | 3.3                       | 3.3                       |                           |
| 101 | iniconfig                 | 1.1.1                     | 1.1.1                     |                           |
| 102 | inotify                   |                           |                           | 0.2.10                    |
| 103 | isodate                   | 0.6.1                     |                           |                           |
| 104 | isort                     |                           | 5.10.1                    | 5.10.1                    |
| 105 | itsdangerous              | 2.1.2                     |                           |                           |
| 106 | jaeger-client             | 4.8.0                     |                           |                           |
| 107 | jinja-app-loader          | 1.0.2                     |                           |                           |
| 108 | jinja2                    | 3.1.1                     | 3.1.1                     | 3.1.1                     |
| 109 | jmespath                  | 1.0.0                     | 1.0.0                     |                           |
| 110 | json2html                 | 1.3.0                     |                           |                           |
| 111 | jsondiff                  | 2.0.0                     |                           |                           |
| 112 | jsonschema                | 3.2.0, 4.4.0              | 3.2.0, 4.4.0              |                           |
| 113 | jupyter-client            | 7.2.2                     |                           |                           |
| 114 | jupyter-core              | 4.9.2                     |                           |                           |
| 115 | jupyter-server            | 1.16.0                    |                           |                           |
| 116 | jupyter-server-proxy      | 3.2.1                     |                           |                           |
| 117 | jupyterlab-pygments       | 0.2.1                     |                           |                           |
| 118 | lazy-object-proxy         | 1.4.3                     | 1.4.3, 1.7.1              | 1.7.1                     |
| 119 | locket                    | 0.2.1                     |                           |                           |
| 120 | lz4                       | 4.0.0                     |                           |                           |
| 121 | mako                      | 1.2.0                     | 1.2.0                     |                           |
| 122 | markupsafe                | 2.1.1                     | 2.1.1                     | 2.1.1                     |
| 123 | mccabe                    |                           | 0.7.0                     | 0.7.0                     |
| 124 | minio                     | 7.0.4                     | 7.0.4                     |                           |
| 125 | mistune                   | 0.8.4                     |                           |                           |
| 126 | msgpack                   | 1.0.3                     |                           |                           |
| 127 | multidict                 | 6.0.2                     | 6.0.2                     |                           |
| 128 | mypy                      |                           |                           | 0.942                     |
| 129 | mypy-extensions           |                           |                           | 0.4.3                     |
| 130 | nbclient                  | 0.6.0                     |                           |                           |
| 131 | nbconvert                 | 6.5.0                     |                           |                           |
| 132 | nbformat                  | 5.3.0                     |                           |                           |
| 133 | nest-asyncio              | 1.5.5                     |                           |                           |
| 134 | networkx                  | 2.8                       |                           |                           |
| 135 | nodeenv                   |                           |                           | 1.6.0                     |
| 136 | nose                      |                           |                           | 1.3.7                     |
| 137 | numpy                     | 1.22.3                    | 1.22.3                    |                           |
| 138 | openapi-core              | 0.12.0                    |                           |                           |
| 139 | openapi-schema-validator  | 0.2.3                     | 0.2.3                     |                           |
| 140 | openapi-spec-validator    | 0.4.0                     | 0.4.0                     |                           |
| 141 | openpyxl                  | 3.0.9                     |                           |                           |
| 142 | opentracing               | 2.4.0                     |                           |                           |
| 143 | orjson                    | 3.6.7                     |                           |                           |
| 144 | packaging                 | 21.3                      | 21.3                      |                           |
| 145 | pamqp                     | 3.1.0                     | 3.1.0                     |                           |
| 146 | pandas                    | 1.4.2                     | 1.4.2                     |                           |
| 147 | pandocfilters             | 1.5.0                     |                           |                           |
| 148 | paramiko                  | 2.10.3                    | 2.10.3                    |                           |
| 149 | parfive                   | 1.5.1                     |                           |                           |
| 150 | partd                     | 1.2.0                     |                           |                           |
| 151 | passlib                   | 1.7.4                     | 1.7.4                     |                           |
| 152 | pathspec                  |                           |                           | 0.9.0                     |
| 153 | pennsieve                 | 6.1.2                     |                           |                           |
| 154 | pep517                    |                           |                           | 0.12.0                    |
| 155 | pillow                    | 9.1.0                     | 9.1.0                     |                           |
| 156 | pint                      | 0.19.1                    | 0.19.1                    |                           |
| 157 | pip-tools                 |                           |                           | 6.6.0                     |
| 158 | platformdirs              |                           | 2.5.1                     | 2.5.1                     |
| 159 | pluggy                    | 1.0.0                     | 1.0.0                     |                           |
| 160 | pprintpp                  |                           | 0.4.0                     |                           |
| 161 | pre-commit                |                           |                           | 2.18.1                    |
| 162 | prometheus-client         | 0.14.1                    |                           |                           |
| 163 | protobuf                  | 3.20.0                    |                           |                           |
| 164 | psutil                    | 5.9.0                     |                           |                           |
| 165 | psycopg2-binary           | 2.9.3                     | 2.9.3                     |                           |
| 166 | ptvsd                     |                           | 4.3.2                     | 4.3.2                     |
| 167 | ptyprocess                | 0.7.0                     |                           |                           |
| 168 | py                        | 1.11.0                    | 1.11.0                    |                           |
| 169 | py-cpuinfo                |                           | 8.0.0                     |                           |
| 170 | pyasn1                    | 0.4.8                     |                           |                           |
| 171 | pycparser                 | 2.21                      | 2.21                      |                           |
| 172 | pydantic                  | 1.9.0                     | 1.9.0                     |                           |
| 173 | pyftpdlib                 |                           | 1.5.6                     |                           |
| 174 | pygments                  | 2.11.2                    |                           |                           |
| 175 | pyinstrument              | 3.4.2, 4.1.1              | 4.1.1                     |                           |
| 176 | pyinstrument-cext         | 0.2.4                     |                           |                           |
| 177 | pylint                    |                           | 2.13.5                    | 2.13.5                    |
| 178 | pynacl                    | 1.5.0                     | 1.5.0                     |                           |
| 179 | pyopenssl                 |                           | 22.0.0                    |                           |
| 180 | pyparsing                 | 3.0.8                     | 3.0.8                     |                           |
| 181 | pyrsistent                | 0.18.1                    | 0.18.1                    |                           |
| 182 | pytest                    | 7.1.1                     | 7.1.1                     |                           |
| 183 | pytest-aiohttp            |                           | 1.0.4                     |                           |
| 184 | pytest-asyncio            |                           | 0.18.3                    |                           |
| 185 | pytest-benchmark          |                           | 3.4.1                     |                           |
| 186 | pytest-cov                |                           | 3.0.0                     |                           |
| 187 | pytest-docker             |                           | 0.12.0                    |                           |
| 188 | pytest-forked             |                           | 1.4.0                     |                           |
| 189 | pytest-icdiff             |                           | 0.5                       |                           |
| 190 | pytest-instafail          |                           | 0.4.2                     |                           |
| 191 | pytest-lazy-fixture       |                           | 0.6.3                     |                           |
| 192 | pytest-localftpserver     |                           | 1.1.3                     |                           |
| 193 | pytest-mock               |                           | 3.7.0                     |                           |
| 194 | pytest-runner             |                           | 6.0.0                     |                           |
| 195 | pytest-sugar              |                           | 0.9.4                     |                           |
| 196 | pytest-xdist              |                           | 2.5.0                     |                           |
| 197 | python-dateutil           | 2.8.2                     | 2.8.2                     |                           |
| 198 | python-dotenv             | 0.20.0                    | 0.20.0                    |                           |
| 199 | python-engineio           | 3.14.2                    |                           |                           |
| 200 | python-jose               | 3.2.0                     |                           |                           |
| 201 | python-magic              | 0.4.25                    |                           |                           |
| 202 | python-multipart          | 0.0.5                     |                           |                           |
| 203 | python-socketio           | 4.6.1                     |                           |                           |
| 204 | pytz                      | 2022.1                    | 2022.1                    |                           |
| 205 | pyyaml                    | 5.4.1, 6.0                | 5.4.1, 6.0                | 5.4.1, 6.0                |
| 206 | pyzmq                     | 22.3.0                    |                           |                           |
| 207 | redis                     | 4.2.2                     | 4.2.2                     |                           |
| 208 | requests                  | 2.27.1                    | 2.27.1                    |                           |
| 209 | respx                     |                           | 0.19.2                    |                           |
| 210 | rfc3986                   | 1.5.0                     | 1.5.0                     |                           |
| 211 | rsa                       | 4.0                       |                           |                           |
| 212 | s3transfer                | 0.5.2                     | 0.5.2                     |                           |
| 213 | semantic-version          | 2.9.0                     |                           |                           |
| 214 | semver                    | 2.13.0                    |                           |                           |
| 215 | send2trash                | 1.8.0                     |                           |                           |
| 216 | setproctitle              | 1.2.2                     |                           |                           |
| 217 | simpervisor               | 0.4                       |                           |                           |
| 218 | six                       | 1.16.0                    | 1.16.0                    | 1.16.0                    |
| 219 | sniffio                   | 1.2.0                     | 1.2.0                     |                           |
| 220 | sortedcontainers          | 2.4.0                     | 2.4.0                     |                           |
| 221 | soupsieve                 | 2.3.2                     |                           |                           |
| 222 | sqlalchemy                | 1.4.35                    | 1.4.35                    |                           |
| 223 | starlette                 | 0.17.1                    |                           |                           |
| 224 | strict-rfc3339            | 0.7                       |                           |                           |
| 225 | tblib                     | 1.7.0                     |                           |                           |
| 226 | tenacity                  | 8.0.1                     | 8.0.1                     |                           |
| 227 | termcolor                 |                           | 1.1.0                     |                           |
| 228 | terminado                 | 0.13.3                    |                           |                           |
| 229 | texttable                 | 1.6.4                     | 1.6.4                     |                           |
| 230 | threadloop                | 1.0.2                     |                           |                           |
| 231 | thrift                    | 0.16.0                    |                           |                           |
| 232 | tinycss2                  | 1.1.1                     |                           |                           |
| 233 | toml                      |                           |                           | 0.10.2                    |
| 234 | tomli                     | 2.0.1                     | 2.0.1                     | 2.0.1                     |
| 235 | toolz                     | 0.11.2                    |                           |                           |
| 236 | tornado                   | 6.1                       | 6.1                       |                           |
| 237 | tqdm                      | 4.64.0                    | 4.64.0                    |                           |
| 238 | traitlets                 | 5.1.1                     | 5.1.1                     |                           |
| 239 | typer                     | 0.4.1                     | 0.4.1                     | 0.4.1                     |
| 240 | types-aiofiles            |                           | 0.8.6                     |                           |
| 241 | types-pkg-resources       |                           | 0.1.3                     |                           |
| 242 | types-pyyaml              |                           | 6.0.5                     |                           |
| 243 | typing-extensions         | 4.1.1                     | 4.1.1                     | 4.1.1                     |
| 244 | ujson                     | 4.3.0, 5.2.0              |                           |                           |
| 245 | urllib3                   | 1.26.9                    | 1.26.9                    |                           |
| 246 | uvicorn                   | 0.15.0, 0.17.6            |                           |                           |
| 247 | uvloop                    | 0.16.0                    |                           |                           |
| 248 | virtualenv                |                           |                           | 20.14.1                   |
| 249 | watchdog                  | 2.1.7                     |                           | 2.1.7                     |
| 250 | watchgod                  | 0.8.2                     |                           |                           |
| 251 | webencodings              | 0.5.1                     |                           |                           |
| 252 | websocket-client          | 0.59.0, 1.3.2             | 0.59.0, 1.3.2             |                           |
| 253 | websockets                | 10.2                      | 10.2                      |                           |
| 254 | werkzeug                  | 2.1.1                     |                           |                           |
| 255 | wheel                     |                           |                           | 0.37.1                    |
| 256 | wrapt                     | 1.14.0                    | 1.14.0                    | 1.14.0                    |
| 257 | yarl                      | 1.5.1, 1.7.2              | 1.5.1, 1.7.2              |                           |
| 258 | zict                      | 2.1.0                     |                           |                           |

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
Looks ok to me. just one thing, I saw the dask-sidecar dependencies changed and I don't see changes in the director-v2 base.txt. Are you sure you updated in the right order?

**Comment by GitHK** [comment]
> Looks ok to me. just one thing, I saw the dask-sidecar dependencies changed and I don't see changes in the director-v2 base.txt. Are you sure you updated in the right order?

Yes apparently I had to go over all the packages again. think I managed to bump all requirements.

**Review by sanderegg — APPROVED** [review]
seems good.
concerning pennsieve I think that pedro already asked for that.
[https://github.com/Pennsieve/pennsieve-python/pull/15](https://github.com/Pennsieve/pennsieve-python/pull/15)

**Review by pcrespov — COMMENTED** [review]
Why did you upgrade the entire repo in a single PR?  We usually upgrade only tooling and test dependencies in a single PR but when it comes to services, we do it in separate PRs.

Is it because of the change in servicelib? If so, When you remove a common dependency you should upgrade carefully downstream to avoid full upgrade.

**Review by pcrespov — CHANGES_REQUESTED** [review]
see comment above. I suggest to split changes in different PRs

Read https://github.com/pcrespov/osparc-simcore/blob/master/requirements/how-to-prune-requirements.md#steps-to-prune-a-library-and-all-services-downstream

**Comment by pcrespov** [comment]
@GitHK perhaps we can close thisone, I added already two upgrades in the last week and more to come in the next

**Comment by GitHK** [comment]
> @GitHK perhaps we can close this PR? I added already two upgrades in the last week and more to come in the next

Yes, I was thinking of doing it.

**Pull request closed without merging**
