### PR TITLE
Nodes Tree UI/UX: Show/hide action buttons

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Nodes tree action buttons show/hide when hovering/unhovering. If the item is selected the action buttons will be visible.

NodesTree-interactive actions

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
pretty, very pretty!

**Review by KZzizzle — COMMENTED** [review]
looks good!

**Review by GitHK — COMMENTED** [review]
The interaction with the delete button on the project is strange. When pressing the delete button on the study a delete node pop-up is shown. Why even have this option enabled since it will not delete the study?

See  below image.

Oct-01-2021 15-47-44
m

**Comment by odeimaiz** [comment]
> The interaction with the delete button on the project is strange. When pressing the delete button on the study a delete node pop-up is shown. Why even have this option enabled since it will not delete the study?
> 
> See below image.
> 
> Oct-01-2021 15-47-44

You are right, the delete button should be disabled in the study item and also in the current/selected item

**Review by pcrespov — APPROVED** [review]

**Comment by schilds77** [comment]
Hi Odei

Yes, I think this is going in the right direction, nice. I'll add some suggestions for improvement here, but from my side it's ok to merge I guess. I leave it to you to further process (or ignore :-) my comments.

- I think 3 inline buttons in a row is the limit before it looks too complicated. Consider to make one of the buttons into a button that show a drop down menu so you can populate it with options that are less frequently used, and it would enable you to add more advanced options like "delete selected" and other operations that affect all selected tree nodes for example.
- For example, I would try to enable renaming by clicking on a selected item for a second time, and relegating the renaming button into said drop down...
- I would not show buttons for selected rows, only for the currently highlighted row (i.e. where the mouse currently is hovering over).
- Can you try to render the buttons without background (or with transparent background)? I.e. only the actual icon svg? I think this would make it look more integrated into the tree.
- I think the tree would benefit from visualizing the highlighted state (if we use that term for rows currently under the mouse pointer). This sould be a visually light element so it's clear the selection is more important. For example, a thin rounded rectangle around the row content might look nice.
- Can you remove the root group? As it seems to be merely the name of the study (which cannot be removed anyway), I do not see any benefit in having this as an element of the tree?
- I would actually remove the title of the frame, but revisit the padding around the actual tree. I'd add at least half a line (=text height) of padding to the top. The leading and trailing paddings seems ok, maybe check that they are the same.

**Comment by odeimaiz** [comment]
> Hi Odei
> 
> Yes, I think this is going in the right direction, nice. I'll add some suggestions for improvement here, but from my side it's ok to merge I guess. I leave it to you to further process (or ignore :-) my comments.
> 
> * I think 3 inline buttons in a row is the limit before it looks too complicated. Consider to make one of the buttons into a button that show a drop down menu so you can populate it with options that are less frequently used, and it would enable you to add more advanced options like "delete selected" and other operations that affect all selected tree nodes for example.
> * For example, I would try to enable renaming by clicking on a selected item for a second time, and relegating the renaming button into said drop down...
> * I would not show buttons for selected rows, only for the currently highlighted row (i.e. where the mouse currently is hovering over).
> * Can you try to render the buttons without background (or with transparent background)? I.e. only the actual icon svg? I think this would make it look more integrated into the tree.
> * I think the tree would benefit from visualizing the highlighted state (if we use that term for rows currently under the mouse pointer). This sould be a visually light element so it's clear the selection is more important. For example, a thin rounded rectangle around the row content might look nice.
> * Can you remove the root group? As it seems to be merely the name of the study (which cannot be removed anyway), I do not see any benefit in having this as an element of the tree?
> * I would actually remove the title of the frame, but revisit the padding around the actual tree. I'd add at least half a line (=text height) of padding to the top. The leading and trailing paddings seems ok, maybe check that they are the same.

Thanks @schilds77, the transparent background for buttons and the thin rounded border when hovered were added. The rest can be further implemented/discussed.

**Pull request merged**
