### PR TITLE
🐛 Improve db performance when searching files

### PR DESCRIPTION
**Pull request by bisgaard-itis**
## What do these changes do?
- Improve performance when looking up files in storage 
- @wvangeit discovered (thanks a lot) that the way we search for files in storage is very inefficient. Together with @matusdrobuliak66 (thanks a lot) we investigated the way the files metadata table and projects table are setup. This PR should improve performance of the search.

## Related issue/s

- https://github.com/ITISFoundation/osparc-simcore/issues/5729

## Dev-ops checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by wvangeit — APPROVED** [review]
Thx 🥳

**Review by sanderegg — APPROVED** [review]
Very nice, thank you very much!
Nevertheless I would also ask why you need to search for files everytime?? the api-server knows which file ID it has, so I do not quite get why it needs to search instead of just asking for a well know file ID. That would also reduce the load.

**Comment by bisgaard-itis** [comment]
> Very nice, thank you very much! Nevertheless I would also ask why you need to search for files everytime?? the api-server knows which file ID it has, so I do not quite get why it needs to search instead of just asking for a well know file ID. That would also reduce the load.

The reason for this is the following: When users write scripts which call the api-server they typically/often upload a file. When debugging/improving their script they run it many many times. Each time uploading the file. This can be quite heavy if the file(s) is large. Hence, I added a mechanism in the upload function in the osparc python client which searches storage to see if there is a file matching the name and sha256 of the file the user is trying to upload. If that is the case, then I return that one instead of reuploading. Let me knwo if you don't think this makes sense.

**Review by pcrespov — APPROVED** [review]
:tada:

**Pull request merged**
