### PR TITLE
🎨 [Frontend] Expose tags in Usage table

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

projectTags

## Related issue/s

- related to https://github.com/ITISFoundation/osparc-issues/issues/1771

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by giancarloromeo — APPROVED** [review]

**Review by matusdrobuliak66 — APPROVED** [review]
:+1:

**Review by sanderegg — COMMENTED** [review]
qweqwe... that is my password man :face_with_head_bandage:

**Review by pcrespov — COMMENTED** [review]
Cool. 

Some suggestions:
- rename  `Node` column? 
- width should fit all displayed columns (tips: hide some)
- color tags

**Review by GitHK — COMMENTED** [review]
👍

**Comment by odeimaiz** [comment]
> * rename  `Node` column?
rename to?

> * width should fit all displayed columns (tips: hide some)
Which one should be hidden?

> * color tags
I only get the string

**Review by jsaq007 — APPROVED** [review]

**Pull request merged**
