### PR TITLE
🎨 [e2e-frontend] Navigation Bar and User Menu

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Extend the Navigation Bar testing and some User Menu testing.

It also adds a test that would detect the bug as mentioned by @sanderegg in [this comment](https://github.com/ITISFoundation/osparc-simcore/pull/6601#pullrequestreview-2394972996).

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
:+1:

**Review by sanderegg — COMMENTED** [review]
💯 nice!

**Review by GitHK — APPROVED** [review]
👍

**Review by jsaq007 — APPROVED** [review]
👍🏼

**Pull request merged**
