### PR TITLE
Context to the Wheel

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
- When right-clicking on the Workbench, the following actions show up:
  - Add new service
  - Draw rectangle
  - Draw text
- When right-clicking on a Node, the following actions show up:
  - Add/Remove Marker
  - Delete node
  - Connect to the input
  - Connect to the output

## Bonus:
- Study Browser: Only studies are part of the scroll area, search filter and selection will get anchored at the top
- Command shortcuts are shown on NodesTree's and NodeUI's menus

The smart wheel:
TheWheel

Scroll studies:
scrollStudies

### CODE REVIEW

**Review by mguidon — APPROVED** [review]
- Part 1: We clearly need more dimensionality
- Part 2: God bless thy teeth

**Review by pcrespov — APPROVED** [review]
Very nice! 🎉 
This partially implements as well #2954

I am not sure annotations section on the left is anymore necesary

**Review by sanderegg — APPROVED** [review]
oooooh

**Comment by odeimaiz** [comment]
> Minor point: could the icon to add an upstream node be different than adding a downstream one? e.g. a + with an arrow to one side or perhaps a variation of the input/output icon: image

I agree that the same icon on both sides is a bit confusing.

@KZzizzle With the library we are using, these are the icons that work out of the box:
https://victorribeiro.com/radialMenu/font-visualizer.html

**Pull request merged**
