### PR TITLE
✨ Auto-recharge: save changes

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

The save changes feature was missing. This PR does some refactoring, implements the Saving operation and improves the UX.

### Bonus
- ``GUEST``s also need to know about their ``user.permissions.read``

SaveAutoRecharge

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
Much better than the last version but I still find it a bit confusing when is the auto-recharge actually enabled and when is disabled  ...  I guess appmotion will give you  more feedback on this.

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by GitHK — COMMENTED** [review]
👍

**Review by ignapas — APPROVED** [review]
👍🏼

**Review by jsaq007 — COMMENTED** [review]
👍

**Pull request merged**
