### PR TITLE
Qooxdoo update

### PR DESCRIPTION
**Pull request by ignapas**
## What do these changes do?

Uses last qooxdoo-sdk version to have the splitter removed from splipanes.

[waffle.io]:https://waffle.io/marketing-assets/documents/waffleio_cheatsheet_v1.pdf?utm_source=blog&utm_medium=cheatsheet-ctabutton&utm_campaign=cheatsheet

### CODE REVIEW

**Comment by odeimaiz** [comment]
@oetiker What about the contribs? Is there a way to always get the latest version?

**Comment by oetiker** [comment]
the latest qooxdoo-compiler lets you use 'tree-ish' references, but I would not recommend todo that ... just use qx contrib install contribname to update the respective contrib and create a PR

**Comment by odeimaiz** [comment]
> the latest qooxdoo-compiler lets you use 'tree-ish' references, but I would not recommend todo that ... just use qx contrib install contribname to update the respective contrib and create a PR

https://github.com/ITISFoundation/osparc-simcore/issues/691

**Comment by ignapas** [comment]
> > the latest qooxdoo-compiler lets you use 'tree-ish' references, but I would not recommend todo that ... just use qx contrib install contribname to update the respective contrib and create a PR
> 
> #691

You want me to do it and push it here? which contribs you want to update?

**Comment by ignapas** [comment]
@oetiker Contrib installation failed (empty Manifest issue...)

**Pull request closed without merging**
