### PR TITLE
🎨🔒️ Remove deprecated services for the SPARC Portal

### PR DESCRIPTION
**Pull request by elisabettai**
## What do these changes do?
Adds a filter on the list returned by `/v0/services` to remove deprecated services (the ones that have an entry in DB, in the table `services_meta_data`, column `deprecated`.

## Related issue/s
- This PR follows up on  https://github.com/ITISFoundation/osparc-simcore/pull/4024
- resolves ITISFoundation/osparc-issues#683

## How to test

Deploy the stack, go to `/v0/services`, in that list services that have a deprecation date in the DB, should not appear.

## How did I test it?
I've exported and imported services data from osparc.io DB into my local deploy DB (applying as filter `jupyter`). 
Before applying this PR, going to `/v0/services` in the browser gave 10 results. After applying the PR `/v0/services` gave 5 results. I then double-checked that the 5 missing ones are deprecated ones.

### CODE REVIEW

**Review by odeimaiz — CHANGES_REQUESTED** [review]
Please add a query parameter to filter the deprecated ones. The osparc frontend needs **all** the services...

**Comment by elisabettai** [comment]
> Please add a query parameter to filter the deprecated ones. The osparc frontend needs **all** the services...

Ah, I was not aware that this `/services` endpoint was used by the osparc frontend, I thought was a new one made for the Portal frontend for NIH (see specs [here](https://github.com/ITISFoundation/osparc-simcore/blob/master/services/web/server/src/simcore_service_webserver/api/v0/openapi.yaml#L8117), I believe).

**Review by pcrespov — COMMENTED** [review]
@odeimaiz  I do not think this entry is used in the front-end. This was internationally separated in the `NIH group` of the web-api and is intended for the portal

image

@elisabettai please fill the issue ;-)
image

**Comment by elisabettai** [comment]
> @odeimaiz I do not think this entry is used in the front-end. This was internationally separated in the `NIH group` of the web-api and is intended for the portal
> 
> image
> 
> @elisabettai please fill the issue ;-) 
Ops, I forgot, thanks @pcrespov, I filled the issue,
@odeimaiz, then I guess I don't need to add changes for the frontend.

**Review by odeimaiz — APPROVED** [review]

**Review by pcrespov — APPROVED** [review]

**Review by pcrespov — APPROVED** [review]

**Review by sanderegg — APPROVED** [review]

**Pull request merged**
