### PR TITLE
💣 Remove osparc-gateway-server and clusters endpoints

### PR DESCRIPTION
**Pull request by sanderegg**
## What do these changes do?
- 💣 deleted osparc-gateway-server service
- 💣 removed dask-gateway library everywhere
- 💣 removed dask-gateway-server library everywhere
- 💣 removed Clusters entrypoints in webserver
- 💣 removed Clusters entrypoints in director-v2

## Dev-ops checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by GitHK — APPROVED** [review]
RIP

**Review by odeimaiz — COMMENTED** [review]
Thanks

**Review by pcrespov — APPROVED** [review]
boom! :-)

**Review by YuryHrytsuk — COMMENTED** [review]
Shall we also remove this ENV from `osparc-config`?

**Review by matusdrobuliak66 — APPROVED** [review]
:+1:

**Comment by sanderegg** [comment]
> Shall we also remove this ENV from `osparc-config`?

@YuryHrytsuk yes but deploy by deploy. same as when changing an ENV.

**Pull request merged**
