### PR TITLE
✨ Frontend feature: Show available Tiers in Service metadata

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Add tab page that shows available Tiers in Service Details
- [x] Fix: Scroll container in its info page

Tiers

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
Question: if there is no tier available, why is the version even selectable?

**Comment by odeimaiz** [comment]
> Question: if there is no tier available, why is the version even selectable?

Correct, that's something I wanted to ask the @backenders. Isn't there a billable check for services before being listed or a default pricing plan?

**Review by jsaq007 — APPROVED** [review]
Looks good to me

**Comment by mguidon** [comment]
Thanks. Can I select the tier in the new tab and will not be bothered with it again in the advanced part of the follow up dialog? Or is this merely to show the options?

**Comment by odeimaiz** [comment]
> Thanks. Can I select the tier in the new tab and will not be bothered with it again in the advanced part of the follow up dialog? Or is this merely to show the options?

This just shows the options. What you request could be implement, but you would still be bothered with the give-your-project-a-name dialog.

**Pull request merged**
