### PR TITLE
✨Frontend: Notify sharer

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Frontend part for https://github.com/ITISFoundation/osparc-simcore/pull/4253

After adding collaborators to a Study, the frontend calls to the new ``:access`` endpoint to check if the new collaborator has actually access to the services in the study. If there are any inaccessible services, these are listed in a new "Sharee permissions" window.

NotifySharer

## Related issue/s

closes https://github.com/ITISFoundation/osparc-issues/issues/909

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
:+1:

**Review by matusdrobuliak66 — APPROVED** [review]
Nice :+1:

**Review by elisabettai — CHANGES_REQUESTED** [review]
Very cool!
One important thing to add explaining what the user who wants to share with someone who has no access to all the services should do.

At this point, I think the only options is to contact support (to the e-mail) or open a Github issue. Maybe we can add this two links in the message. Or to share the service as you show in the animation, if the user who's sharing is the owner (which is unlikely for external users).

At some point will be nice if we can automatically send a notification so the service owner.

**Comment by odeimaiz** [comment]
> Very cool! One important thing to add explaining what the user who wants to share with someone who has no access to all the services should do.
> 
> At this point, I think the only options is to contact support (to the e-mail) or open a Github issue. Maybe we can add this two links in the message. Or to share the service as you show in the animation, if the user who's sharing is the owner (which is unlikely for external users).
> 
> At some point will be nice if we can automatically send a notification so the service owner.

I added the following text: ``Please contact the service owner(s) to give permission.``. Next to the service name and version there is the ``i``nfo button, where all this information is accessible, I don't think there is much more we can do atm.

**Comment by elisabettai** [comment]
> > Very cool! One important thing to add explaining what the user who wants to share with someone who has no access to all the services should do.
> > At this point, I think the only options is to contact support (to the e-mail) or open a Github issue. Maybe we can add this two links in the message. Or to share the service as you show in the animation, if the user who's sharing is the owner (which is unlikely for external users).
> > At some point will be nice if we can automatically send a notification so the service owner.
> 
> I updated the text: `The following users/groups will not be able to open the shared study, because they don't have access to some services. Please contact the service owner(s) to give permission.`. Next to the service name and version there is the `i`nfo button, where all this information is accessible, I don't think there is much more we can do atm.

Ok, when they hover on the service owner name they should see the email address and they can contact them. It's a bit hidden, but somewhat findable. 😉

**Review by elisabettai — APPROVED** [review]

**Pull request merged**
