### PR TITLE
⬆️ Pydantic v2 migration

### PR DESCRIPTION
**Pull request by sanderegg**
## What do these changes do?
This PR contains all the changes to migrate osparc-simcore to pydantic V2.

# **It can only be merged once all the services are migrated!**

## Related issue/s
- closes https://github.com/ITISFoundation/osparc-simcore/issues/4481

## Dev-ops checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Comment by giancarloromeo** [comment]
Quality gate complains because there is duplicated code (actually it has been moved from `models_library` to `common_library` but in this PR it is still in both).

**Review by giancarloromeo — APPROVED** [review]

**Review by GitHK — APPROVED** [review]
Finally green! Looking forward to seeing this in master

**Review by pcrespov — APPROVED** [review]
:tada:

**Review by mrnicegyu11 — APPROVED** [review]
jesus, TL;DR!

but damn, thank you guys to much for pushing this!

**Review by matusdrobuliak66 — APPROVED** [review]
:1st_place_medal:

**Pull request merged**
