### PR TITLE
Pie context menu

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR brings the pie on the cherry.

It integrates the [radialMenu library](https://github.com/victorqribeiro/radialMenu) and for now it is only used when right clicking on the workbenchUI. In this context menu the following actions are provided:
- Add new service
- Zoom in
- Reset zoom
- Zoom out

## Bonus
- [x] Select study item on Nodes Tree/List when nodes selection is empty

PieMenu

### CODE REVIEW

**Review by mguidon — APPROVED** [review]
Real nice. @ignapas @colinRawlings I think we have to accept the challenge and create a rocket-pie for the modeling.

**Review by pcrespov — COMMENTED** [review]
fancy!

**Review by sanderegg — APPROVED** [review]
greatness

**Review by KZzizzle — APPROVED** [review]
great!

**Pull request merged**
