### PR TITLE
⬆️ upgrading httpx for director-v2

### PR DESCRIPTION
**Pull request by GitHK**
## What do these changes do?

Apparently `httpx` or `anyio` (dependency) may have issues in resolving hostnames with docker. Trying to update to latest version to see if issue persists.

## Related issue/s

- trying to address https://github.com/ITISFoundation/osparc-simcore/issues/4161

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]
Once you have verified that this upgrade is actually necessary, can you please follow up with a target upgrade of these two libraries on the entire repo?

**Review by matusdrobuliak66 — APPROVED** [review]

**Comment by GitHK** [comment]
> Once you have verified that this upgrade is actually necessary, can you please follow up with a target upgrade of these two libraries on the entire repo?

Yes I will do so

**Comment by mrnicegyu11** [comment]
Thanks for this, and good luck. Tbh I looked at the changelog of the libraries and am doubtful that this will help. the gitlab issue chat you linked in the assoc. issue points towards this being a docker problem.

**Comment by GitHK** [comment]
> Thanks for this, and good luck. Tbh I looked at the changelog of the libraries and am doubtful that this will help. the gitlab issue chat you linked in the assoc. issue points towards this being a docker problem.

I'm doubtful myself it will help but it's an attempt at seeing how it behaves after the upgrade.

**Review by sanderegg — APPROVED** [review]

**Pull request merged**
