### PR TITLE
🎨 Bill dynamic service in case of error. 

### PR DESCRIPTION
**Pull request by matusdrobuliak66**
## What do these changes do?
- 🎨 Bill dynamic service in case of error. 

## Related issue/s
- closes https://github.com/ITISFoundation/osparc-issues/issues/1397 

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]

**Review by sanderegg — APPROVED** [review]
Question here:
so if I get the reasoning right, it is that now we bill the dynamic service as long as it ran correctly?
so what happens if it ran for 3 hours correctly, then fails to switch off for 2 hours? what gets billed?

**Comment by matusdrobuliak66** [comment]
> Question here: so if I get the reasoning right, it is that now we bill the dynamic service as long as it ran correctly? so what happens if it ran for 3 hours correctly, then fails to switch off for 2 hours? what gets billed?

Hi, until now, we billed it only if it ran correctly. If there was a problem on our side and RUT did not receive heartbeats, it would not be billed at all. With this change, even if this situation occurs, it will be billed from the start until the last heartbeat.

**Comment by sanderegg** [comment]
> > Question here: so if I get the reasoning right, it is that now we bill the dynamic service as long as it ran correctly? so what happens if it ran for 3 hours correctly, then fails to switch off for 2 hours? what gets billed?
> 
> Hi, until now, we billed it only if it ran correctly. If there was a problem on our side and RUT did not receive heartbeats, it would not be billed at all. With this change, even if this situation occurs, it will be billed from the start until the last heartbeat.

ok so in the use-case I wrote above, that means that if you receive heartbeats and the system is stuck it will still be billed.

**Comment by matusdrobuliak66** [comment]
> > > Question here: so if I get the reasoning right, it is that now we bill the dynamic service as long as it ran correctly? so what happens if it ran for 3 hours correctly, then fails to switch off for 2 hours? what gets billed?
> > 
> > 
> > Hi, until now, we billed it only if it ran correctly. If there was a problem on our side and RUT did not receive heartbeats, it would not be billed at all. With this change, even if this situation occurs, it will be billed from the start until the last heartbeat.
> 
> ok so in the use-case I wrote above, that means that if you receive heartbeats and the system is stuck it will still be billed.

Yes, if the dynamic sidecar considers itself as running it will be billed unless a stop event is sent to RUT.

**Pull request merged**
