### PR TITLE
✨   Surface job status

### PR DESCRIPTION
**Pull request by jsaq007**
## What do these changes do?

- Show the status of computational jobs
- Update the UI for visual improvements

## Dev Checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
it looks really nice! 🎉

**Review by sanderegg — APPROVED** [review]
very pretty! :100:

**Review by elisabettai — APPROVED** [review]
Oh woooooooow, for a second I thought you were working on a platform totally different from oSPARC! 
Visually amazing.

**Review by ignapas — COMMENTED** [review]
Some minors:

* Changing tags makes the bottom ribbon disappear

Peek 2023-11-20 15-03
* S4L v8 default thumbnail looks a bit off (framing and definition)
* Selection issue
image

**Review by mguidon — APPROVED** [review]
Real Nice!

**Review by matusdrobuliak66 — APPROVED** [review]
Very nice! :)

**Review by ignapas — APPROVED** [review]

**Pull request merged**
