### PR TITLE
Run partial pipeline. Frontend

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
- [x] Show running status on computational services
- [x] Run button context dependant. If node(s) selected Run button says "Run selection "and partial pipeline is run

#### Bonus:
- [x] Retrieve button (soon deprecated) doesn't belong the the Node Data Model

RunningStateChip

## Related issue number
related to https://github.com/ITISFoundation/osparc-simcore/pull/2040

## Checklist

- [ ] Did you change any service's API? Then make sure to bundle document and upgrade version (``make openapi-specs``, ``git commit ...`` and then ``make version-*``)
- [ ] Unit tests for the changes exist
- [ ] Runs in the swarm
- [ ] Documentation reflects the changes
- [ ] New module? Add your github username to [.github/CODEOWNERS](.github/CODEOWNERS)

### CODE REVIEW

**Review by ignapas — CHANGES_REQUESTED** [review]
great stuff... only I saw some stuff in the UI
* Nodes in workbench show a dark spot
image
* Running selection resets the progress of all nodes
* If I run this selection, the intermediate nodes won't run again (maybe it is intended)
* image
* I think that while the pipeline is running, the selection shouldn't change the text nor the state on the run button. If the user runs a selection, the text should remain "Run selection" until it finishes or fails, and then it can resume updating according to the selection.
* There should be an option to run the entire pipeline even if some nodes are selected, maybe using a http://qooxdoo.org/qxl.apiviewer/#qx.ui.form.SplitButton for the run button?

**Review by GitHK — COMMENTED** [review]
Very nice. I can run the entire pipeline or the selected node. 👍 

A few suggestions to improve visual feedback as it results misleading:
- when the entire pipeline is ran I get the following result which is good
Screenshot 2020-12-17 at 10 44 05
- if I run the entire pipeline again I get the "success" being visible without a saying "going to run", but the progress got cleared 
Screenshot 2020-12-17 at 10 45 02

- after I run the last node I get all the bars reset with is not what I have expected
Screenshot 2020-12-17 at 10 43 27

If you manage to address the above it would be great!

**Comment by odeimaiz** [comment]
> * Nodes in workbench show a dark spot
Done, hidden if there is no status

> * Running selection resets the progress of all nodes
ProgressBar now relies on what the backend says

> * If I run this selection, the intermediate nodes won't run again (maybe it is intended)
Backend

> * I think that while the pipeline is running, the selection shouldn't change the text nor the state on the run button. If the user runs a selection, the text should remain "Run selection" until it finishes or fails, and then it can resume updating according to the selection.
Done, if it's fetching, the text will not get updated

> * There should be an option to run the entire pipeline even if some nodes are selected, maybe using a http://qooxdoo.org/qxl.apiviewer/#qx.ui.form.SplitButton for the run button?
Clicking in the empty workbench resets selection. Same number of clicks away from the same action

**Comment by odeimaiz** [comment]
ProgressBar now relies on what the backend says

**Review by KZzizzle — APPROVED** [review]
I have nothing to add to Andrei's comments - they were very thorough =)  Everything else works as expected and it's great - well done Odei!!

**Review by ignapas — APPROVED** [review]

**Pull request merged**
