### PR TITLE
✨Autoscaling: allow multiple autoscaling services

### PR DESCRIPTION
**Pull request by sanderegg**
## What do these changes do?

This PR allows to run several Autoscaling services with different purposes:
- 1 Autoscaling that takes care for example of scaling EC2 instances for a specific service (i.e. jupyter-math)
- 1 Autoscaling that takes care for example of scaling EC2 instances for another service (i.e. s4l)

The PR allows both Autoscaling application to not trample each other feet by stealing each other machines.

 Each Autoscaling is made unique through the ENV ```NODES_MONITORING_NODE_LABELS``` and ```NODES_MONITORING_SERVICE_LABELS```

## Related issue/s
NOTE: the moto library has an issue, see https://github.com/getmoto/moto/issues/5966. This implied that a patch had to be applied in the unit tests. Real testing with AWS showed that the system is functional.

bonus:
fixes https://github.com/ITISFoundation/osparc-simcore/issues/3842

### CODE REVIEW

**Review by mrnicegyu11 — APPROVED** [review]
lgtm, looking forward.

thanks a lot!

**Review by GitHK — COMMENTED** [review]
One thing is not clear to me:
1. how is this going to be deployed?
1. How will autoscaling work?
  - a) will we add multiple autoscaling micro services in the docker-compose configuration?
  - b) Or will one instance of autoscaling be able to deal with scaling the machines for different services?

**Comment by sanderegg** [comment]
> One thing is not clear to me:
> 
> 1. how is this going to be deployed?
> 2. How will autoscaling work?
> 
> * a) will we add multiple autoscaling micro services in the docker-compose configuration?
> * b) Or will one instance of autoscaling be able to deal with scaling the machines for different services?

@GitHK 
so the answer is a) ;) one responsibility

**Review by GitHK — APPROVED** [review]
Had an offline chat. 

Among other things, I missed the fact that we could have multiple services running on the same pool of autoscaled machines.

👍 this makes sense to me now

**Pull request merged**
