### PR TITLE
🐛 [Frontend] Fix: Unique session id

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Changes the logic to create/get the clientsessionid. When a tab gets duplicated, the ``sessionStorage`` and ``localStorage`` get also copied. When this happens, two different tabs would end up using the same sessionId, bringing the user to buggy scenarios.

This PR updates the getClientSessionId function, which now also relies on the ``window.name``, which doesn't get copied when a tab is duplicated but it persists to window reloads.

uniqueTabId

## Related issue/s

closes https://github.com/ITISFoundation/osparc-simcore/issues/4363

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by sanderegg — COMMENTED** [review]
great! thanks!

**Review by pcrespov — COMMENTED** [review]
thx

**Review by GitHK — COMMENTED** [review]
🙏 thanks a lot!

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by jsaq007 — APPROVED** [review]
👍🏼

**Pull request merged**
