### PR TITLE
Confirmations page

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Provide warnings for the following actions:
- Back to dashboard
- Delete study
- Delete node
- Window size

PS: these options, for now, are not be persistent.

image

## Related issue/s
closes https://github.com/ITISFoundation/osparc-simcore/issues/2248

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
to the point.

**Review by pcrespov — COMMENTED** [review]
I know what you intend with this PR but from a UX perspective I find these settings a bit strange. If they are checked, they enable a confirmation?
Shouldn't be stated better as a list of "sentences" as
- [ ] Ask for confirmation before ...
- [ ] Collapse if ...
- [ ] When X then Z

**Comment by odeimaiz** [comment]
> I know what you intend with this PR but from a UX perspective I find these settings a bit strange. If they are checked, they enable a confirmation?
> Shouldn't be stated better as a list of "sentences" as
> 
> * [ ]  Ask for confirmation before ...
> * [ ]  Collapse if ...
> * [ ]  When X then Z

Do you want each option to say:
- [ ] Ask for confirmation before going back to the dashboard
- [ ] Ask for confirmation before deleting a study
- [ ] Ask for confirmation before deleting a node

**Review by KZzizzle — APPROVED** [review]
I don't care so much about the wording. For example it could say "Provide warnings for the following actions:" and then the list. 

A bonus for me would be disabling the "screen size too small" but that's not crucial

**Comment by odeimaiz** [comment]
> I don't care so much about the wording. For example it could say "Provide warnings for the following actions:" and then the list.
> 
> A bonus for me would be disabling the "screen size too small" but that's not crucial

I will update the wording, thanks.

The bonus request would also be very easy to add, but taking into account that, for now, theae preferences are not persistent, not sure if it makes much sense.

**Pull request merged**
