### PR TITLE
Is1877/allow constraints on director services

### LINKED ISSUE #1877: The director need to add a new label to the service he is deploying
**USER STORY:**

We want to isolate as much services from the simcore-stack as we can (all except traefik and the director). In order to do that, we need the director to tell to the service he will deploy to go on the node who have the label sidecar=true (or the label of your choice)

### PR DESCRIPTION
**Pull request by sanderegg**
## What do these changes do?

- allows OPS to set a custom placement constraints on services spawned by the director

fixes #1877 

## Checklist

- [ ] Did you change any service's API? Then make sure to bundle document and upgrade version (``make openapi-specs``, ``git commit ...`` and then ``make version-*``)
- [ ] Unit tests for the changes exist
- [x] Runs in the swarm
- [ ] Documentation reflects the changes
- [ ] New module? Add your github username to [.github/CODEOWNERS](.github/CODEOWNERS)

### CODE REVIEW

**Review by GitHK — APPROVED** [review]
OK with me.

**Review by pcrespov — APPROVED** [review]

**Review by mguidon — COMMENTED** [review]
How does this work. Where are the node labels defined where this is mapped onto?

**Comment by sanderegg** [comment]
> How does this work. Where are the node labels defined where this is mapped onto? Does this allow me to add any label to a node and the reuse that in a docker image label?

This is a general constraints for use with DEVOPS. Basically you define a DIRECTOR_SERVICES_CUSTOM_CONSTRAINTS environ when deploying the simcore stack. -> all the services spawned by the director will receive this additional constraint.

As to your question, you can already define individual constraints on the services by setting them in the docker labels of the service.

**Comment by mguidon** [comment]
> > How does this work. Where are the node labels defined where this is mapped onto? Does this allow me to add any label to a node and the reuse that in a docker image label?
> 
> This is a general constraints for use with DEVOPS. Basically you define a DIRECTOR_SERVICES_CUSTOM_CONSTRAINTS environ when deploying the simcore stack. -> all the services spawned by the director will receive this additional constraint.
> 

I understand that what I meant was more: Is it possible to do that via env variables and node labels only without having to change the resources config (i.e. VRAM) in the docker daemon on the nodes.

**Comment by mguidon** [comment]
> > > How does this work. Where are the node labels defined where this is mapped onto? Does this allow me to add any label to a node and the reuse that in a docker image label?
> > 
> > 
> > This is a general constraints for use with DEVOPS. Basically you define a DIRECTOR_SERVICES_CUSTOM_CONSTRAINTS environ when deploying the simcore stack. -> all the services spawned by the director will receive this additional constraint.
> 
> I understand that what I meant was more: Is it possible to do that via env variables and node labels only without having to change the resources config (i.e. VRAM) in the docker daemon on the nodes.

Resolved in private chat. I CAN do what I want.

**Review by Surfict — APPROVED** [review]

**Pull request merged**
