### PR TITLE
🐛 De-synchronizing the file pickers

### PR DESCRIPTION
**Pull request by ignapas**
## What do these changes do?
Fix the nasty bug where several file pickers in the same study instantly replicated each other's outputs

## Related issue/s

Not sure if there's one

## How to test

* Upload and clear several file pickers and check that their outputs are no longer synchronized
* Play with other services' outputs too

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by sanderegg — COMMENTED** [review]
:+1:

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by GitHK — APPROVED** [review]
Thank you so much for this!

**Review by jsaq007 — APPROVED** [review]
Nice one... 👍🏼

**Review by elisabettai — APPROVED** [review]
Great catch! 
Who knows how this got broken. 😏

**Review by odeimaiz — COMMENTED** [review]
I don't really see how these changes could fix the bug... Also, this piece of code didn't change in the last 3-4 years, so I would expect the culprit to be somewhere else.

**Comment by ignapas** [comment]
> I don't really see how these changes could fix the bug... Also, this piece of code didn't change in the last 3-4 years, so I would expect the culprit to be somewhere else.

It fixes it by using the setter to change the value of the outputs instead of directly assigning to the value returned by the getter. We don't know how Qooxdoo's getters/setters are implemented...
My guess is that is was always there or that it surfaced after some other change elsewhere.

**Comment by matusdrobuliak66** [comment]
> > I don't really see how these changes could fix the bug... Also, this piece of code didn't change in the last 3-4 years, so I would expect the culprit to be somewhere else.
> 
> It fixes it by using the setter to change the value of the outputs instead of directly assigning to the value returned by the getter. We don't know how Qooxdoo's getters/setters are implemented... My guess is that it was always there or that it surfaced after some other change elsewhere.

With @GitHK, we have just tested the changes locally, and it seems the issue is gone. Let's try to deploy and observe (because master/staging has different behavior: one uses PATCH, while the other still uses PUT)

**Comment by ignapas** [comment]
> > > I don't really see how these changes could fix the bug... Also, this piece of code didn't change in the last 3-4 years, so I would expect the culprit to be somewhere else.
> > 
> > 
> > It fixes it by using the setter to change the value of the outputs instead of directly assigning to the value returned by the getter. We don't know how Qooxdoo's getters/setters are implemented... My guess is that it was always there or that it surfaced after some other change elsewhere.
> 
> With @GitHK, we have just tested the changes locally, and it seems the issue is gone. Let's try to deploy and observe (because master/staging has different behavior: one uses PATCH, while the other still uses PUT)

The outputs were being assigned there to every file picker node there (maybe other nodes, too) and then the periodic "delayed" patcher was sending them to the server.

**Comment by odeimaiz** [comment]
> > I don't really see how these changes could fix the bug... Also, this piece of code didn't change in the last 3-4 years, so I would expect the culprit to be somewhere else.
> 
> It fixes it by using the setter to change the value of the outputs instead of directly assigning to the value returned by the getter. We don't know how Qooxdoo's getters/setters are implemented... My guess is that it was always there or that it surfaced after some other change elsewhere.

The bug is not reproducible in prod, so I most likely introduced it during the PATCH/PUT refactoring. Good that this changes fix it. Thanks 👌.

I still think that I'm setting one node's outputs object to a different node... I will investigate it a bit deeper.

**Pull request merged**
