### PR TITLE
UI/UX empty File Picker

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR improves the UX when the File Picker has no file selected. When the empty File Picker is selected a "Drop here" field is shown and the Files Tree tab is shown in the primary column.
In the "Drop here" field, files coming from the Files Tree and also the ones coming from the user's local storage can be Drag&Dropped.

EmptyFP

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
That is very nice!
just wondering why the node in the workbench changes shape only when a file is selected. should it have always the same shape?

**Review by KZzizzle — APPROVED** [review]
Very nice! Just to clarify - when there is a file picked for the File Picker, would the user ever be able to change the file? It looks like the file metadata is shown for a file picker node after one is picked so to change files, the user would need to delete that file picker and create another one. I'm not sure this is ideal but I will let you judge on that.

**Comment by odeimaiz** [comment]
> Very nice! Just to clarify - when there is a file picked for the File Picker, would the user ever be able to change the file? It looks like the file metadata is shown for a file picker node after one is picked so to change files, the user would need to delete that file picker and create another one. I'm not sure this is ideal but I will let you judge on that.

Correct. I thought there was no need to add a "Clear selection" button since it usually never changes, but I might be wrong....

**Comment by KZzizzle** [comment]
> > Very nice! Just to clarify - when there is a file picked for the File Picker, would the user ever be able to change the file? It looks like the file metadata is shown for a file picker node after one is picked so to change files, the user would need to delete that file picker and create another one. I'm not sure this is ideal but I will let you judge on that.
> 
> Correct. I thought there was no need to add a "Clear selection" button since it usually never changes, but I might be wrong....

Personally I like being able to change the file "in place" so I don't have to reconnect/map inputs. One example is if I'm troubleshooting a python runner or something. Perhaps @newton1985 has an opinion?

**Review by pcrespov — APPROVED** [review]
beautifil! :tada: 
just a minor suggestion on the message: ``Drop file/s here`` instead of simpley ``Drop Here``

**Pull request merged**
