### PR TITLE
🎨 Frontend UI/UX: S4L logo, Sharee Permissions and Life Cycle view

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- New S4L logo (same as lite, but without the feather :( )
- Sharee Permissions view
  - Warning-yellow icon on caption bar
  - Strong button appearance for the ``i`` button
- Show update service option, if any, when the study is open. It was only visible when the service was eirther deprecated or retired.

Sharee Permissions view:
image

Update service
UpdateService

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
:+1:

**Review by mguidon — APPROVED** [review]
:+1:

**Review by elisabettai — APPROVED** [review]
Very cool, thanks!
I would also make the "Sharee permission" text yellow. 😉

**Review by matusdrobuliak66 — COMMENTED** [review]
:+1:

**Pull request merged**
