### PR TITLE
🐛🎨 Frontend: Nodes can't be added while the pipeline is running

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

When a pipeline is running, if the user adds new nodes the backend will fail with a 409 and no error is shown to the user. The reason is that a pipeline is immutable for the backend and therefore it will reject saving the new pipeline until it finishes. This can cause unpleasant side effects, eg. not letting close the study because the latest conflictive pipeline can't be saved.

This PR won't allow users adding nodes when the pipeline is running.

RunningPipeline

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
great!

**Review by GitHK — APPROVED** [review]
👍

**Comment by pcrespov** [comment]
@odeimaiz this is related to https://github.com/ITISFoundation/osparc-simcore/issues/5640 but would it solve it?

**Review by pcrespov — COMMENTED** [review]
This is related to https://github.com/ITISFoundation/osparc-simcore/issues/5640, but would it solve it?

**Review by jsaq007 — APPROVED** [review]
I am not completely against this implementation but why don't we just disable the add node button if the user isn't able to perform the action. This type of UX is better than clicking on something to get the message that it's not allowed

**Review by matusdrobuliak66 — APPROVED** [review]
Q: But would you agree that this is a backend issue, generally user should be able to add a node correct?

**Comment by odeimaiz** [comment]
> This is related to #5640, but would it solve it?

Not really related, that fix might come later today 👍

**Comment by odeimaiz** [comment]
> Q: But would you agree that this is a backend issue, generally user should be able to add a node correct?

Yes, it's a limitation. Ideally, only the pipeline that was sent to the running queue should be "frozen", but imo it's not that bad.

**Comment by odeimaiz** [comment]
> I am not completely against this implementation but why don't we just disable the add node button if the user isn't able to perform the action. This type of UX is better than clicking on something to get the message that it's not allowed

Agree, we could/should also do that, but the problem is that there more ways to modify the pipeline, eg dropping a file on the workbench would create a File Picker.

**Pull request merged**
