### PR TITLE
🎨 Redesign: Study information page

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR redesigns the Study Large and Medium views.

Study Large:
- More compact grid
- Titles in capitals and shorter
- ``Study Id`` in a button
- ``Disable Services auto start`` option right below the ``Open`` button

Study Medium:
- More compact grid
- Titles in capitals and shorter

### Bonus:
- Make sure Study properties are bound to Study Large and Medium views
- Study preview:
  - Do not show it if study is empty
  - Do not show the Nodes tree if it's a mononode study

Before (Study L):
image

After (Study L):
image

Before (Study M):
image

After (Study M):
image

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]

**Review by sanderegg — APPROVED** [review]
:+1:

**Review by pcrespov — COMMENTED** [review]
:+1:

**Review by elisabettai — APPROVED** [review]
The UX Team approves.

In Study L, you haven't move "TAGS" to the right in the end. 😉

**Comment by odeimaiz** [comment]
> The UX Team approves.
> 
> In Study L, you haven't move "TAGS" to the right in the end. 😉

I never said that I plan to move them (;

**Review by GitHK — APPROVED** [review]

**Pull request merged**
