### PR TITLE
🐛 [Frontend bugfix] List everyone group and provide product-everyone group in potential collaborators

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Fixes:
- [x] List ``Everyone`` in current collaborators list
- [x] List ``Product Everyone`` in current collaborators list

Improvements:
- [x] Do NOT list ``Everyone`` in potential collaborators
- [x] Do NOT list ``Product Everyone`` in potential collaborators for Studies
- [x] DO list ``Product Everyone`` in potential collaborators Templates if user is at least Tester
- [x] DO list ``Product Everyone`` in potential collaborators for Services
- [x] Stop using hardcoded ``Everyone`` info, use the one provided by the backend
- [x] Do not list ``Everyone`` in the Publish as Template options

Studies:
Studies

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by GitHK — COMMENTED** [review]
👍

**Review by sanderegg — APPROVED** [review]

**Review by elisabettai — APPROVED** [review]
Thanks!

My only concern is the "Product Everyone" regular users have no idea of what that is.

**Comment by odeimaiz** [comment]
> My only concern is the "Product Everyone": regular users have no idea of what that is.

The text show was "Public for Product users". I changed it to "Available to all users".

**Review by pcrespov — COMMENTED** [review]
:+1:

**Review by ignapas — APPROVED** [review]

**Pull request merged**
