### PR TITLE
Parameters in frontend

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR gets the frontend ready to deal with Parameter's metadata defined in the backend.

- Parameters
  - Editor
  - Ease assignment
- Specific NodeUI for:
  - parameter

#### Bonus:
- Instead of "in"/"out" ports, a small open circle for unconnected nodes or dot-filled circle for connected ones
- Show full node name with cursor hover if the name is too long
- turn into FilePicker UI improved

Parameters

## Related issue/s
related to https://github.com/ITISFoundation/osparc-issues/issues/328
closes https://github.com/ITISFoundation/osparc-simcore/issues/2437

### CODE REVIEW

**Review by KZzizzle — APPROVED** [review]
Very cool! Just a quick summary of what we discussed:
* smaller font for the parameter values
* instead of "out" port, a small open circle for unconnected parameters or filled circle for connected ones
* slight enlarging of the node for now (until we think of something better)
* possibly showing full parameter name with cursor hover if the parameter name is too long

**Comment by odeimaiz** [comment]
> Very cool! Just a quick summary of what we discussed:
> 
> * smaller font for the parameter values
> * instead of "out" port, a small open circle for unconnected parameters or filled circle for connected ones
> * slight enlarging of the node for now (until we think of something better)
> * possibly showing full parameter name with cursor hover if the parameter name is too long

- [x] smaller font for the parameter values
- [x] instead of "out" port, a small open circle for unconnected parameters or filled circle for connected ones
- [x] slight enlarging of the node for now (until we think of something better)
- [ ]  possibly showing full parameter name with cursor hover if the parameter name is too long

**Comment by KZzizzle** [comment]
I'm a big fan of the update

**Review by ignapas — COMMENTED** [review]
Couldn't get the parameters to show in the Service Catalog, how should I get them?
From what I saw in the capture, which in general looks awesome, these are my suggestions for the moment:
* Do parameters qualify as services? If not, I think they should have their own tab in the service catalog, that could be renamed to "Add item".
* I think the big border-radius doesn't look so cool... circular containers only look good when they have only one item centered both vertically and horizontally. Plus long titles are cut at the beginning.
* Value label should be aligned with the node title.
* Right after moving a node in the workbench, no d&d is possible from the in/out ports of the node.
* The links are super hard to select for removal.

**Comment by odeimaiz** [comment]
> Couldn't get the parameters to show in the Service Catalog, how should I get them?
> From what I saw in the capture, which in general looks awesome, these are my suggestions for the moment:

In the .env, you need to set ```CATALOG_DEV_FEATURES_ENABLED=1```

> * Do parameters qualify as services? If not, I think they should have their own tab in the service catalog, that could be renamed to "Add item".

They do, but we could group them differently. For now, the backend provides them together with the rest of the services.

> * I think the big border-radius doesn't look so cool... circular containers only look good when they have only one item centered both vertically and horizontally. Plus long titles are cut at the beginning.

I do like it, but I will make them less circular. Anyway, they need to look different to the rest of the nodes.

> * Value label should be aligned with the node title.

👍 

> * Right after moving a node in the workbench, no d&d is possible from the in/out ports of the node.

Will check

> * The links are super hard to select for removal.

That was always the case

**Review by ignapas — CHANGES_REQUESTED** [review]
looking great... thanks for the corrections... I just picked a couple of things while clicking around
* arrows start from the wrong height in the param node, once you move the node, they update correctly
* it is possible to create a param node from an output, and the arrow ends in the output of the param node, looking weirdly
Peek 2021-07-22 17-32

**Comment by odeimaiz** [comment]
> looking great... thanks for the corrections... I just picked a couple of things while clicking around
> 
> * arrows start from the wrong height in the param node, once you move the node, they update correctly
> * it is possible to create a param node from an output, and the arrow ends in the output of the param node, looking weirdly
>   Peek 2021-07-22 17-32

Done, thanks for testing 👌

**Review by ignapas — APPROVED** [review]

**Review by GitHK — COMMENTED** [review]
The following issue happens to me:
- look at the bar with the study name and service name how it changes after you go in and out of the service
- the entire UI ends up being blocked in the end
Jul-27-2021 16-36-48

**Comment by odeimaiz** [comment]
> The following issue happens to me:
> 
> * look at the bar with the study name and service name how it changes after you go in and out of the service
> * the entire UI ends up being blocked in the end
>   Jul-27-2021 16-36-48

Very weird, and, obviously, it doesn't happen to me.

Could you, please, open the dev-tools and check if you can get some information about what's failing? Thanks 👌

**Pull request merged**
