### PR TITLE
🎨 [Frontend] TIP.itis.swiss: Show Phase out message at Request Account

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

As requested by @calys, this PR makes the ``Request Account`` button in https://tip.itis.swiss/ behave differently. Hardcoded in the frontend code, it will pop a dialog saying:

```
This version of the planning tool will be phased out soon and no longer accepts new users.
Please visit TIP.lite or TIP instead. See here for more information.
```

PhaseOut

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Comment by calys** [comment]
awesome, thanks Odei.

**Review by pcrespov — COMMENTED** [review]
I generally prefer more flexible, dynamic solutions over hard-coded approaches, but I understand that, given this is a one-time scenario, a hard-coded method provides the largest return of investment.  :-)

**Review by sanderegg — COMMENTED** [review]
:+1:

**Review by GitHK — APPROVED** [review]

**Review by jsaq007 — APPROVED** [review]
👍🏼

**Pull request merged**
