### PR TITLE
UI fixes/improvements and more

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
- [x] Sort Organizations and Organization Members
- [x] "Add" collaborators button reacts to selected collaborators
- [x] FilePicker: Do not allow uploading multiple files
- [x] API requests include the product name in the header
- [x] Narrower minWidth panels for fitting better smaller screen resolutions
- [x] Include user's screen resolution in environment info when creating issue
- [x] Larger ti-solutions logo to avoid stretching
- [x] Using all links provided in the statics
- [x] Removed unused classes/libraries
  - gridster
  - loader.html

## Related issue number
closes ITISFoundation/osparc-issues#311
closes FB: 135370

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]

**Comment by GitHK** [comment]
@sanderegg @odeimaiz to completely avoid further confusion will it be possible to rename the `File Picker` to `Single File Picker`?

**Review by GitHK — CHANGES_REQUESTED** [review]
All looks good, I have one request which I think will help a lot.

While it is nice to have the screen resolution, it would be better to have the window resolution. When opening the issue I had a screen resolution: `screenWidth=2560, screenHeight=1440` and a window resolution `window.innerWidth=1650, window.innerHeight=433` (the debug console was opened).
I think this extra information will help a lot.

**Comment by odeimaiz** [comment]
> All looks good, I have one request which I think will help a lot.
> 
> While it is nice to have the screen resolution, it would be better to have the window resolution. When opening the issue I had a screen resolution: `screenWidth=2560, screenHeight=1440` and a window resolution `window.innerWidth=1650, window.innerHeight=433` (the debug console was opened).

Good point. Added

**Review by pcrespov — APPROVED** [review]

**Review by GitHK — APPROVED** [review]
👍

**Pull request merged**
