### PR TITLE
🐛 [Frontend] Fix: Selected Pricing Unit bgColor

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

reported by @matusdrobuliak66 @mguidon 

The selection (what the user clicked) was properly transmitted to the backend, but its background color wasn't updated.

### Bonus:
- [x] Do not allow changing selection in the list of units in the service description card

Bug:
Bug

Fix:
Fixed

## Related issue/s

closes https://github.com/ITISFoundation/osparc-simcore/issues/6643

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by mguidon — APPROVED** [review]
THANKS

**Review by matusdrobuliak66 — APPROVED** [review]
thanks!

**Review by GitHK — APPROVED** [review]

**Review by pcrespov — COMMENTED** [review]
thx

**Review by sanderegg — COMMENTED** [review]
thanks

**Pull request merged**
