### PR TITLE
Added background heads for Academy Lite and default

### PR DESCRIPTION
**Pull request by jsaq007**
## What do these changes do?
Adds background images for the login page for S4L lite and academy

Screenshot 2024-03-11 at 15 15 34
Screenshot 2024-03-11 at 15 16 13
Screenshot 2024-03-11 at 15 16 54

## Dev-ops checklist

- [x] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by odeimaiz — APPROVED** [review]
Thanks!

**Review by mguidon — APPROVED** [review]
Boom!

**Review by elisabettai — APPROVED** [review]
🤩 🤩 🤩 
Minor: it looks like the logo have different distances from the username/password form fields, in case this is not intentional.

**Review by sanderegg — APPROVED** [review]

**Comment by jsaq007** [comment]
> 🤩 🤩 🤩 Minor: it looks like the logo have different distances from the username/password form fields, in case this is not intentional.

Yes. I have requested the images in the same place and scale. But these would be added to assets repo and would correct that.

**Review by pcrespov — APPROVED** [review]
:fire:

**Pull request merged**
