### PR TITLE
⬆️Maintenance: upgrade static-webserver to latest 2.32.1-alpine

### PR DESCRIPTION
**Pull request by sanderegg**
## What do these changes do?

- the venerable static-webserver which boasted version v1.16.0-alpine seems to have a memory leak and is 3 years old
- the new 2.32.1-alpine is the latest, built now on Rust and does not seem to show the same problem
btop reports about 65MB of memory usage and quite stable

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by YuryHrytsuk — APPROVED** [review]
Amazing!

**Review by mrnicegyu11 — APPROVED** [review]
abfahrt! 🚗

**Review by pcrespov — APPROVED** [review]
seems a very smooth migration :-)

**Review by odeimaiz — APPROVED** [review]
💅

**Pull request merged**
