### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
- [x] Navigation Bar with Icons
- [x] Svg lib initialization improved
- [x] studycard.Large replaces StudyDetailsEditor
  - Edit options to whatever is editable or has its dedicated view directly on Study Details

NavBar with icons
image

Old StudyDetailsEditor:
image

New studycard.Large:
image

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
very pretty, nice work!

**Review by pcrespov — APPROVED** [review]
very nice.
for the classifiers, you add the identifier, right? If it is an RRID, can you perhaps add the link to scrunch?

**Comment by odeimaiz** [comment]
> very nice. Some minors
> 
> * for the classifiers, you add the identifier, right? If it is an RRID, can you perhaps add the link to scrunch?
> * the uuid I think should only be shown to tester or in some kind of advanced section.
>   
>   * Capitalize the label, i.e. `UUID` instead of `uuid`

- In the Classifiers section, we will only show the number of classifiers assigned and the Classifiers dedicated view be available next to it. Also, we now have a different way to display them: the tree without checkboxes for view mode and the existing tree with checkboxes for editing.
- UUID only for tester + I added a copyToClipyboard option

**Review by KZzizzle — APPROVED** [review]
I love it, especially the icons for manuals and feedback!!! Well done Odei!

Minor request: could the description in the medium and large tiles also have the title "Description" in bold? Just because all the other fields have the bold titles.

**Comment by odeimaiz** [comment]
> I love it, especially the icons for manuals and feedback!!! Well done Odei!
> 
> Minor request: could the description in the medium and large tiles also have the title "Description" in bold? Just because all the other fields have the bold titles.

Done 💪

**Comment by KZzizzle** [comment]
> > I love it, especially the icons for manuals and feedback!!! Well done Odei!
> > Minor request: could the description in the medium and large tiles also have the title "Description" in bold? Just because all the other fields have the bold titles.
> 
> Done 💪

So SPEEDY

**Pull request merged**
