### PR TITLE
Clusters in frontend

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Provides access to the clusters resource from the frontend:
- cluster_id optional field when a computation is started
- CRUD operations on clusters

Run with cluster_id:
RunWithCluster

CRUD operations on clusters:
CRUDCluster

### CODE REVIEW

**Review by sanderegg — APPROVED** [review]
pretty much amazing!!

**Review by pcrespov — COMMENTED** [review]
:+1:

**Review by ignapas — APPROVED** [review]
I got some weird behavior by adding collaborators to a cluster, then logging in with that collaborator and not being able to see the details. After trying again, it was working intermittently. Also when coming back to the cluster's creator, not every cluster was being loaded, and after fetching them again, for example by deleting the one listing, then the rest were coming.
Can I test again once both back and front ends are working well together and there is some real functionality?

**Comment by odeimaiz** [comment]
> I got some weird behavior by adding collaborators to a cluster, then logging in with that collaborator and not being able to see the details. After trying again, it was working intermittently. Also when coming back to the cluster's creator, not every cluster was being loaded, and after fetching them again, for example by deleting the one listing, then the rest were coming.

There was an issue with the cache, fixed, thanks!

> Can I test again once both back and front ends are working well together and there is some real functionality?

Not sure what functionality you really want to test... as shown in the animations, if the clusters are listed in the SelectBox and the correct cluster_id is sent in the "start" call, then all the frontend can do is there.

**Review by KZzizzle — APPROVED** [review]
Looks really cool! From a purely UI perspective would it be possible to have a split button (e.g. https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns) for the Run button where you could choose the cluster? The reason for this is to not crowd the top menu bar. That would also make the cluster more obviously associated with the "Run" function.  

Other than that awesome and I'm excited to see it in action! I also like the same menu style for assigning members and permissions to each cluster.

**Comment by odeimaiz** [comment]
> Looks really cool! From a purely UI perspective would it be possible to have a split button (e.g. https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns) for the Run button where you could choose the cluster? The reason for this is to not crowd the top menu bar. That would also make the cluster more obviously associated with the "Run" function.

That was our first approach, but the Run button already gets split when a node is selected (Run/RunSelection).

I think that at some point we will end up having a Run Dialog with all the options: Run/RunSelection, Select Cluster, UseCache, MyCreditCard details....

**Pull request merged**
