### PR TITLE
Some enhancements and bug fixes

### LINKED ISSUE #1567: Service submission email has wrong subject
Someone submitted a new service candidate and the mail's subject shows the prefix ``TEST: ``, which should only be used in testing environments.

### PR DESCRIPTION
**Pull request by ignapas**
## What do these changes do?

* Fixes wrong subject in service submission email
* **Added osparc.window.Window component with ``clickAwayClose`` function.**
* Added faded modal overlay.

## Related issue number

closes #1567 #1609 #1607 

## How to test

* Service submission email has right subject
* Check window styles, modal overlays and click away close
* Can edit study info from dashboard
* Dashboard studies update after name change inside study

#### Click away to close and modal overlay
In PR, click away is only activated for permissions window.
clickaway

## Checklist

- [ ] Did you change any service's API? Then make sure to bundle document and upgrade version (``make openapi-specs``, ``git commit ...`` and then ``make version-*``)
- [ ] Unit tests for the changes exist
- [ ] Runs in the swarm
- [ ] Documentation reflects the changes
- [ ] New module? Add your github username to [.github/CODEOWNERS](.github/CODEOWNERS)

### CODE REVIEW

**Comment by ignapas** [comment]
@GitHK @Surfict There might be a problem here with the file cache in the actions... Frontend testing is failing although I already pushed the code to solve them

**Comment by GitHK** [comment]
> @GitHK @Surfict There might be a problem here with the file cache in the actions... Frontend testing is failing although I already pushed the code to solve them

From what I see is eslint is complaining about something. Caching should not be the issue.

**Comment by ignapas** [comment]
> > @GitHK @Surfict There might be a problem here with the file cache in the actions... Frontend testing is failing although I already pushed the code to solve them
> 
> From what I see is eslint is complaining about something. Caching should not be the issue.

I know but those are corrected!

**Comment by GitHK** [comment]
> > > @GitHK @Surfict There might be a problem here with the file cache in the actions... Frontend testing is failing although I already pushed the code to solve them
> > 
> > 
> > From what I see is eslint is complaining about something. Caching should not be the issue.
> 
> I know but those are corrected!

Would you mind adding a line where the CI dumps the file before sling runs? You could simply do it as a cat command.

**Pull request merged**
