### PR TITLE
Breadcrumb Navigation

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
This PR brings nicer a breadcrumb navigation plus some improvements in the slideshow viewer.

## Related issue number
related to ITISFoundation/osparc-issues#327
closes ITISFoundation/osparc-issues#359

- Workbench mode:
image

- Guided mode:
image

#### Bonus:
- Some Grouping features were brought back
- New TI Treatment Planning logo
image

## Checklist

- [ ] Did you change any service's API? Then make sure to bundle document and upgrade version (``make openapi-specs``, ``git commit ...`` and then ``make version-*``)
- [ ] Unit tests for the changes exist
- [ ] Runs in the swarm
- [ ] Documentation reflects the changes
- [ ] New module? Add your github username to [.github/CODEOWNERS](.github/CODEOWNERS)

### CODE REVIEW

**Review by GitHK — COMMENTED** [review]
Some feedback:

- the changes look nice and work as described
- if a FilePicker is selected as a service in the preview mode, the "Starting FilePicker" window is shown forever
- If I add too many slides, the layout is broken and the next and prev buttons disappear; also the breadcrumb bar on top is not fully visible.

**Comment by odeimaiz** [comment]
https://github.com/ITISFoundation/osparc-issues/issues/359

**Review by ignapas — CHANGES_REQUESTED** [review]
It's amazing how you managed to do this! Very nice... although the amount of code needed (svg library + your own) to create the breadcrumb splitter, I think it's too much. I wouldn't do this kind of personalised widgets too often.
Some little things:
* A controlled breadcrumb widget. Instead of having the logic in ``NavigationBar``, having a separate Breadcrumb widget that takes a path of node ids, and renders itself as a series of ToggleButtons and separators, or even better, as a series of extended ToggleButtons that incorporate their separators when appropriate, and manage their state changes on hover, clicking, etc.
* On hover, the separator is not highlighted and looks a bit weird. 
image
* I don't know if related to this PR, but grouping nodes no longer works. Links created inside the group are not saved, and the edge stays dashed. I cannot ungroup them either..
groupingfail 
image
* I see some hardcoded widths and heights

**Comment by odeimaiz** [comment]
@GitHK @ignapas To be tackled in this PR:
- [ ] If I add too many slides, the layout is broken and the next and prev buttons disappear; also the breadcrumb bar on top is not fully visible.
- [x] A controlled breadcrumb widget
- [ ] Remove hardcoded widths and heights

**Review by ignapas — CHANGES_REQUESTED** [review]
awesome!!
Sorry, there is something I didn't see before... not so important... there is a problem when you are inside some group views, the breadcrumb disappears and the previous version shows up
groupsandbread

**Review by ignapas — APPROVED** [review]

**Review by pcrespov — APPROVED** [review]

**Review by KZzizzle — APPROVED** [review]

**Pull request merged**
