### PR TITLE
🎨 [Frontend] UX: Create Study from Template

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Currently, when creating a Study from a Template:
1) waiting: there is a view showing that the data is being copied (long running task)
2) user input required: once copied, the study is created and the the Study Options (rename, select credit account, tiers) are shown to the user
3) waiting: then the study opens

In order to improve the UX, in this PR, instead of waiting, then user input and then waiting again, the steps 1 and and 2 are switched, so that user's input is required right after opening the template and then the data is copied and finally the brand new study opened.

Before:
Before

After:
After

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by GitHK — COMMENTED** [review]
Question: should we not adapt the backend to take as input these parameters that you are caching, while it is coping the study?

**Comment by odeimaiz** [comment]
> Question: should we not adapt the backend to take as input these parameters that you are caching, while it is coping the study?

That could also be a solution.

Yet another solution would be that the study is created right away (so I can play with its metadata) and then the data copy starts...

**Review by sanderegg — COMMENTED** [review]
nice!

**Review by jsaq007 — APPROVED** [review]
👍🏼

**Review by pcrespov — COMMENTED** [review]
:+1:

**Review by pcrespov — APPROVED** [review]

**Pull request merged**
