### PR TITLE
Dashboard UI/UX: Study multi-selection

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

The selection option in the study card was removed and, in order to start/stop study multiselection, a "Select" toggle button was added on the top right list of studies.

MultiSelection

**Bonus:**
```Import``` button depends on the WEBSERVER_EXPORTER plugin

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
:+1:

**Review by KZzizzle — APPROVED** [review]
totally awesome!

**Review by ignapas — COMMENTED** [review]
Looks good. Maybe it would be more clear if the check mark icon was removed from the button and the text changed to ``Select items``. Then the text can change to ``Cancel selection`` when selection mode is active. Maybe only in that case add the cross icon.

**Comment by odeimaiz** [comment]
> Looks good. Maybe it would be more clear if the check mark icon were removed from the button and the text changed to `Select items`. Then the text can change to `Cancel selection` when selection mode is active. Maybe only in that case add the cross icon.

Done, thanks

**Review by sanderegg — APPROVED** [review]

**Review by pcrespov — COMMENTED** [review]
:+1:

**Pull request merged**
