### PR TITLE
🐛 [Frontend] Guest viewers

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

Spotted in the e2e-portal VTK_dispatcher, the ``NodeViewer`` for guest users sometimes fails during the node start up process, because the frontend wasn't listening to the socket. This PR fixes it.

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
:tada:

**Review by sanderegg — COMMENTED** [review]
👍

**Review by jsaq007 — APPROVED** [review]
👍🏼

**Review by matusdrobuliak66 — APPROVED** [review]
cool, thanks!

**Pull request merged**
