### PR TITLE
Draw rectangle for multiselection

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

DrawRectangle

## Related issue/s
closes https://github.com/ITISFoundation/osparc-issues/issues/465

### CODE REVIEW

**Review by mguidon — APPROVED** [review]
HOT. Next step, a helper grid for nice alignments.

**Review by sanderegg — APPROVED** [review]
AMAZING! very cool!

**Review by pcrespov — COMMENTED** [review]
GREAT!

**Comment by KZzizzle** [comment]
super nice, thanks @odeimaiz !

**Pull request merged**
