### PR TITLE
🐛 test_port_key_sequential_event_generation is still flaky

### PR DESCRIPTION
**Pull request by GitHK**
## What do these changes do?

Just marking to retry, CI fails. Create issue to track https://github.com/ITISFoundation/osparc-simcore/issues/3694

## Related issue/s

- https://github.com/ITISFoundation/osparc-issues/issues/675

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]

**Comment by pcrespov** [comment]
@GitHK keep an eye on this one ... it might be a hidden bug

**Comment by GitHK** [comment]
> @GitHK keep an eye on this one ... it might be a hidden bug

Yes, I also thought about this. I'll do another review of it next sprint.

**Review by sanderegg — APPROVED** [review]
please do not forget, add the case to the epic, it makes it easier to create the list of changes for the reviews:
image

**Comment by GitHK** [comment]
closing, out of date

**Pull request closed without merging**
