### PR TITLE
✨ Expose message templates to POs

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

This PR exposes the message templates (emails, SMSs) to the POs in the PO Center.

The backend is not ready yet. So the frontend mocked the get request:
MessageTemplates

### CODE REVIEW

**Review by elisabettai — COMMENTED** [review]
Very cool, looking forward to use this instead of my templates in Google Doc. 😉 

Does the text have to contain HTML notations? E.g., can you add new lines without using `<b>`?
That is a bit too much to ask to non-dev POs.
I think we also have the same problem in other fields, e.g. in the study description.

**Comment by odeimaiz** [comment]
> Very cool, looking forward to use this instead of my templates in Google Doc. 😉
> 
> Does the text have to contain HTML notations? E.g., can you add new lines without using `<b>`? That is a bit too much to ask to non-dev POs. I think we have the same problem in other fields, e.g. in the study description.

If you want fancy emails it need to be html

**Comment by elisabettai** [comment]
> > Very cool, looking forward to use this instead of my templates in Google Doc. 😉
> > Does the text have to contain HTML notations? E.g., can you add new lines without using `<b>`? That is a bit too much to ask to non-dev POs. I think we have the same problem in other fields, e.g. in the study description.
> 
> If you want fancy emails, it needs to be html

I'd go for markdown then.

**Comment by odeimaiz** [comment]
> > > Very cool, looking forward to use this instead of my templates in Google Doc. 😉
> > > Does the text have to contain HTML notations? E.g., can you add new lines without using `<b>`? That is a bit too much to ask to non-dev POs. I think we have the same problem in other fields, e.g. in the study description.
> > 
> > 
> > If you want fancy emails, it needs to be html
> 
> I'd go for markdown then.

Very good... but the current templates are already html

**Review by mguidon — APPROVED** [review]
Good stuff. I just dont like how the string "PO Center" looks like. No alternative?

**Review by pcrespov — APPROVED** [review]
:+1:

**Pull request merged**
