### PR TITLE
🎨 [Frontend] Highlight elements in Guided Tour

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

As requested by some of you, the main elements in the Guided Tour are now highlighted:
Blankets

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by ignapas — APPROVED** [review]
nice blankets :D

**Comment by odeimaiz** [comment]
> nice blankets :D

Thank you for the nice approach!!

**Review by GitHK — APPROVED** [review]
Fancy ✨

**Review by elisabettai — APPROVED** [review]
Nice, thanks a lot!

You can maybe make the contrast between the highlighted elements and rest even bigger.

**Review by pcrespov — COMMENTED** [review]
👍

**Comment by odeimaiz** [comment]
> Nice, thanks a lot!
> 
> You can maybe make the contrast between the highlighted elements and rest even bigger.

0.4 is the opacity value used throughout the application for highlighting modal items. I would rather stick to the same value 👍

**Pull request merged**
