### PR TITLE
🎨 [Frontend] Move multiple studies at once

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?

- [x] Move multiple studies at once
- [x] Merge Move-to-Folder and Move-to-Workspace
- [x] UI/UX Workspace&Folders tree: In order to avoid the arrow that disappears, go one step ahead the user and load the next level too.
- [x] UI/UX Loading projects: Updates the "Loading..." card's appearance, now it's just a semi transparent spinning wheel

Move multiple studies at once
MoveMultipleStudies

UI/UX
ArrowsAndSpinners

## Related issue/s

closes https://github.com/ITISFoundation/osparc-simcore/issues/6404
related to https://github.com/ITISFoundation/osparc-simcore/issues/6386

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

### CODE REVIEW

**Review by matusdrobuliak66 — APPROVED** [review]
:1st_place_medal:

**Review by pcrespov — COMMENTED** [review]
Nice!

@matusdrobuliak66 for these features it would be good that we implement batch operations int he rest API, i.e. batchCreate, batchGet, batchDelete, batchUpdate, batchReplace.

**Review by GitHK — COMMENTED** [review]
👍

**Review by jsaq007 — APPROVED** [review]
👍🏼

**Pull request merged**
