### PR TITLE
Services update

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
This PR allows user with write access on a study to update services from the Study Browser.

The criteria for determining if a service is updateable to a higher version is the following:
- After some discussion, in this first iteration, only patch updates are allowed
- input keys in source need to be in destination
- [keyId, type, unit] source input values need to be the same in destination
- [keyId, type, unit] source output values need to be the same in destination
- fileToKeyMap and defaultValue are not taken into account. Is that correct?

UpdateServices

## Related issue/s
related to https://github.com/ITISFoundation/osparc-simcore/issues/2244

### CODE REVIEW

**Comment by sanderegg** [comment]
I find the feature very nice.
now for the latest compatible:
- say I have version 1.0.0 and I publish 2.0.0 with the the same inputs/outputs it will be listed right? and following semver this might very well come with breaking changes. what happens if after the update my study is broken? it might even save some state that is not backward compatible and the studies is broken until we get the data back.
--> to aleviate this: I would propose to create a backup of the project before updating (could be optional if the user wants to take risks)

**Comment by odeimaiz** [comment]
> I find the feature very nice.
> now for the latest compatible:
> 
> * say I have version 1.0.0 and I publish 2.0.0 with the the same inputs/outputs it will be listed right? and following semver this might very well come with breaking changes. what happens if after the update my study is broken? it might even save some state that is not backward compatible and the studies is broken until we get the data back.
>   --> to aleviate this: I would propose to create a backup of the project before updating (could be optional if the user wants to take risks)
> 
> NOTE: maybe the risk could be color-coded... if major version changes in red, if minor in yellow and if patch then...

Uff, I find this a huge overkill, a backup of the study every time you update one service... how do you know it will break? how do you discard the broken? one and take the latest backup?

If you think it's too risky, we can do the inputs/outputs compatibility check and only allow patch updates.

**Comment by sanderegg** [comment]
> Uff, I find this a huge overkill, a backup of the study every time you update one service... how do you know it will break? how do you discard the broken? one and take the latest backup?

Well the thing is you cannot know it until you do it and then it is too late. the node + its data might be broken (I agree that for computational services that is I think not a problem, but for dynamic services??)
no, what I proposed, is to allow the user to do a clone of the study before applying the update. that is one call to the API away no?
I agree that updating patches will probably never break.. until it does. updating minor versions is more risky. updating major versions can be quite risky.

> 
> If you think it's too risky, we can do the inputs/outputs compatibility check and only allow patch updates.

**Review by sanderegg — APPROVED** [review]
ok. just beware of:
- if the catalog auto-upgrades the rights.. we might end up in issues where the dynamic services state file is broken
- when computational services are updated, the scheduler will not re-run them automatically

**Review by KZzizzle — COMMENTED** [review]
Very nice interface and very intuitive.

I agree with SAN that there should be some backup in case the update breaks something. When we get the feature to duplicate nodes instead of full studies, that could be another option. 

One thing we need to get right is TN with his huge studies in JupyterLabs. This one will need to be updated all the time (maybe less with the dynamic sidecar) and it would be super bad if the stuff inside gets corrupted with no backup... On the other hand, ANE mentioned that duplicating one of these giant studies would take many hours... @sanderegg @GitHK ?

**Review by pcrespov — APPROVED** [review]
I think it is a nice step in the right direction but I agree as well with the statements above.
Why not restricting this feature to ``testers`` until we address other issues? Can you perhaps add those comments to the case #2244?

**Pull request merged**
