### PR TITLE
Ease Input file assignment

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
- [x] File/Link like nodeUI when there is a selection in FilePicker
- [x] Back to previous node after selecting file in FilePicker
- [x] Input file can be selected directly from the settings field that requires a file

image

selectFile

#### Bonus:
- Rollover text for Theme switch

## Related issue/s
closes https://github.com/ITISFoundation/osparc-issues/issues/478

### CODE REVIEW

**Review by KZzizzle — APPROVED** [review]
It's super nice Odei! I really don't have much to say other than as a user it's a bit annoying that the text field of the node UI accommodates only ~13 characters. I have the impression that most (>>50%) file names are longer than that, especially due to file extensions (imagine .smash) so basically every file name would be cut off with "..." I understand that it's impossible to accommodate 100% of file names - would it be possible to enable multiple lines for a start?

Ability to add files directly in node settings is super!

**Review by ignapas — APPROVED** [review]
I think the Select File button shouldn't be disabled if a file is selected.. maybe changed to "Go to filepicker". I see the problem is that everytime it is pressed a new file picker is attached, and not reusing the previous one... maaaybe a bit confusing but idk.

**Review by pcrespov — APPROVED** [review]
👍

**Review by GitHK — APPROVED** [review]
👍

**Pull request merged**
